### ISSUE TITLE
Base uptime stats on search results

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#1003]
- [x] Create a nagios check for whether an application can return search results as expected
- [x] Base the weekly uptime reports on this stat

**Comment by bess** [comment]
![Nagios_Availability.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5515e9ab52d65b2000638516/125516c66e82c728ace21e0d46c6959d2a8d9096aeffbe4aa85cf29d254f336a6b48e13b628ae92dbc56395b4d5a46f812505943a9fedf7ff5e23b708a5d5ab9d66b0b7c902f0dbefad341eb5ee779c11ac7a4b6984dc8e23c20e58f8d4a391e061b8dff5427ed.png)

**Comment by bess** [comment]
@mark-dce Take a look at this screen shot and let me know if it's okay. This is what the nagios service report looks like, for a service check I just set up called `search_results`. I just set the check up, so there aren't really any numbers there yet.

**Comment by bess** [comment]
![Nagios_Availability.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5515e9ab52d65b2000638516/125516c66e82c728ace21e0d46c6959d2a8d9096aeffbe4aa85cf29d254f336a6b48e13b628ae92dbc56395b4d5a46f812505943a9fedf7ff5e23b708a5d5ab9d66b0b7c902f0dbefad341eb5ee779c11ac7a4b6984dc7e23c20e58f8d4a391d061f80fe5d27ed.png)

**Comment by mark-dce** [comment]
This looks like a great internal facing report to help us understand how the service is running.

It feels like there's a lot of extraneous information here that I'm not sure exactly how to interpret - e.g. what does it mean if the report shows `OK Unscheduled: 95%` and `Warning scheduled: 5%` - are we in SLA compliance?  

Is there a way we could just provide the "Total" lines in a client facing report?  If I understand everything shown here, the one critical number here from an SLA standpoint it `OK Total %` 

Can you give this up to four more hours to see if there's a simpler version we can share with clients?  (i.e. I think we'll might easily end up spending 4 hours explaining the nuances of this more detailed report as clients try to understand what it's telling them.)  If we can't get anything better out of nagios in that time, we can go with this.

**Comment by bess** [comment]
![ETD_Uptime_for_Apr_16__2018_-_Apr_23__2018_-_bess_curationexperts_com_-_Data_Curation_Experts_Mail.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5515e9ab52d65b2000638516/125516c66e82c728ace21e0d46cda0be1cb793bd86e4ba7ca252e2ab0856354c78529c1422d5b270800f44201f1d21ae42373046fcf88144bbd96e25c91f64be942f0e309f624ff9f0c24afd45f94fd810d8d9a1e53891ac6c4a94cecd1e7a475a46e68a1575f5db0f8b378b1ab81147b8017621b92c632f0386146729633375a3fad80380d334f7ee172f56c9b2b0fd1046a92acadb1b33320b0ff5776bff57189b6a8a477057eab0c6f9124d0a1709c8eec2d2afa2.png)

**Comment by bess** [comment]
@mark-dce I can send an email (see above) that only has the date range and the service uptime number in it. It looks very bare-bones, but maybe that's okay? Is there anything else you'd like to add to it?

**Comment by mark-dce** [comment]
Can you get it to emit some kind of name / environment?  (next to the percentage).  If not, let's send a sample to Emory and explain what the new report checks and that we propose sending this (more accurate) report going forward.

**Comment by bess** [comment]
![ETD_Uptime_for_Apr_17__2018_-_Apr_24__2018_-_bess_curationexperts_com_-_Data_Curation_Experts_Mail.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5515e9ab52d65b2000638516/125516c66e82c728ace21e0d46cda0be1cb793bd86e4ba7ca252e2ab0856354c78539c1422d5b270800f44201f1d21ae45373046fcf88144bbd96e25c91f64be942f0e309f624ff9f0c24afd45f94fd810d8d9a1e53891ac6c4a94cecd1e7a475a46e68a1575f5db0f8b378b1ab81147b8017621b92c632f0386146729633375a3fad80380d334f7ee172f56c9b2b0fd1046a92acadb1b33320b0ff5776bff57189b6a8a477157eab0c6f9124b0c1607cdebc3dbafa2.png)

**Comment by bess** [comment]
@mark-dce Nagios doesn't do the kind of report you're asking for, so I'm just querying the report with a ruby script and composing an email with only the information we want. See https://github.com/curationexperts/sla_nagios_email/blob/master/sla_report.rb for the script.

I added a couple of options for indicating the environment (see image above). Let me know if either of those works or if you want something different.

**Comment by bess** [comment]
I went with the second option in the interests of getting something out there. We can update it as needed.

**Comment by mark-dce** [comment]
👍
