### ISSUE TITLE
Complete ART/Security Review Questions

### ISSUE THREAD

**Issue by tmiles2** [curationexperts/laevigata#101]
The ART/Security question have been provided to Rosalyn and Shanita to share with pertinent parties.

- [x] Provide responses to questions in [Architecture Review Questions.docx](https://app.box.com/files/0/f/24726825539/ART_Security_Review_Docs)
- [x] Provide responses to items in [Security requirements for ETD.xlsx](https://app.box.com/files/0/f/24726825539/1/f_162106088898) Related to #233
- [x] Architecture Diagram - #103

**Comment by mark-dce** [comment]
Blacked by #103 - Architecture Diagram

**Comment by shanitajohn** [comment]
Architecture Diagram completed and here: https://drive.google.com/file/d/0B8imcSJ3yFamWmJISWhjRDBvUTQ/view?usp=sharing
