### ISSUE TITLE
Our splunk service has stopped working

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#1010]
We need to either pay for a production license or set up something different. The team seems to want us to try fluentd and I'm game to try it. The more I think about it the more I think having a log aggregator is vital to our hosting work, and the more I think we should host it ourselves so it will scale and we'll develop expertise in it.

**Comment by bess** [comment]
Mark sent an email asking them to contact us about a production sized instance.

**Comment by mark-dce** [comment]
Fixed and opening a new ticket to automate spunk setup for new servers
