### ISSUE TITLE
Password protect OkComputer

### ISSUE THREAD

**Issue by no-reply** [curationexperts/laevigata#1016]
The `okcomputer` endpoints for laevigata are public. This presents some minor DDOS risk, especially if fairly expensive tasks are added.

We should add basic authentication. https://github.com/sportngin/okcomputer#requiring-authentication

**Comment by mark-dce** [comment]
We aren't exposing any confidential info through the ok computer endpoint, so closing this issue at this time.

`https://etd.library.emory.edu/okcomputer?lang=en` gives
> default: PASSED Application is running (0s)
