### ISSUE TITLE
Upgrade to Fedora 4.7.5

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#1023]
- [x] Go through the 4.7.3 upgrade notes and check for potential data corruption issue (see https://wiki.duraspace.org/display/FF/Fedora+4.7.3+Release+Notes)
- [x] Then upgrade to 4.7.5 so we're on the latest version
- [x]  Update our development configuration to run the same fedora version as in production

**Comment by mark-dce** [comment]
Should this also include updating our development configuration to run the same fedora version as in production? I.E. specify a version here https://github.com/curationexperts/laevigata/blob/master/.fcrepo_wrapper and here https://github.com/curationexperts/laevigata/blob/master/config/fcrepo_wrapper_test.yml?
