### ISSUE TITLE
Why are all these users created at startup?

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1025]
**ISSUE**
I just ran through the setup instructions in the readme and I have 27 users in my database???

**DETAILS**
```
irb(main):008:0> User.all.each{|u| puts "#{u.id}: #{u.created_at}, email: #{u.email}, name: #{u.display_name}" }
  User Load (0.4ms)  SELECT "users".* FROM "users"
1: 2018-05-16 20:06:10 UTC, email: , name: 
2: 2018-05-16 20:06:10 UTC, email: , name: ETD Notification System
3: 2018-05-16 20:06:10 UTC, email: , name: 
4: 2018-05-16 20:06:10 UTC, email: , name: 
5: 2018-05-16 20:06:45 UTC, email: , name: 
6: 2018-05-16 20:06:45 UTC, email: , name: 
7: 2018-05-16 20:06:47 UTC, email: , name: 
8: 2018-05-16 20:06:47 UTC, email: , name: 
9: 2018-05-16 20:06:49 UTC, email: , name: 
10: 2018-05-16 20:06:49 UTC, email: , name: 
11: 2018-05-16 20:06:51 UTC, email: , name: 
12: 2018-05-16 20:06:54 UTC, email: , name: 
13: 2018-05-16 20:06:57 UTC, email: , name: 
14: 2018-05-16 20:07:00 UTC, email: , name: 
15: 2018-05-16 20:07:04 UTC, email: , name: 
16: 2018-05-16 20:07:08 UTC, email: , name: 
17: 2018-05-16 20:07:12 UTC, email: , name: 
18: 2018-05-16 20:07:16 UTC, email: , name: 
19: 2018-05-16 20:07:21 UTC, email: , name: 
20: 2018-05-16 20:07:26 UTC, email: , name: 
21: 2018-05-16 20:07:31 UTC, email: , name: 
22: 2018-05-16 20:07:37 UTC, email: , name: 
23: 2018-05-16 20:07:43 UTC, email: , name: 
24: 2018-05-16 20:07:49 UTC, email: , name: 
25: 2018-05-16 20:07:56 UTC, email: , name: 
26: 2018-05-16 20:08:03 UTC, email: , name: 
27: 2018-05-16 20:08:10 UTC, email: , name: 
```

**Comment by val99erie** [comment]
@mark-dce  I'm guessing that these are all the workflow approvers for each AdminSet.  (There are around 20 AdminSets, each with at least one approver, plus some superusers).  They were probably created when you called the workflow setup script.

If you print out the `ppid` or `uid` for the User records, you'll probably see what they are for.  You can match them up with the users in `config/emory/admin_sets.yml` or `config/emory/superusers.yml`

**Comment by mark-dce** [comment]
The `uid` is empty - see my printout about.  I didn't know to check `ppid` at the time I was looking.  I agree that they are probably created during some setup process.

I'm concerned that we have a bunch of user accounts in the system that are super hard to distinguish from one another because they have no UID, Email, or Name.

**Comment by val99erie** [comment]
It looks like you are printing `u.id`, not `u.uid`
