### ISSUE TITLE
Registered role is repeated too many times

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1027]
**ISSUE**
When I log into production as an administrator and look at admin set participants, I see roles repeated an arbitrary number of times.  See https://etd.library.emory.edu/admin/admin_sets/05741r701/edit?locale=en#participants

**STEPS TO REPRODUCE**
1. Login as `tezprox`
1. Click on "Administration" in the top navigation bar
1. Click on "Administrative Sets" in the left navigation bar
1. Choose (click on) any administrative set 
1. Click the Edit button for the administrative set
1. Click on the Participants tab
1. Scroll down to the Depositors section

Each admin set seems to have a different number of entries.

<img width="1314" alt="1027 - depositors error" src="https://user-images.githubusercontent.com/3064318/40147139-0993faf6-592e-11e8-9739-84a2b49db076.png">

**Comment by bess** [comment]
No longer an issue in 2.x
