### ISSUE TITLE
Provide architecture diagram of the system

### ISSUE THREAD

**Issue by tmiles2** [curationexperts/laevigata#103]
Show a service level and network connection level diagram of the interconnections between the 
* ETD Application running at AWS
* Emory Authentication System (shibboleth)
* Registrar and ESD feeds as needed

**ACCEPTANCE**
- [x] Show individual servers on AWS side
- [x] Represent services or feeds on Emory side
- [x] Represent submitter and approver browsers
- [x] Show which systems communicate with which others including protocols in use
- [x] Show where network security boundaries exist and which ports and protocols can be passed
- [x] Represent what type of data is transferred between systems
- [x] Use multiple diagrams or layers as needed to cover all of the above

**Comment by mark-dce** [comment]
@tmiles2 is this required as part of the submission for the ART review?

**Comment by tmiles2** [comment]
@mark-dce  Yes, I will attach the diagram to my request for  ART review

**Comment by mark-dce** [comment]
@acozine is going to take a first pass and then share out for further enhancement / refinement

**Comment by acozine** [comment]
First pass: https://docs.google.com/drawings/d/1ztpNFxaEtbGzmKM0az2kpcdgYwVPrgP7OaEVZ-YzbqM

**Comment by mark-dce** [comment]
I've added detailed acceptance criteria.  

@acozine @bess @shanitajohn - can you schedule time to try to add in the remaining information outlined in the acceptance criteria.  The diagram should be able to answer questions such as:
* How are ETDs uploaded to the system, over what protocols, what servers are involved
* How is traffic to the VPC protected (what ports are open)
* Which systems at Amazon interact with which systems at Emory (over what protocols and ports)
* What data is transferred between client machines and AWs
* What data is transferred between Emory systems and AWS
* What data is transferred between AWS and Emory systems (hint: probably none)

You may need multiple diagrams to answer these pictures.  Feel free to use (and/or complete) any of the completed diagrams from #104 (Data Flow Diagrams) that would help answer the above questions.

**Comment by acozine** [comment]
Here's another piece of the picture: https://docs.google.com/drawings/d/1hrazRYdGZmsEwef8lae5ystrp8z93R56DkcnLcyYVqw/edit

**Comment by shanitajohn** [comment]
@acozine I know that this was completed / submitted, but can you do me a favor and just confirm that all of the checkboxes in Tiffany's original post can be closed, then move this to Done, please?
