### ISSUE TITLE
Document user setup process for dev environment

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1030]
**ISSUE**
As a team member I'd like to be able to get up and running quickly and in a way similar to what I've done for other DCE projects.

**ACCEPTANCE**
- [ ] Emory database user setup looks as much like other projects as possible
- [ ] The general pattern is documented in the project readme (or the DCE playbook if we can make it consistent)
- [ ] Any deviations from the general pattern are documented in the project readme under developer setup
  - [ ] UID and PPID requirements

**Comment by mark-dce** [comment]
Basically, what I'm looking for is instructions in the readme that lead me to be able to 
- [ ] set up a new student depositor user in my development environment
- [ ] set up a new school approver in my development environment
- [ ] set up a new super admin in my development environment
This can just be links to appropriate feature test that say "do the same setup these tests do" or they can be pointers to writ ups somewhere else, but right now, if I do the setup I'd expect to do for nurax or one of our other projects, I'm not successful in getting a user configured that I can use to log in with the appropriate access.

**Comment by bess** [comment]
Documentation here: https://github.com/curationexperts/playbook/pull/59

**Comment by mark-dce** [comment]
Probably this just needs README instructions on how to set SuperAdmin and Approver passwords

**Comment by mark-dce** [comment]
probably moot at this point.
