### ISSUE TITLE
Evaluate browser automation options

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1039]
- [X] Develop a short list of potential options
- [X] Choose one or two for a trial
- [x] Set up a simple (partial) feature test - e.g. check for a valid School+Department+Subfield choice

**Comment by jenlindner** [comment]
Using a free trial set up with Sauce Labs, I can locally run RSpec tests against their OS/browser infrastructure. The test visits QA, logs in as our test user, fills in all of the 'About Me' inputs except the School fields, checks that About Me is in an invalid state, fills in the School fields with Rollins data, and confirms the tab is now valid.

**Comment by jenlindner** [comment]
Some links for reference: 

Best Automated Testing Tools 2018 - https://medium.com/@briananderson2209/best-automation-testing-tools-for-2018-top-10-reviews-8a4a19f664d2
(Selenium and Watir, for Ruby/Linux)

https://www.usertesting.com - good site for UX testing
