### ISSUE TITLE
Draw 'Data Flow' diagrams

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#104]
**STORY**
As a contributor to the development of the ETD repository, I'd like a visual representation of the system steps that happen to file before, during and after I deposit it, so that I can better understand the steps involved.

**ACCEPTANCE**
- [ ] Diagram developed
- [ ] Diagram reviewed by team
- [ ] Feedback incorporated
- [ ] Diagram posted to WIKI

**Comment by bess** [comment]
Blocked until we know what fields we need from ESD

**Comment by rotated8** [comment]
Link to fields review: https://emory.box.com/s/nhmxqfxd35opq6cx62rbdnk2r0k4pu2d

**Comment by mark-dce** [comment]
- [ ] User Login Data Flow: https://docs.google.com/drawings/d/1-LQZjbRm3D3nr-fekFeBzUtlxAwKKnlsQedH7LXxdYM/edit 
- [ ] ETD Initial Submission Data Flow: https://docs.google.com/drawings/d/1lln8-ZY7ZGFwp0MWLbIOpFlq0mvvyb0I9zjBojgqeh8/edit
- [ ] ETD Approval Data Flow: ...
- [ ] Changes requested Data Flow: ...

**Comment by shanitajohn** [comment]
Merge with #103
