### ISSUE TITLE
Ensure Spanish translations exist for corresponding i8n keys

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1047]
**ACCEPTANCE**
For each English keyword in https://github.com/curationexperts/laevigata/tree/master/config/locales
- [ ] Ensure a corresponding Spanish keyword exists

**Comment by bess** [comment]
Are we sure Spanish is a requirement? Can we ask? I seem to recall a conversation where they said they only want English.

**Comment by mark-dce** [comment]
This has not surfaced as an issue since the system has been in production, so closing the ticket.
