### ISSUE TITLE
Restrict "Switch Language" Options

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1048]
**ACCEPTANCE**
- [ ] English is an option
- [ ] Spanish is an option
- [ ] No other languages appear as options

NOTE: in release 1.6.2, Simplified Chinese appears as a dropdown option, but no local lavegata translations exist.  In the initial 2.0 upgrade testing, additional language options appeared, so we may need to think about white-listing English and Spanish explicitly.

**Comment by no-reply** [comment]
Confirming that `en`, `es` and `zh` are the only three languages in Hyrax 1.0.5. https://github.com/samvera/hyrax/tree/b155a6c09ba7b11110c512d3f7d4cf36529d1d13/config/locales

Based on this, I suspect we haven't previously called out the need to filter locales.

**Comment by mark-dce** [comment]
After discussion, we've decided to continue supporting all languages so that non-english indexers can continue to index the site - in order to make content available in a wider variety of searches outside of english speaking countries.

Going forward, this means we will need to update i8n files from hyrax and blacklight when upgrading major versions to ensure that new UI features continue to be equally accessible in non-english contexts.
