### ISSUE TITLE
Normalize non-standard characters in abstract and table of contents

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#1061]
Some legacy etds (see, e.g., https://legacy-etd.library.emory.edu/view/record/pid/emory%3Arrqvw) seem to have non-standard characters in the abstract and table of contents such that the first time we migrated them they appeared in  strange way. See attached screen shot for an example.

- [ ] ETDs with non-standard characters in the abstract or TOC get normalized

**Comment by bess** [comment]
<img width="778" alt="screen shot 2018-05-24 at 4 10 38 pm" src="https://user-images.githubusercontent.com/65608/40844247-68385020-6581-11e8-93a2-dc5e68ad3686.png">

**Comment by no-reply** [comment]
@bess I can confirm for this item in particular that this data explicitly appears in the `<mods:tableOfContents>`

**Comment by bess** [comment]
If it's in the original then fixing it is out of scope. Closing this ticket.
