### ISSUE TITLE
Add ssh timeout to all emory servers

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1069]
**ISSUE**
The new single-host servers appear to lack an ssh timeout.  Per our agreement with Emory IT, systems must have a 15 idle timeout.

> Vendor systems must automatically lock or logoff active console sessions after a period of inactivity of no more than 15 minutes.  

**ACCEPTANCE**
- [x] Idle ssh sessions are terminated within 15 minutes
- [x] Sessions are resilient against poor network connections (i.e. don't do a single keep alive at 15 minutes, terminate after 5 failed keep alives at 3 minute intervals)

**DETAILS**
http://manpages.ubuntu.com/manpages/trusty/man5/ssh_config.5.html - ServerAliveCountMax & ServerAliveInterval  
Also see https://github.com/curationexperts/ansible-samvera/issues/40

**Comment by bess** [comment]
Fix to this added to ansible-samvera and applied to qa and stage. It will get applied to prod when that box is built. This is now the default for our ssh config.

**Comment by bess** [comment]
I added this timeout config but it isn't working. I'll troubleshoot next week.

**Comment by bess** [comment]
I added a slightly different config, but it does do a timeout. Mark, let's talk later about whether you want to fine tune this, but for now we are complying with the Emory security requirement so I'd like to move on.

**Comment by mark-dce** [comment]
That's fine & why I had already written up https://github.com/curationexperts/ansible-samvera/issues/52.  I do think we will want some configurability going forward, but for now the key deliverable was compliance with the Emory security agreement that has my signature on it ;)
