### ISSUE TITLE
Update out of date dependencies

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#107]
Gemnasium is reporting some out of date dependencies. Update our gems so we're working with the latest versions and so we don't let this pile up.

**Comment by shanitajohn** [comment]
Schedule for updating out-of-date dependencies: every 2 weeks / at demo time. Anytime anyone wants to they are  welcome to complete the update, in a separate pull request. Will confirm every 2 weeks that we are up-to-date.
