### ISSUE TITLE
Sort embargoes by earliest date

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1070]
**ISSUE**
When I view the embargoes page in v2.0.0-alpha+sha.8e864f6, the items appear to be sorted in descending date order.  This means that I have to scroll all the way to the bottom of the list to see the embargoes that are expiring soonest.  I'd like to see the embargoes expiring earliest at the top of the list (or be able to toggle the sort order).

**ACCEPTANCE**
- [x] The items with the embargoes expiring soonest can be sorted so they are at the top of the list
~- [ ] The items with the embargoes expiring furthest out appear at the bottom of the list~

**Comment by mark-dce** [comment]
This is required in partial fulfillment of https://github.com/emory-libraries/etd-issues/issues/30

**Comment by no-reply** [comment]
#1138 makes the table sortable.

@mark-dce when we originally discussed this, we talked about that being enough to meet the requirements. We can change the default sort order for the table in a follow-up, but I wanted to confirm that the requirements marked here are critical, since this seems to require some minor customization of javascript otherwise provided by Hyrax.

**Comment by bess** [comment]
Remember when we talked about wanting a code word to say when we were engaging in scope creep? Did we ever settle on one? Can we call this good enough for now and add this as a nice-to-have feature later if we have scope left in the project?

**Comment by mark-dce** [comment]
It would be super helpful to have earliest expiring embargoes first.  In general use, this is what every user is going to want to do, so we can either let them scroll to the bottom of the list, hope they discover how to use the sort button every time they access the page, or set ascending sort order programmatically.  

@bess you're sort of right, except Im asking because this is already something that's an annoyance for me in acceptance testing, so I'm anticipating it would be super helpful to Fran and Anna.  I'm willing to spend two hours of programming time on this - it's of high value to me as the Product Owner.  I would cut the sort request if it's over 8 hours of programming time.

**Comment by no-reply** [comment]
@mhbussey the existing PR avoids the need to scroll, since it adds sortable columns to the table.

I'm hoping that reducing the pain to one click is good enough for now. does that seem wrong?

**Comment by mark-dce** [comment]
Ok, I'm willing to take a look as-is with the "you must click the sort order" solution.  Let's get this deployed on qa-upgrade-etd (if you can do that go ahead; otherwise, I can get a clean codebase on my system later today and deploy)

I am concerned and frustrated if we're using a toolset that doesn't let us easily request ascending or descending sort order for data we display - (i.e. isn't there some way to insert a sort assertion somewhere like here: https://github.com/samvera/hyrax/blob/master/app/views/hyrax/embargoes/_list_active_embargoes.html.erb#L8)

**Comment by mark-dce** [comment]
Doesn't this let us set the initial sort order without resorting to javascript?
https://github.com/samvera/hyrax/blob/2.1-stable/app/search_builders/hyrax/embargo_search_builder.rb#L11

**Comment by no-reply** [comment]
> I am concerned and frustrated if we're using a toolset that doesn't let us easily request ascending or descending sort order for data we display.

DataTables provides a way to do this. Hyrax provides an integration mechanism (`.datatables` CSS class) that seems desirable to use, but doesn't have a way to pass through sort order. The default is to sort ascending on the first column. It's absolutely possible to do, just not as clean as I would like. If we want to polish this table, I'd rather be doing it in Hyrax than hacking in a solution here.

This seems to be end-arounding the question I'm really asking, though, which is: should we be spending the time on this to have this debate?

**Comment by mark-dce** [comment]
So, my initial request was to sort the table ascending.  I had understood data tables would be the fastest route to do that.  I feel like we've now substituted adding a data table so the user "could" sort, but haven't met the actual request that I initially made in the ticket - which was to alter the default sort order.

**Comment by mark-dce** [comment]
@no-reply I've deployed the code and get clickable data-table headers, but they don't seem to impact the content displayed in the table.

**STEPS TO REPRODUCE**
1. Login as a superuser (tezproxy) to https://qa-upgrade-etd.emory.edu
2. Visit the embargo dashboard https://qa-upgrade-etd.emory.edu/embargoes?locale=en
3. Click on any data-table header

**EXPECTED BEHAVIOR**
The table is displayed sorted by the selected column in the selected order

**ACTUAL BEHAVIOR**
The datable headers change when I click on them, but nothing else in the table changes

**Comment by mark-dce** [comment]
:( Ignore that - I'm clicking on the wrong chooser.  So there's some layout we might want to fix, but the sort is working.

**Comment by mark-dce** [comment]
Let's look at this together with live data on  https://qa-upgrade-etd.emory.edu/embargoes?locale=en.  

* The date sort looks good, but I misunderstood which control was attached to the date
* The title sort is giving surprising results in ascending order - which I suspect means we're allowing non-printing characters at the front of titles

I'd like to talk about whether pushing some fixes back into Hyrax would allow us to fix the layout issues and specify the default column to sort

**Comment by mark-dce** [comment]
So after our discussion, let's call this good and I'll add a separate ticket for the layout and the file listing issues.
