### ISSUE TITLE
Configure nagios on new emory servers

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1075]
**ISSUE**
In order to put the new single host servers into production, we need them to be actively monitored, so we can respond in a timely way to any outages and proactively manage capacity.

**ACCEPTANCE**
- [x] nagios configuration for qa-upgrade-etd is complete 
- [x] nagios configuration for staging-upgrade-etd
- [x] nagions configuration for upgrade-etd is complete
- [x] all three servers are included in the emory host group in nagios dashboards

**Comment by bess** [comment]
![nagios_hostgroups.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5515e9ab52d65b2000638516/125516c66e82c728ace21e0d46e6959d2a8d909687e6ac57a34fff813955653f6b14b1247a80e03cfd183954570b1da4475f0a43aaadda7fa1b63c71db080ceb85650966da2f53fde6d640e258f075c95d8fa4bd8246c1ed3f2ce18c86473e1d001889ed10.png)
