### ISSUE TITLE
Add legacy vocabulary terms

### ISSUE THREAD

**Issue by no-reply** [curationexperts/laevigata#1106]
- [ ] All `subfield` values from the legacy/migration data are included in the controlled vocabulary as inactive.
 - [ ] Items with legacy `subfield` terms can be edited and saved while retaining the legacy value.
- [ ] All `department` values from the legacy/migration data are included in the controlled vocabulary as inactive.
 - [ ] Items with legacy `department` terms can be edited and saved while retaining the legacy value.
- [ ] Add any other fields identified during the migration

**Comment by bess** [comment]
This is no longer a requirement because of the way we'll be updating things in the new ui form. It would become a requirement if we wanted to edit migrated ETDs in the legacy form.

**Comment by mark-dce** [comment]
Closing since we're deprecating the legacy form (and should be able to adopt the same strategy used in the new UI if required.)
