### ISSUE TITLE
Legacy inactive vocabulary additions report

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1109]
- [ ] Produce a report of all vocabulary items that will need to be added to support migrated ETDs
  - [ ] Schools (hopefully no surprises here...)
  - [ ] Departments
  - [ ] Subfields
  - [ ] Degree
  - [ ] Submission Type
  - [ ] Research Fields
  - [ ] Partnering Agencies
  - [ ] Graduation Date
  - [ ] Language

**Comment by bess** [comment]
We don't know why we need this report given our latest plan for editing migrated works.

**Comment by mark-dce** [comment]
Closing given that we've adopted a new UI and new strategy for handling edits to legacy ETDs
