### ISSUE TITLE
Add large file support

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#111]
**STORY**
As Carla, I want students to easily be able to load up large files from cloud services like DropBox, so that I don't have to set up special complicated processes to support students with large PDFs and supplemental files.

**DETAILS**
This story can probably be accomplished by integrating the Browse Everything gem.  This might already be done.  For details see https://github.com/projecthydra/sufia/wiki/Sufia-Management-Guide#integration-with-dropbox-box-etc and https://github.com/projecthydra/browse-everything

**ACCEPTANCE**
- [x] Determine whether Browse Everything is implemented already.
- [x] An authenticated student can upload a file from Box
- [x] An authenticated student can upload a file from Google Drive
- [x] We've documented the list of services that are supported.
- [x] We've received the default storage max allowed to students for their Box accounts from Emory and added it to our documentation.

**Comment by shanitajohn** [comment]
Upload limit is 2.5GB per file, will need messaging in the application to let student's know if the file is too large, etc. Above this size requires Superadmin intervention.

**Comment by rotated8** [comment]
Upload limit config was moved in this PR for Hyrax 2.x : https://github.com/projecthydra-labs/hyrax/pull/933

**Comment by jenlindner** [comment]
There are a few aspects to uploading large files, and I'm going to start with this one: “let the user know before they start upload if their file is too big (because of poor user experience) to use the the built-in uploader”.

**Comment by acozine** [comment]
The browse-everything gem is integrated in laevigata. On the stresstest server, we are using it to connect to Box. Unfortunately DropBox changed its API and that connection is not working - see https://github.com/projecthydra/browse-everything/issues/159 and https://github.com/psu-stewardship/scholarsphere/issues/862. Our other options for browse-everything are:
- google drive
- s3
- sky drive

**Comment by mark-dce** [comment]
I was mostly just looking to be able to demonstrate more than one service to make sure there weren't any edge-cases we didn't catch.  Looks like it worked ;)  I've changed the acceptance criteria to *Box* and *Google Drive*.  It looks like Emory is more used to using *Box*, so that's probably a better choice anyway.

**Comment by acozine** [comment]
Currently the stresstest box hits a fedora bug (https://jira.duraspace.org/browse/FCREPO-2311) when uploading a 1.7GB file.

**Comment by jenlindner** [comment]
https://docs.google.com/document/d/1wLFXH3XChgVoQGWH3L1I5XJFJ3Jk9orLIM-Ua-pa__A/edit
