### ISSUE TITLE
404 vs. Page does not exist

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1111]
https://etd.library.emory.edu/embargoes - gives me a "The page you were looking for doesn't exist." error

https://etd.library.emory.edu/embargos gives me an unsettled 404 error

Why?   Shouldn't these both give a the same error page?

**Comment by no-reply** [comment]
don't these errors both mean the same thing? I'm not sure we should consider this a priority, especially since this is running an old version of the software.

**Comment by mark-dce** [comment]
Agreed - but logging a ticket about an issue isn't the same thing a prioritizing it - that's why I just logged this but didn't prioritize it by putting it in `backlog` or `next`. 

It's concerning to me that we appear to have two different mechanisms in play to respond to page not found errors.  Mostly I was logged this so we would take a look and see if we see the behavior in 2.x at some future point.

**Comment by mark-dce** [comment]
As of 3/19/2019, the current release of Hyrax has fixed the "We're Sorry But something went wrong"
