### ISSUE TITLE
Provide Upload Error if File is too large

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#112]
**STORY**
As Carla, a repository service manager, I want the system to notify students early if they try to upload files that are too large for reliable browser upload, so that they don't get frustrated uploading files that are too large.

**ACCEPTANCE**
- [x] When an end-user chooses a local file to upload, it's size is checked against the configured upload limit *BEFORE* the application tries to upload it.
- [x] If the file is too large, the user is notified about alternative methods to submit large files (see #111)
- [x] The file size limit is easily configurable 
- [x] The limit configuration parameter is clearly documented

**Comment by shanitajohn** [comment]
Upload limit is 2.5GB per file, will need messaging in the application to let student's know if the file is too large, etc. Above this size requires Superadmin intervention.
