### ISSUE TITLE
Make a workflow diagram

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#113]
Create a workflow diagram as described on this page: https://github.com/projecthydra/sufia/wiki/Mediated-Deposit-Workflow

**Acceptance Criteria**

- [ ] All steps required for deposit and approval of an ETD
- [ ] All roles required for each step
- [ ] Which roles can see the item throughout the workflow?
- [ ] When a state change occurs, what other actions could/should be taken?

**Comment by mark-dce** [comment]
@bess - does this ticket mean to translate this diagram into some other format?
https://drive.google.com/file/d/0B8imcSJ3yFamSmVMeFhvQmhCaXc/view?usp=sharing

**Comment by bess** [comment]
Yes, I'd like to translate that into the kind of diagram Jeremy describes in the "mediated workflow" page I linked to. I think it will help us visualize all the needed steps in our workflow, how transitions happen, who needs access at various points, etc. I think this also ties into the conversation we had about developing a common visual language for talking about workflow.

**Comment by bess** [comment]
See https://docs.google.com/drawings/d/1oCNgx4XiDzZdsomnTkP4LVkVBtr0rHJ4OJhZUXlmJo0/edit
