### ISSUE TITLE
Use an admin service to get admin_set_id

### ISSUE THREAD

**Issue by jenlindner** [curationexperts/laevigata#1146]
**ACCEPTANCE CRITERIA**
- [ ] A service class exists, which will return an admin set id for a given school and department

**Comment by mark-dce** [comment]
This go taken care of in https://github.com/curationexperts/laevigata/pull/1130 - see https://github.com/curationexperts/laevigata/blob/f2bc55b02faa2e44979d18656605eeca3f183f0f/app/services/admin_set_chooser.rb
