### ISSUE TITLE
Restore new production server to staging

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1147]
**STORY**
As a repository manager, I would like to confirm that our restore documentation matches our final production configurations, so that I can sleep easier at night.

**ACCEPTANCE**
Given a DCE team member who is not Bess...
- [x] I have the access I need to restore last night's production backup to the staging server
- [x] I know how to determine the appropriate backup for a specific date (e.g. I want to restore last Thursday's content to staging for forensic purposes)
- [x] I can perform the restore by following the document steps without having to guess about anything or fill in any undocumented gaps*
- [x] We have good confidence as a team that we can use the same process to restore to production - i.e. this acceptance criteria comes last and involves a quick team discussion

* If the person testing the documentation finds a gap in the documentation, we need to update the documentation as needed and a new team member should complete the testing from start to finish.

**Comment by bess** [comment]
Documentation here: https://github.com/curationexperts/playbook/pull/59

**Comment by no-reply** [comment]
I am Tom. I can do everything listed here (except having a team discussion, which requires input from others).

I'm putting this in progress and assigning to me to add to the agenda for next team meeting.

**Comment by mark-dce** [comment]
Signing off on final acceptance criteria based on conversation with Tom
