### ISSUE TITLE
Write up ETD production upgrade summary

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1148]
Bess wrote "Everything should pretty much look the same, but there have been many upgrades and improvements behind the scenes."

We should produce release notes that list the key updates:
* Single host build
* Fedora 4.7.5
* etc.

**Comment by bess** [comment]
* Single host build simplifies management and reduces AWS costs
* Upgrade to Fedora 4.7.5 for stability and performance
* Fedora backed by Postgres for improved performance and data integrity
* Upgrade to Passenger 5.3.2 for security fixes
* Systems built with latest ansible-samvera playbooks, making them match other DCE systems
* Systems built fully with ansible, making the process much more predictable and repeatable
* Production environment variables managed in version control and deployed to new systems via ansible
* Solr, Fedora, and Sidekiq all restart automatically when nagios detects they are down for any reason
* All logs are shipped to splunk for ease of auditing and troubleshooting
* Nagios plugins updated for improved performance and security

**Comment by bess** [comment]
@mark-dce Here's everything I could think of that we changed with the latest deploy

Where would you like this? Have I missed anything?

**Comment by bess** [comment]
I also added these notes at https://github.com/curationexperts/laevigata/releases/tag/v1.6.6

**Comment by mark-dce** [comment]
The release tag is awesome.  I like that pattern as a place for us to put this kind of info.  It's an easy place for me to look back to when writing up monthly notes or ad-hoc email.
