### ISSUE TITLE
Plan to decommission obsolete Emory servers

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1150]
**ISSUE**
Emory is being charged for a lot of servers right now, we should try to reduce that cost by shutting down servers we don't intent to use in the future.

**ACCEPTANCE**
- [x] Decommission multi-server qa & staging
- [x] Decommission multi-server prod
- [x] Suspend any other boxes we don't need live - i.e. do we need all six single box servers running right now?

**Comment by bess** [comment]
We are down to 3 in our production stack (qa, stage, and prod) and 3 in our upgrade stack (qa-upgrade, stage-upgrade, and prod-upgrade)
