### ISSUE TITLE
Confirm July 3rd Embargo Expiration

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1157]
**ISSUE** 
The first embargoes in the system that should automatically expire (via our cron job) should be released on 2018-07-03

**ACCEPTANCE**
On or after July 4th, 
- [x] confirm that the 6 scheduled embargoes have been released

**Comment by bess** [comment]
Yes! These embargoes were lifted. See https://etd.library.emory.edu/concern/etds/hx11xf263. We also have a record of it in the logs and in splunk.

**Comment by mark-dce** [comment]
👍

**Comment by fpici** [comment]
@bess The Embargo summary for records expiring July 3 came through and is populated with the 6 student records. Also confirming that all six access restrictions have been removed and the records are now Open Access :-):+1:Shazaam!
