### ISSUE TITLE
ProQuest

### ISSUE THREAD

**Issue by bnash108** [curationexperts/laevigata#116]
Answers from ProQuest to our questions

**Comment by bnash108** [comment]
Question 1: 
Is there a test account/FTP site on the ProQuest side they can use for development? We would like to avoid sending test dissertations to your production system if possible.
Answer 1:
We currently don’t have an account set up for this purpose, but I can absolutely make it happen. When I have the new account set up, I will send you the log in credentials. That will be later this week. *(Note from Bethany: I do not have this yet. Will update the ticket once it is available)

Question 2:
Are there any technical specifications from your end that our developers can code against?
Answer 2:
I just spoke with you on the phone about this particular question. As discussed, I have attached the DTD that you all have been using for the last several years, as well as supporting documentation (degree codes, language codes, etc.) I’ve also attached a sample Emory University submission, so that you can see the DTD’s output.

Question 3:  
Is there a way we can get an automated notification back from the ProQuest system that our FTP was successful?
Answer 3:
We have no automated systems in place for this. As we discussed recently though, I will let you and Fran know whenever Emory University FTPs files to us (assuming the automated e-mail messages that Emory University currently sends to ProQuest will continue to be sent moving forward).

Question 4:
Given that our Graduate School would like to change its relationship with ProQuest (agreement between the school and ProQuest, not the student and ProQuest) as we discussed in our meeting with Ulf Nilsson last year, what changes should we anticipate in what our ETD software needs to send to ProQuest? If I remember correctly, there is not currently a way for students to request copyright registration in an automated fashion. We were planning to remove that functionality from the new software. Is there anything else we should be aware of?
Answer 4:
In the paper agreement form days, authors and/or universities would normally send any permission letters to ProQuest attached to the associated author’s agreement form. Permission letters moving forward will need to be scanned, put into a folder, and zipped with the PDF manuscript, XML, and any supplemental files there may be for any given author. The name of the folder that the permission letters are put in should be end in “_permission”.

**Comment by bnash108** [comment]
[upload_fogg_ross.zip](https://github.com/curationexperts/laevigata/files/961767/upload_fogg_ross.zip)


[ProQuest Documentation.zip](https://github.com/curationexperts/laevigata/files/961770/ProQuest.Documentation.zip)

**Comment by fpici** [comment]
Hello everyone. Buddy from proquest says the Test Environment is now up and running. Here are the login credentials:  

ftp.proquest.com
User Name: EmTest
Password: 06TesTem65
 
Any questions or issues, let me know :-)

**Comment by shanitajohn** [comment]
@bnash108 Can you talk @shanitajohn and @bess through the answer to Question 4? I want to confirm we understand the following and that we have accommodated everything in the student submission workflow. 

- [ ] What is a permission letter? 
- [ ] Do all students submitting to Proquest need to scan / submit one via the ETDs system? 
- [ ] At what point in the submission process does the student upload the permission letter?

**Comment by shanitajohn** [comment]
Related to #163 - Display ProQuest submission information within the application

**Comment by bnash108** [comment]
@shanitajohn re: ProQuest permissions letters - permission letters will be something our Graduate School handles separately with ProQuest.

**Comment by shanitajohn** [comment]
@bess @bnash108 Great, thank you! That covers off on all our questions.
