### ISSUE TITLE
Profile link takes me to homepage in 2.x

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1163]
**STEPS TO REPRODUCE**
1. Login as any user
2. Navigate to the dashboard (2.x has a single dashboard)
3. Click on the "Your Activity Dropdown"
4. Click on "Profile"

**ACTUAL RESULTS**
I'm taken back to the homepage

**EXPECTED RESULTS**
Nurax gives me a page that looks like this when I click the same link
<img width="484" alt="1163 - expected user profile" src="https://user-images.githubusercontent.com/3064318/42004304-e1ac991c-7a34-11e8-9828-55eecb097b2e.png">

**ACCEPTANCE**
- [ ] Remove the "Profile" link
OR
- [ ] Give me some user type statistics like nurax does

**Comment by mark-dce** [comment]
Update - this may have to do with overlapping CSS elements.  If I hover over the top of the word "Profile" I don't get a highlight and inspect element seems to be saying I'm on the masthead.  If I hover lower or just underneath "Profile", I get a nightlight and the expected behavior. 

Let's hold this one until #1171 (header CSS) is complete and re-check the behavior.

**Comment by bess** [comment]
This seems to have been fixed. I can't re-create the error.

**Comment by mark-dce** [comment]
This turns out to be Safari specific and documented better in #1276
