### ISSUE TITLE
Collection types missing translations

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1167]
**STEPS TO REPRODUCE**
1. Login as an administrator
1. Navigate to the dashboard
1. Click on "Settings"
1. Click on "Collection Types"
1. View the "Name" field under "Current Collection Types"

Example: https://qa-upgrade-etd.emory.edu/admin/collection_types?locale=en

**Comment by val99erie** [comment]
A screenshot of the problem:

<img width="810" alt="screen shot 2018-06-28 at 3 50 09 pm" src="https://user-images.githubusercontent.com/298865/42060033-11c29140-7aeb-11e8-80d6-201317b707c6.png">

**Comment by no-reply** [comment]
This seems like it should be coming for free from: https://github.com/samvera/hyrax/blob/1677d72041ecca2e4e88917236dac82f43776b2f/config/locales/hyrax.en.yml#L499

**Comment by no-reply** [comment]
This seems like it should be coming for free from: https://github.com/samvera/hyrax/blob/1677d72041ecca2e4e88917236dac82f43776b2f/config/locales/hyrax.en.yml#L499

**Comment by val99erie** [comment]
@no-reply Yeah, I think you are right.

I haven't been able to reproduce the problem on master yet, and I can't easily confirm whether it was broken in a previous version because the version that is currently deployed on that environment has a SHA from before the force-push on master.  I'm not sure what SHA that corresponds to on the new master.

I'll dig around a little more, but I suspect that I'm not able to reproduce this in my dev environment.

**Comment by val99erie** [comment]
On that environment, here's the last entry from the revisions.log:
`Branch master (at 098e707d7a88507f4fa4dfa8b1ff04d34643588f) deployed as release 20180627180754 by mark`

**Comment by mark-dce** [comment]
Just deployed master and I'm still seeing this text:
```
translation missing: en.hyrax.collection_type.default_title
translation missing: en.hyrax.collection_type.admin_set_title
```

```
04:27 deploy:log_revision
      01 echo "Branch master (at 245e84eade10bb5edc1865107ea16b7fcb2e3652) deployed as release 20180628213126 by mark" >> /opt/laevigata/revis…
    ✔ 01 deploy@qa-upgrade-etd.emory.edu 0.199s
```

**Comment by mark-dce** [comment]
We have a local copy of https://github.com/curationexperts/laevigata/blob/master/config/locales/hyrax.en.yml wouldn't we need to update that with the necessary translations (or does i8n merge application translations with engine translations)?

**Comment by mark-dce** [comment]
It looks like the hyrax translation file has a translation for `en.hyrax.collection.collection_type.default_title` which is different that what's being asked for in the view: `en.hyrax.collection_type.default_title` - i.e. there's an extra `.collection` level in the translation file in the engine compared to what the running application is looking for

**Comment by val99erie** [comment]
I don't think this is a bug (at least not in the current code).  This looks like a data problem.

I created 2 new CollectionType records on that environment, and they display correctly.  See screenshot below.

If you look at the titles for the existing CollectionType records, the title is actually set to "translation missing: en.hyrax.collection_type.default_title".  So I think we just have some bad data in that environment.

```ruby
irb(main):011:0* I18n.t('hyrax.collection_type.admin_set_title')
=> "Admin Set"

irb(main):012:0> I18n.t('hyrax.collection_type.default_title')
=> "User Collection"

irb(main):013:0> Hyrax::CollectionType.all.map(&:title)
=> ["translation missing: en.hyrax.collection_type.default_title", "translation missing: en.hyrax.collection_type.admin_set_title", "ABC", "Another type"]
```

<img width="670" alt="collection_type" src="https://user-images.githubusercontent.com/298865/42098096-83a09b38-7b7f-11e8-944a-7ddf19ab41fd.png">

I'll assign the story back to @mark-dce for review.

**Comment by mark-dce** [comment]
Ok, on my development environment, 
1. When I load a clean environment, I have no collections listed at `/collection_types`
1. When I run `bin/rails hyrax:default_collection_types:create`, default collection types **user_collection** and **admin_set** get created
1. When if visit `/collection_types` two new collections get created with the titles "translation missing: en.hyrax.collection_type.default_title" and "translation missing: en.hyrax.collection_type.admin_set"

This seems like a bug in the `hyrax:default_collection_types:create` task.  How do we want to address this?  (I'd prefer not to have to go into each server environment and manually edit the titles, but we could automate a script to do that, but that doesn't stop this from happening to every other Hyrax user who runs the script)

**Comment by mark-dce** [comment]
So when I run the `hyrax:default_collection_types:create` on a clean environment without and collections and add a breakpoint in the setup code, I see this:
```
$ bin/rails hyrax:default_collection_types:create

[15, 24] in /Users/mark/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/hyrax-2.1.0/app/models/hyrax/collection_type.rb
   15:     ADMIN_SET_MACHINE_ID = 'admin_set'.freeze
   16:     ADMIN_SET_DEFAULT_TITLE = I18n.t('hyrax.collection_type.admin_set_title').freeze
   17: 
   18:     byebug
   19: 
=> 20:     def title=(value)
   21:       super
   22:       assign_machine_id
   23:     end
   24: 
(byebug) ADMIN_SET_DEFAULT_TITLE
"translation missing: en.hyrax.collection_type.admin_set_title"
(byebug) 
```

So it looks like the environment that task is loading does not include the localization files.

**Comment by mark-dce** [comment]
It definitely looks like a environment load issue in the rake task.  I wrote up a ticket for Hyrax: https://github.com/samvera/hyrax/issues/3136
