### ISSUE TITLE
All Users should have display names

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1169]
**ISSUE**
Users who are created via workflow setup appear to only get PPID assigned.  Users who login via Shibboleth appear to all have display names assigned.  

**ACCEPTANCE**
Either
- [x] Update missing usernames at login from shibboleth
OR
- [ ] Add display names to the user setup for workflows

<img width="1122" alt="1169 - user display names" src="https://user-images.githubusercontent.com/3064318/42013066-13567ff6-7a61-11e8-8f55-f76328a56005.png">

**Comment by bess** [comment]
We already do update the user with a display name when they log in via shibboleth. 

After removing the 'bess' and 'alicia' users, which were left over from early days of system setup, we are left with four users who don't have display names. These are uids that we have been asked to enable as approvers, but apparently they have never logged into the system via shibboleth. Two of them have more recent dates under "last access" but that's misleading... that's the date they were added to the workflow config, i.e., the last time their database record was updated.
