### ISSUE TITLE
List Workflow Roles users by display name

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1173]
**ISSUE**
We have display names for most users (and should have them for all users - see #1169).  As an administrator I would like to be able to see the full names of users in the workflow roles display.

**ACCEPTANCE**
- [x] Add a column to display the full user name in the Workflow Roles view: eg https://qa-upgrade-etd.emory.edu/admin/workflow_roles
- [x] Sort the view by the display name
- [x] [BONUS] Add a data-tables control to provide pagination and make the page searchable by role - ask @no-reply about this because he just did the same thing for the embargoes page

**Comment by val99erie** [comment]
@no-reply Is this the kind of thing we might want to do directly in hyrax?  Or do you think it's better to keep it local to laevigata?

**Comment by bess** [comment]
PR to Hyrax at https://github.com/samvera/hyrax/pull/3140
