### ISSUE TITLE
Users list missing/broken from dashboard

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1175]
**ISSUE**
As a SuperAdmin In 1.x, I could see a full list of users at `/admin/users` and there was a link to that page called "Manage Users".  That link is gone and when I try to visit that path I get a honey badger error.

1. In Hyrax 1.x / Lavigata 1.x - there't a page like the one at https://staging-etd.library.emory.edu/admin/users?locale=en
1. In Hyrax 2.x the link to `/admin/users` still works, but there's no longer a link on the dashboard (I don't know if this is intentional or a bug in Hyrax) - see https://tenejo.curationexperts.com/admin/users (let me know if you need admin rights added to any account)
1. In Lavigata 2.x, the link is missing ('cause it's missing in Hyrax) and visiting the path gives me a honey badger error (instead of just a 404 like I'd expect) - i.e. visiting https://qa-upgrade-etd.emory.edu/admin/users triggers https://app.honeybadger.io/projects/56103/faults/38417434#notice-summary

**ACCEPTANCE**
*PREFERRED SOLUTION*
- [x] The `/admin/users` page is fixed
- [x] The "Manage Users" link is restored to the dashboard 

*LESS ATTRACTIVE ALTERNATIVE*
- [ ] The `/admin/users` route is removed and I get a 404 as I would for any other invalid path

**Comment by mark-dce** [comment]
@no-reply I don't necessarily think you personally need to take this ticket, but I would love for you to review the ticket and give any feedback about which parts should be fixed in Laevigata, which parts should be addressed in Hyrax, and how much of the change dropping "Manage Users" in Hyrax was intentional.

**Comment by bess** [comment]
Connected to https://github.com/curationexperts/laevigata/issues/1237
