### ISSUE TITLE
Give copyright questions meaningful attribute names

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1176]
**ISSUE**
We currently use vague attribute names for the copyright questions as follows:
```
copyright_question_one: false
copyright_question_two: false
copyright_question_three: false
```
see https://github.com/curationexperts/laevigata/blob/master/app/models/etd.rb#L132-L143

This forces a tight coupling between our forms, the code, and the data, because I need to see all three to make sense of what 'copyright_question_three=true' actuallys mean.  (In fedora, I can look and see that that's actually 'skos/core#note_patents: true' which suggest this is about the patent's question.)

I've had to deal with this a few times already and each time I have to do a bunch of dereferencing to understand which values are answering which questions.

Since we're not changing the underlying predicates, I'm assuming this is just a refactor of the attribute naming within the application.  If there's something that makes the scope larger or would require a data migration, we should discuss it before completing this ticket.

**ACCEPTANCE**
- [ ] attribute names are refactored to be more semantic in relation to the question the correspond to
    - [ ] copyright_question_one --> requires_permissions (skos/core#note_permissions)
    - [ ] copyright_question_two --> other_copyrights (skos/core#note_copyrights)
    - [ ] copyright_question_three --> patents (skos/core#note_patents)

*NOTE* I'm not committed to these specific attribute names - if folks have better ideas for names or we want to just use the SKOS predicate names I'm fine with that.  I just need the names not to be _one, _two, _three ;)

**Comment by val99erie** [comment]
Is it necessary to change names in the code?  Or is it sufficient to give the properties meaningful labels in the UI?

**Comment by rotated8** [comment]
@devanshu-m is working on the labels on the review page at the moment here: emory-libraries/etd-issues#42. I'd be happy to add changing the attribute names to that work.

**Comment by no-reply** [comment]
It seems like a good idea to deprecate the old (code) property names and update with something more meaningful.

**Comment by mark-dce** [comment]
> Although the struggle for good names is painful, it is worth the effort if you wish your work to survive to be read. Code clarity is built upon names.
https://www.sandimetz.com/99bottles/sample/

I've been asked to deal with questions about copyright_question_one, _two, and _three a few times now and it's really hard to tell how they map to the UI and the meaning of true vs. false in each case.  It would be a whole lot more fun dealing with the code and questions related to it if we had better names here.

**Comment by mark-dce** [comment]
e.g. `etd.other_copyrights = true` clearly suggests that the work in question has other copyrights involved.   

The current naming is completely opaque each time I've come across it.  `etd.copyright_question_one = true` is completely opaque to me each time I read some version of it.
