### ISSUE TITLE
Remove homepage index view when Hyrax is released

### ISSUE THREAD

**Issue by rotated8** [curationexperts/laevigata#118]
The fixes we added to that view will no longer be necessary once Hyrax is 1.0.0
Closable when:
- [ ] Application uses Hyrax 1.0.0 (instead of 1.0.0.rc1).
- [ ] app/views/hyrax/hompage/index.html.erb is removed.

**Comment by mark-dce** [comment]
Blocked until Hyrax 1.0.0 is released - see https://rubygems.org/gems/hyrax

**Comment by shanitajohn** [comment]
Superceded
