### ISSUE TITLE
Display the filled-out form content on the submission tab

### ISSUE THREAD

**Issue by little9** [curationexperts/laevigata#1190]
The form should display all the content that a user has filled out as a preview before submission.

**Comment by little9** [comment]
@jenlindner Is this ticket no longer valid? Do we just want the final tab in the form to notify the user that they successfully filled out the form, and then give them a link to the actual Etd submission form?

**Comment by jenlindner** [comment]
It's valid. There's a basic version of it working now, the tab displays the form data all in one place. We could close this and open a story for styling the tab and adding the agreement input to it.

**Comment by little9** [comment]
- [ ] Files
- [ ] Embargoes

**Comment by little9** [comment]
This still needs to display the files
