### ISSUE TITLE
Determine how an ETD is edited after it is submitted

### ISSUE THREAD

**Issue by little9** [curationexperts/laevigata#1192]
We need to make sure that an ETD is still editable via the Hyrax form after submission OR
maybe reuse the Vue form for editing.

**Comment by val99erie** [comment]
Some things to consider:
- [ ] Student needs to be able to edit the ETD during certain stages of the workflow.
- [ ] Approver or admin user needs to be able to edit the ETD during certain stages of the workflow.

**Comment by val99erie** [comment]
We need to decide if we can replace all the javascript for the old ETD edit form with the new Vue-based code.  We want to avoid supporting 2 separate UIs for the forms (editing `Etd` vs editing `InProgressEtd`), but we also want to make sure all the standard hyrax features work as they should, including workflow progression.

**Comment by val99erie** [comment]
The code is roughly done for successful edit.  Some fields aren't working yet, but you can edit the simple fields, such as title and creator.  I haven't worked on the error path yet.

**Comment by val99erie** [comment]
I will close this ticket.  The remainder of the work should be handled in these stories:
#1447 - ETD submission error case
#1300 - Address hard-coded fields
