### ISSUE TITLE
Implement uploading  primary file from Box on the front-end

### ISSUE THREAD

**Issue by little9** [curationexperts/laevigata#1198]
See if there is a library to enable uploading from Box.

**Comment by mark-dce** [comment]
I don't know if either of these are useful:
https://blog.box.com/blog/using-the-box-api-with-javascript/
https://developer.box.com/docs/sdks --> https://github.com/allenmichael/box-javascript-sdk

It doesn't look like file upload is too complicate - so if we want to contemplate a custom view component for box upload, I'd be willing to talk about whether we have time to complete that (it might be faster than other options.)
