### ISSUE TITLE
Migrate existing content to new visibility rules

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1207]
**ACCEPTANCE**
- [x] Visibility restrictions are fully reflected at the work level using the new visibility levels described in #1206
- [ ] ~Old-style TOC & Abstract restrictions settings are removed from objects in fedora~
- [ ] ~Old-style TOC & Abstract restriction code is removed from the application~

**Comment by bess** [comment]
Run the rake task and make sure it updates existing items as expected

**Comment by bess** [comment]
This needs to be done again during the release, because there have been new submissions since we did this in production.

**Comment by bess** [comment]
This has been tested and added to the release process.
