### ISSUE TITLE
Add view support for new-style visibility restrictions

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1208]
**ACCEPTANCE**
New style (#1206) visibility restrictions are supported in:
- [ ] search result views
- [ ] single item show views
- [ ] embargo listing views

**Comment by no-reply** [comment]
@bess, @mark-dce #1488 adds badges to all of these views.

Is there further view work we want to take on?

**Comment by mark-dce** [comment]
Once the new embargo levels were in place, a human member of our team needs to look at each of those pages and verify that they still behave in a predictable way without errors.  If the page errors or presents the user with information that is untrue or confusing, we need to address it - either as part of this ticket (if the issue is small) or by writing a new ticket (if the issue is larger and needs steps to reproduce, screenshots, etc.)

**Comment by bess** [comment]
@mark-dce Take al ook?
