### ISSUE TITLE
Add edit support for new-style visibility restrictions

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1209]
**ACCEPTANCE**
The following create and edit forms support new style #1206 visibility restrictions
- [x] Single embargo management pages (/embargoes/[:id])
- [ ] Bulk embargo management pages (/embargoes#expired)
- [x] Single file embargo management page (/concern/file-set...##permissions_display)

**Comment by no-reply** [comment]
>  Bulk embargo management pages (/embargoes#expired)

I'm thinking this criterion is misplaced, here. The expired embargoes tab does not allow editing embargos, apart from deactivating them.

**Comment by mark-dce** [comment]
Happy to move this to a new ticket - the point is to ensure that the "Expired Active Embargos" and "Deactivated Embargos" tab render the new embargo levels correctly, not that they can be edited directly.

<img width="1162" alt="1209 embargo text" src="https://user-images.githubusercontent.com/3064318/43680442-88d39bb2-9800-11e8-8751-cab5bd328f2b.png">
