### ISSUE TITLE
"ETD" capitalization

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1219]
**ISSUE**
In listings where I see the work type (which might only be in Embargoes), I see new works submitted with 2.x code listed as "Etd" whereas works submitted with 1.x code are listed as "ETD" (all caps)

**ACCEPTANCE**
- [x] New submissions show the type as "ETD" in any relevant display views

<img width="1161" alt="1219 - etd capitalization" src="https://user-images.githubusercontent.com/3064318/42117704-d57358f8-7bc3-11e8-8f24-ab25019e4a56.png">

**Comment by no-reply** [comment]
oh, that's wild. This mus be stored verbatim in the db!

**Comment by no-reply** [comment]
Note that #1230 doesn't fix this issue on existing migrated data in QA and staging envs until a reindex takes place.
