### ISSUE TITLE
Schools configuration view broken

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1243]
This was working earlier this week...

**STEPS TO REPRODUCE**
1. Login as an admin user
1. Navigate to the dashboard
1. Click on "Schools" in the left-hand task panel

**EXPECTED BEHAVIOR"
I should get a list fo the schools configured in the application with links to visit their individual configurations.

**ACTUAL BEHAVIOR**
"We're sorry, but something went wrong."   
Probably connected to https://app.honeybadger.io/projects/56103/faults/38472658

**ACCEPTANCE**
- [x] I see a list of links to each of the four schools

**Comment by bess** [comment]
Fixed in another ticket
