### ISSUE TITLE
Re-index prod after deploying updated copyright questions

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1258]
**ISSUE**
We've updated the predicates for copyright questions and will need to re-index when deploying the corresponding 2.x release.

**ACCEPTANCE**
- [x] Existing copyright question data display correctly on Review pages
- [x] Existing copyright question data displays correctly on Edit forms

**Comment by bess** [comment]
We need to re-index for several reasons. Let's do it as part of the upgrade / release process.

**Comment by bess** [comment]
This has been tested and added to the release process.
