### ISSUE TITLE
When derivatives fail to be created, make it clear which ETD failed

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#1259]
Sometimes derivatives fail to be created, especially for PDFs. When this happens, we want to be able to quickly identify which object failed. Unfortunately, the error report only includes the filename, not the object. Add the object id to the error that is raised.
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/56306/faults/38422076)

**Comment by no-reply** [comment]
SideKiq captures the id for the FileSet that failed. See the *Arguments* column at https://etd.library.emory.edu/sidekiq/morgue

```
{"_aj_globalid"=>"gid://laevigata/FileSet/6395w7149"}, "6395w7149/files/00699a8b-ed4a-4974-92ec-3b9f52afd985", "/tmp/RackMultipart20180425-59149-2ndlip.pdf"
```
