### ISSUE TITLE
Characterization is not being run on the DCE demo server

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#126]
**ISSUE**
File characterization results are not being reported for uploaded files.

**DETAILS**
https://emory.curationexperts.com/concern/file_sets/vh53wv72q
<img width="372" alt="show_file_set____hyrax" src="https://cloud.githubusercontent.com/assets/3064318/25503568/7e875f8a-2b60-11e7-839e-cba9c2f92d98.png">

**ACCEPTANCE**
- [x] I see file characterization for files I upload
- [x] There is an initializer check that ensures file characterization is correctly configured whenever I restart the server

**Comment by acozine** [comment]
FITS is installed, available to the deploy user, and in the production logs I see it running:
```
Ran characterization on jw827b648/files/b2716e27-898d-4d75-a020-d5c5fde926bc (application/pdf)
```
Maybe we still need the `fits_path` setting in `config/initializers/hyrax.rb`?

**Comment by mark-dce** [comment]
@acozine have you confirmed which version of FITS is installed and which version is required?

**Comment by bess** [comment]
Update: Characterization is running, but the solr index isn't being updated. If you updated it manually, on the console, the view is as expected. Jen and I are trying to figure out why solr isn't updating as expected.

**Comment by acozine** [comment]
Characterization on the sandbox requires:
- FITS version 1.0.5
- resque and resque-pool gems installed
- config changes in two files:
in `shared/config/initializers/hyrax.rb`:
```
  config.redis_namespace = "laevigata_#{Rails.env}"
  config.fits_path = "/usr/local/bin/fits"
  config.libreoffice_path = "/usr/bin/soffice"
  config.ffmpeg_path = '/usr/local/bin/ffmpeg'
  config.ingest_queue_name = :default
``` 
in `shared/config/environments/production.rb`:
```
  config.active_job.queue_adapter     = :resque
  config.active_job.queue_name_prefix = "laevigata_#{Rails.env}"
```
- both config files above added to capistrano linked_files (so future changes won't override these local settings) on the aws sandbox
- automated restart of resque-pool included in `cap aws deploy`
