### ISSUE TITLE
Cleanup after deleting testing object

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1260]
**ISSUE**
There appears to be residue from a testing attempt on prod.  We should make sure we have all traces of the test cleaned up so that further honeybadger errors aren't triggered.

NOTE: Look for the reference to "agile_samurai_estimation.pdf" in the backtrace.

[Emory laevigata PROD/production] ActiveJob::DeserializationError: Error while trying to deserialize arguments:

## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/56306/faults/38387689)

**Comment by mark-dce** [comment]
@no-reply can you look up a potential solution from the other project you mentioned.

We believed this particular object is fixed.

**Comment by no-reply** [comment]
My hack at an `ApplicationJob` for Hyrax 2 apps is here:

https://github.com/curationexperts/mahonia/blob/master/app/jobs/application_job.rb

It includes a catch and ignore for the known `Ldp::Gone` case represented here.
