### ISSUE TITLE
Bug in CSS layout in Safari

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1276]
**ISSUE**
In Safari, when it appears I'm clicking on a specific link or item, there's an invisible link target area that actually takes me to the homepage instead of the item I'm trying to hit.

See this screen capture: https://youtu.be/4JlWdtpsaPA

**ACCEPTANCE**
- [x] I don't get an invisible link to the homepage rendered on every page
- [x] When I have a pointer icon that looks like I'm hovering over a tab in the submission form, I can click on the link that takes me to that tab (and not the homepage)

**Comment by mark-dce** [comment]
If you hover over one of the "invisible" target areas and click inspect element, you get
```
<a id="logo" class="navbar-brand" style="color: #fff;" href="/?locale=en" data-no-turbolink="true">
```

**Comment by mark-dce** [comment]
Probably need to back port this to 1.6-stable as well

**Comment by little9** [comment]
@mark-dce could you try this in Chrome? I've been trying to reproduce this and haven't been able to. It would help to know if this was only happening in Safari. If it happens for you in Chrome, then it might be caused by the screen resolution.

**Comment by mark-dce** [comment]
No, I'm not seeing it in Chrome.  It only appears to show up in Safari.

**Comment by mark-dce** [comment]
Also, the behavior doesn't seem to be dependent on window dimensions in Chrome or Safari, but it does disappear in Safari if I zoom out (text smaller) two levels.

**Comment by mark-dce** [comment]
Issue resolved.

Tested in Safari and Chrome against https://qa-upgrade-etd.emory.edu/ running
> © 2017 Emory University. Version js/fix-school-dept-embargo-switching updated 14 August 2018.
