### ISSUE TITLE
Email clean-up

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#1280]
After the Spring 2018 graduation data was processed we had two bounced emails.

- [x] Correct `emilyrsmith9@gmail.om` to `emilyrsmith9@gmail.com` and re-send the user's graduation notifications
- [x] Correct`mihassa@hotmail.com` to `morad_hassan@hotmail.com`and re-send the user's graduation notifications

**Comment by fpici** [comment]
@bess Good Morning Bess. I have not heard back from this graduate but I have confirmed with Laney that the proper email address is: morad_hassan@hotmail.com. I amended the ETD record to reflect this address. Hope this helps :-)

**Comment by bess** [comment]
Done, and I also wrote up the process so someone else could do this next time, if necessary: https://github.com/curationexperts/laevigata/wiki/Bad-email-address-after-graduation
