### ISSUE TITLE
Make sure any corrupt file upload errors are handled

### ISSUE THREAD

**Issue by jenlindner** [curationexperts/laevigata#1283]

**Comment by jenlindner** [comment]
See: https://waffle.io/curationexperts/laevigata/cards/5a207ac7a23b2a001b2a20dd

**Comment by mark-dce** [comment]
That link doesn't appear to point to a valid card for some reason - can you provide a direct GitHub link?

**Comment by bess** [comment]
@jenlindner Do you have an example of a corrupt file that's causing errors? I couldn't get corrupt files to throw any errors. If you have a sample for me then please attach it to this ticket. Otherwise, I think we should proceed with the assumption that this is future scope work captured by #1290

**Comment by RachelDCE** [comment]
Can't replicate this issue.
