### ISSUE TITLE
Ensure that all values that have been saved in IPE and ETD display the correct values when loaded

### ISSUE THREAD

**Issue by little9** [curationexperts/laevigata#1301]
The state should be reloaded in a way that displays the correct values, and when you click around in the tabs, the values should be maintained.

**Comment by little9** [comment]
- [ ] School
- [ ] Graduation Date
- [ ] Department 
- [ ] Degree
- [ ] Submission Type
- [ ] Chair 
- [ ] Member
- [ ] Language
- [ ] Abstract
- [ ] TOC
- [ ] Research Fields
- [ ] Keywords
- [ ] Copyright questions
- [ ] Primary Files --
- [ ] Supplemental Files --
- [ ] Embargoes

**Comment by bess** [comment]
Files are addressed in separate tickets.
