### ISSUE TITLE
Alternate File Attachement Tab Wireframe [for comment]

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1309]
# STORY
As a sleep deprived student, I'd like to see and edit all of my file submissions in a single place, so there are fewer buttons and tabs I have to choose between while uploading files.

### New Submission, no files attached
![6-alt 1 my files no files attached](https://user-images.githubusercontent.com/3064318/42663766-a25dc050-85fc-11e8-8bab-276a31bb05bb.png)

### Primary PDF only, no supplemental files
![6-alt 2 my files primary only](https://user-images.githubusercontent.com/3064318/42663777-b609538a-85fc-11e8-88f6-75e6b7490c4b.png)

### Primary and supplemental files
![6-alt 3 my files supplemental](https://user-images.githubusercontent.com/3064318/42663779-bfa0d0da-85fc-11e8-82bc-22d4efc8c17a.png)

**Comment by mark-dce** [comment]
@bess @jenlindner @little9 @val99erie @no-reply Please review the above wireframes and add any comments, questions, or a thumbs-up.  I'm happy to schedule time for a synchronous in-person review too.

**Comment by little9** [comment]
@mark-dce this looks fine to me. Since I'm working on the Box features now I'll just implement this as well. 

I assume that we don't want the user to be able to edit the file name in the form, so I'll just display that as text. Let me know if the user should be able to edit the filename. 

If anybody else has any feedback, let me know! Otherwise I'm going to start on this.

**Comment by val99erie** [comment]
We can't edit the file name in the old form, so let's not allow editing file name.  Since our deadline is so tight, I don't want to spend the time researching whether or not that would break file ingest job or other file processing jobs.

**Comment by mark-dce** [comment]
No filename editing should be allowed - that's why it's shown as a disabled box in all rows.  If it makes more sense to just show it as a display label instead of a text box, that's great with me.

**Comment by bess** [comment]
:+1: This looks fine to me.

**Comment by mark-dce** [comment]
superseded by #1315 - Implement updated file Upload UI
