### ISSUE TITLE
DCE Shibboleth request form question

### ISSUE THREAD

**Issue by tmiles2** [curationexperts/laevigata#132]
How are the servers protected from unauthorized access and from attack (physically and via network)?

**Comment by acozine** [comment]
How does this sound?

The servers are hosted in a secure data center maintained by Amazon Web Services, built in a private VPN,  protected by a double firewall (an EC2 Security Group plus internal iptables rules). They are monitored for spikes in traffic, unexpected ssh connections, and other signs of intrusion. The site runs only SSL connections (https://).

**Comment by rotated8** [comment]
Added "System packages are regularly updated for security patches."
