### ISSUE TITLE
Additional Information for Non-Emory Committee / Thesis Adviser

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#133]
If a student has a non-Emory faculty Committee Chair or Thesis Advisor, we provide a text field for them to type in the Adviser's name. Is there any other information that needs to be collected about a non-Emory Chair or Adviser other than their name? 

- Will follow-up with wireframes link, shortly.

**Comment by bnash108** [comment]
We allow non-Emory chair/adviser and also committee members. We collect same information in both cases: Last name, First name, Affiliation. Screenshot from current app attached.
![screen shot 2017-05-05 at 11 41 40 am](https://cloud.githubusercontent.com/assets/26879573/25753014/0d54be38-3188-11e7-8c4a-b999cfd1dca0.png)

**Comment by shanitajohn** [comment]
Thanks. This has been updated in the wireframes.
