### ISSUE TITLE
Fix collection translations

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1333]
## ISSUE
See https://upgrade-etd.emory.edu/dashboard/collections?utf8=✓&per_page=10&locale=en

**NOTE:** This is an artifact of the 2.1 upgrade process, we can either fix it there or make sure to fix it in production data (and copies)

### ACCEPTANCE
- [ ] Fix or hide the title column on that page

<img width="1131" alt="1333 collections translations" src="https://user-images.githubusercontent.com/3064318/42824381-61b8cf98-89a5-11e8-9385-783d6e1fb917.png">

**Comment by bess** [comment]
We have a rake task to fix this. We just need to run  `RAILS_ENV=production bundle exec rake laevigata:fix_collection_type_labels`. I've now done that for `upgrade-etd`, `qa-upgrade-etd`, and `staging-upgrade-etd`.
