### ISSUE TITLE
File submission from box breaks in old UI

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#1347]
I'm pretty sure this is only happening for supplemental files submitted from box, and that it's around applying their metadata. 

Linked to Fresh Desk ticket https://curationexperts.freshdesk.com/helpdesk/tickets/65

I thought I had a stack trace for this, but I don't. That stack trace was because I had mistakenly deployed the 2.x branch on qa-etd.

**Comment by bess** [comment]
In the 2.x branch, this bug is caused because in a controller, `params` used to be a sub-class of `Hash`, and now it is an `ActionController::Parameters` object. When you call `.to_h`methods on params now, it checks to see whether the parameters have been whitelisted.

We have custom code that merges two `selected_files` hashes, because the legacy form had two copies of browse everything, so if you submit a PDF and a supplemental file from browse everything, you have to merge those values. 

This fix is low-priority because we hope we will not be running this code in the future. However, if we need to go back and use the non-Vue form, we'll need to fix this before box submission will work.

**Comment by mark-dce** [comment]
@bess can we close this as addressed in the UI refactoring in v2.0.0?
