### ISSUE TITLE
Research Field numbers

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#135]
The Research fields are pulled in from ProQuest with a four digit numerical code before the name of the discipline. Is that number valuable to the student or can we suppress it?

**Comment by bnash108** [comment]
They will not be important to students going forward b/c they won't be filling out a separate, paper form for ProQuest.
(Historical note: In the past, we recommended students make sure they are matching ProQuest fields between ETDs and their paper form by looking at the code.)

**Comment by shanitajohn** [comment]
Sounds good. Creating a ticket to that says to suppress the 4-digit numbers and closing this issue.

**Comment by shanitajohn** [comment]
Related to #182 and #188
