### ISSUE TITLE
Ensure the reviewTabs function sets tab navigation properties appropriately

### ISSUE THREAD

**Issue by jenlindner** [curationexperts/laevigata#1372]

**Comment by bess** [comment]
- [ ] If you've filled out all your tabs, and you get to the review screen and save at that state, you should come back to that exact state (maintain the state of "ready to submit")
- [ ] Anytime you edit some tabs, leave and come back, the ones you have saved are still valid, and you are taken to the first tab that you have not yet completed.
- [ ] Any tabs that you've already saved are still valid and enabled

NOT A PRIORITY
