### ISSUE TITLE
Suppress "Partnering Agencies" for all schools except Rollins School of Public Health

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#140]
**STORY**
As a student attempting to submit my ETD, I only want to see questions and form fields that apply to me, so that I don't become distracted looking for information I'm not required to have. 

**ACCCEPTANCE CRITERIA**
- [ ] If I am a student in the Rollins School of Public Health, I should be able to see Partnering Agencies in the About My Program section of ETDs. 
- [ ] If I am a student in the Rollins School of Public Health, Partnering Agencies is included in my submission checklist. 
- [ ]  ~If I am not a student in the Rollins School of Public Health, I never see anything about Partnering Agencies in the submission process~ 
- [ ] ~If I am not a student in the Rollins School of Public Health, I don't see Partnering Agencies listed in my submission checklist.~

UPDATE: Last two were removed because the submission checklist isn't that granular anymore.

**Comment by shanitajohn** [comment]
Related to #241

**Comment by alexBLR** [comment]
@shanitajohn where can I find the submission checklist?
