### ISSUE TITLE
Better end-user error reporting for Box issues

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#1446]
- [ ] If the box upload fails for any reason, notify the user
- [ ] Check that the file that has been attached is the file in question, not "error.html"
- [ ] When an error is encountered with Box, write a log entry:
  - [ ] log entry of type ERROR
  - [ ] includes the string BOX UPLOAD ERROR
  - [ ] it includes the ETD id
  - [ ] it includes the filename that we were attempting to retrieve

**Comment by val99erie** [comment]
One option we talked about - if Box file is attached by background job(s), then if job failed (and failed all retries), then send email notification to depositor.

**Comment by mark-dce** [comment]
Let's time box this to 12 hours of time moving any existing box upload code from the old process to the new job.  If there are issues remaining at the end of the time box we'll discuss whether to extend or create a new ticket.

**Comment by RachelDCE** [comment]
Related to older format for Box upload.
