### ISSUE TITLE
Determine if Sir Trevor is a viable solution for Abstract and TOC fields

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#145]
Determine if Sir Trevor is a viable solution for Abstract and TOC fields:

http://madebymany.github.io/sir-trevor-js/

Related to Tickets #56 and #57 and #242

**Comment by mark-dce** [comment]
Initially sizing this as a 1 and time-bounding it to 4 hours for Zo to research and report back.

**Comment by bess** [comment]
@alexBLR Looked at Sir Trevor, but tinymce is already being used by Hyrax, so we're going to try that first.
