### ISSUE TITLE
Suppress 4-digit Research Field code

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#149]
As a student, since I no longer have to use the Proquest research field code on a paper form, I don't need to see it when I select a research field during the online submission process. 

- [x] When I select a research field from the Proquest list, I do not see the 4-digit number code associated with that research field.

**Comment by shanitajohn** [comment]
Related to #188 and #242

**Comment by rotated8** [comment]
Implemented in #277
