### ISSUE TITLE
Box isn't setup on the upgrade-etd server

### ISSUE THREAD

**Issue by little9** [curationexperts/laevigata#1495]
When a user clicks on the Box link on `uprade-etd` they get an error. 

If we want to to use this on a server, we'll need to have an app setup in a developer's 
Box account and then enter the proper URLs in the Box settings so that the callback URLs
are going to the server.

**Comment by bess** [comment]
Jamie and I checked the config for the server and it looks right. We think there is a redirect override in the submit button and he's going to take a look at that.
