### ISSUE TITLE
List what content can be embargoed

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#151]
**STORY**
As a student, I only have three options for what content can be embargoed, I would like to be presented with those options and nothing else so that I am not overwhelmed with imaginary options. 

**ACCEPTANCE CRITERIA**
- [x] I should be able to embargo: Files only
- [x] I should be able to embargo: Files and table of contents
- [x] I should be able to embargo: Files, table of contents, and abstract
- [x] I should not be able to embargo any other combination of content

**Comment by shanitajohn** [comment]
**WIREFRAME** 
https://emory.box.com/s/3sfzqsiv6imc1ccb3mxm2m6vphwyu378

**Comment by val99erie** [comment]
See #150
