### ISSUE TITLE
Blank MyFiles tab

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts/laevigata#1518]
I am seeing this after I added a PDF for the primary. Then tried to add a supplemental file and it didn’t get added. Then brought me to Embargo. Going back to My File tab shows mostly empty page.

![screen shot 2018-08-08 at 11 05 17 am](https://user-images.githubusercontent.com/23509160/43849797-e24449f0-9afb-11e8-9aad-e25e5699a813.png)

**Comment by bess** [comment]
Cannot re-create. I believe this has been fixed in current master.
