### ISSUE TITLE
Add Emory theming

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#152]
- [x] Find out if Emory has formal branding guidelines we need to follow
- [ ] Laevigata should use Emory colors and branding

**Comment by mark-dce** [comment]
There is a university style guide available here: http://communications.emory.edu/resources/identity/index.html

**Comment by eporter23** [comment]
See also the Library's web branding pattern library here: http://template.library.emory.edu/styleguide/patternlibrary/

**Comment by shanitajohn** [comment]
Example: https://emory.box.com/s/3mscw7m9syle0rfzybjzb3ntdnwnm0at

**Comment by shanitajohn** [comment]
Design clarification from Emily: https://docs.google.com/document/d/1yfCKt40T8R4y5xQvOj8nIPPIjdqKIjbmjPzmL5zM0sQ/edit#

**Comment by shanitajohn** [comment]
Thanks @eporter23!  I've just been placing screen shots from the process PDF for inspiration mock-ups. Can you share branding assets (lock-ups, typefaces, etc.)?  ... also I just realized Doge is your avatar... brilliant.

**Comment by eporter23** [comment]
@shanitajohn glad to share some Doge love... can you ping me on slack with more detail about what you may need in terms of assets?

**Comment by eporter23** [comment]
@shanitajohn @bnash108 talked to Kristian Serrano this morning and we put this together for minimal branding (see Option 5): https://docs.google.com/document/d/1yfCKt40T8R4y5xQvOj8nIPPIjdqKIjbmjPzmL5zM0sQ/edit#heading=h.8cwoocespqlk - Kristian will need to request the custom logo image.
