### ISSUE TITLE
Editing a work does not let me edit embargo length and type

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#1554]
- [x] When I edit a work I should be able to select a new embargo length
- [ ] When I edit a work I should be able to select a new embargo type (e.g., files only, files and toc, or all restricted)

**Comment by RachelDCE** [comment]
This was tested and fixed.

Tested on QA | © 2017 Emory University. Version rebased_hyrax_2.2 updated 16 August 2018.
