### ISSUE TITLE
Submission agreement text

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#157]
- [ ] Get language for submission agreement from Bethany
- [ ] Update submission agreement with Emory language

**Comment by bnash108** [comment]
Submission agreement text:

I hereby grant to Emory University and its agents the non-exclusive license to archive, make accessible, and display (subject to the conditions agreed upon in the separate written agreement I have submitted to Laney Graduate School) my thesis or dissertation in whole or in part in all forms of media, now or hereafter known, including the display of the thesis or dissertation on the world wide web. I retain all ownership rights to the copyright of the thesis or dissertation. I also retain the right to use in future works (such as articles or books) all or part of this thesis or dissertation. I certify that my electronic submission is the version of my thesis/dissertation that was approved by my committee.

**Comment by bess** [comment]
@bnash108 Can you confirm this text should specify "Laney Graduate School" for *everyone*?

**Comment by bnash108** [comment]
Ah, sorry about that. I should have called out that the school referenced in the text changes based on which school the student belongs to.

**Comment by bess** [comment]
Perfect! Thanks, @bnash108!

**Comment by shanitajohn** [comment]
Incorporate into Wireframe ticket

**Comment by bnash108** [comment]
@shanitajohn @bess Lisa would like to change the language for the submission agreement. New text below. Also, with this text change we will not need functionality to populate the school name. The text will be the same for all students.

I hereby grant to Emory University and its agents the non-exclusive license to archive, make accessible, and display, subject to any embargo restrictions I have specified above, my thesis or dissertation in whole or in part in all forms of media, now or hereafter known, including the display of the thesis or dissertation on the world wide web. I retain all ownership rights to the copyright of the thesis or dissertation. I also retain the right to use in future works (such as articles or books) all or part of this thesis or dissertation. I certify that my electronic submission is the version of my thesis/dissertation that was approved by my committee.

**Comment by shanitajohn** [comment]
Related to Ticket #146

**Comment by shanitajohn** [comment]
This copy has been added to the copy doc, approved and will be added to the application
