### ISSUE TITLE
Committee member affiliation not on review page

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#1579]
If a committee member has a non-emory affiliation I expect to see what that affiliation is, not just "non-emory"

**Comment by bess** [comment]
![commitee_affiliation.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5515e9ab52d65b2000638516/125516c66e82c728ace21e0d46eb9b972e8b97ac8ad6be45a254fc9d28522e7c2746ef696097ec22ba416f43554d4ba4150b5742fbac8e7df2e568778a5c0abc856a5920ce6b03b0aac04ee155e57dd205d0f4ae805ec1e03724e2888c463d1a0c118dfb5a37b2d4.png)

**Comment by RachelDCE** [comment]
Still not working in last test on qa/2017 Emory University. Version js/fix-school-dept-embargo-switching updated 14 August 2018.
