### ISSUE TITLE
Chair/Committee members disappear after saving and refreshing or logging out

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts/laevigata#1584]
After I add committee members - save - log out or refresh - they all disappear.

This branch and server:

© 2017 Emory University. Version js/department-persistence-fix updated 10 August 2018.
https://qa-upgrade-etd.emory.edu/

**Comment by RachelDCE** [comment]
I can't tell if this is the same exact issue as #1568. So I added this one with the version info for this test.

**Comment by little9** [comment]
There was a fix for this in, but not on that branch at the time.

**Comment by bess** [comment]
I cannot re-create this. I believe it has been fixed.
