### ISSUE TITLE
Committee Chair and members doubling on edit screen

### ISSUE THREAD

**Issue by little9** [curationexperts/laevigata#1593]
It seems like the list is getting appended to itself each time you save on the edit screen
so you end up with large amounts of duplicate chairs and members.

**Comment by little9** [comment]
This is not longer happening, they aren't doubling, but we need to determine a way to edit them.

**Comment by RachelDCE** [comment]
This is solved in    qa/2017 Emory University. Version js/fix-school-dept-embargo-switching updated 14 August 2018.
