### ISSUE TITLE
Embargoed content not displaying on edit form

### ISSUE THREAD

**Issue by little9** [curationexperts/laevigata#1595]
What we get back from fedora is not what is in the form. So we either need to translate between the to
or change the form so that it matches fedora expects.

The form has a string that lists out what is embargoed, like "toc, abstract"

The server is returning individual params for each

**Comment by bess** [comment]
Still not fixed as of evening of August 12

**Comment by bess** [comment]
Remove this code if it's no longer needed: https://github.com/curationexperts/laevigata/blob/master/app/actors/hyrax/actors/etd_actor.rb#L21-L30

**Comment by RachelDCE** [comment]
Tested and fixed. 

Tested on QA |  © 2017 Emory University. Version rebased_hyrax_2.2 updated 16 August 2018.
