### ISSUE TITLE
Add School, Program and Department metadata to ETDs

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#16]
- [x] Determine predicates to use for School, Department, and Degree
- [x] Change degree to use http://vivoweb.org/ontology/core#AcademicDegree
- [x] Change department to use http://vivoweb.org/ontology/core#AcademicDepartment
- [x] Change school to use http://vivoweb.org/ontology/core#School
- [x] Add fields to ETD Edit form
- [x] Add fields to ETD Show page
- [x] Add fields to ETD Search results
- [x] Allow faceting on fields

**Comment by bess** [comment]
Predicates will be drawn from this document: https://docs.google.com/spreadsheets/d/13Y8iEqT2daThb6qqeKSsmZFKbPeDHhWGxXzfJWUAFSQ/edit#gid=854977831

**Comment by mark-dce** [comment]
You can get a code diff view like you get for PRs, but without needing to make and actual PR by using the github compare tool.  Push the branch you're working on to github, look at the code view in github and target your working branch, then use the compare tool.
<img width="1029" alt="github compare" src="https://cloud.githubusercontent.com/assets/3064318/24808509/9b96a1e2-1b81-11e7-9b77-3976f638053d.png">

Which gives you something like
https://github.com/curationexperts/laevigata/compare/add_school_metadata

**Comment by bess** [comment]
Program and department are the same thing in the Emory terminology, so I added School, Department, and Degree:
```
  property :department, predicate: "https://schema.org/department"
  property :school, predicate: "https://schema.org/alumniOf"
  property :degree, predicate: "http://bibframe.org/vocab/dissertationDegree"
```
Predicates drawn from https://docs.google.com/spreadsheets/d/13Y8iEqT2daThb6qqeKSsmZFKbPeDHhWGxXzfJWUAFSQ/edit#gid=854977831
