### ISSUE TITLE
Adding a file from box removes the school and department

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#1603]
During my submission process, if I upload a file from box it removes my school and department.

**Comment by bess** [comment]
@little9 I just tested this with your Sunday night PR and I can re-create it on the server.
1. Start a new ETD
2. On the file submission page add a pdf and a new supplemental file 
3. Go to the next tab and you can't select embargo b/c the school setting has been lost

**Comment by little9** [comment]
@bess Did you clear out any InProgressEtds before testing it?
