### ISSUE TITLE
Restrict students from inadvertently starting over

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1630]
- [x] Remove the start over button at the bottom of every tab
- [x] Add a "Start Over with a New School" button to the "About Me" tab once a student has saved the tab
- [x] Add a modal warning when students elect to start over

**WIREFRAMES**
**About Me - After Save - disabled school**
![1 about me - saved](https://user-images.githubusercontent.com/3064318/44106898-7674a1a6-9fbb-11e8-84c6-5301aead36df.png)

**Modal Warning if student clicks "Start Over"**
![1 modal start over warning](https://user-images.githubusercontent.com/3064318/44106914-803a9c68-9fbb-11e8-98a2-4a58107d05d0.png)

**Comment by RachelDCE** [comment]
This has been tested and is fixed. 

Tested on QA | 2017 Emory University. Version master updated 17 August 2018.
