### ISSUE TITLE
Remove "Start Over" Option for previously submitted ETDs

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1631]
**ACCEPTANCE**
When I am editing a previously submitted ETD
- [ ] Do not provide any "Start Over" option

See also #1630

**Comment by val99erie** [comment]
When editing a previously-submitted ETD, it should not ever be possible to trigger that `changeFormMethod()` function.

**Comment by RachelDCE** [comment]
***Upon further investigation:  The button on edit actually does work. The Warning shows up off screen at the bottom of the page.
