### ISSUE TITLE
Auto-create the (4? 5?) AdminSets for the top level schools

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#164]
- [x] Double check which schools we want. Are they:
  - Candler School of Theology
  - Laney Graduate School
  - Rollins School of Public Health
  - Honors Undergraduate Program
- [x] Add these to a config file (json? yml?) that can drive a UI
- [x] Update the seeds.rb file to draw from the config file and name the schools properly instead of "School One" etc.

**Comment by mark-dce** [comment]
There appears to be a larger list of schools at http://www.emory.edu/home/academics/programs/index.html.  I'm assuming that the four listed above are the only ones that submit either theses or dissertations to the repository.  Do we need to change the name of the last item to "Emory College of Arts and Sciences" from "Honors Undergraduate Program" to be consistent with the school name as it might be supplied by ESD & Shibboleth?
