### ISSUE TITLE
Establish workflow plans for all top level schools

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#165]
As Carla, I want each school to use an appropriate workflow. What workflows are appropriate for each AdminSet? Related to #113.

- [x] Can any schools use the same workflow? (Likely yes, but Fran is checking. However, none can use the "one step mediated workflow" that comes with Hyrax)
- [x] For any that diverge, how do they diverge? Document this. 
- [x] Create tickets to implement any workflow needs that are discovered
- [x] Fran to check whether Rollins, Emory College, and Candler want to simplify their approval workflow

**Comment by bess** [comment]
Bethany, Fran and I talked this through, and produced diagrams for each school:
Laney: https://docs.google.com/drawings/d/1oCNgx4XiDzZdsomnTkP4LVkVBtr0rHJ4OJhZUXlmJo0/edit?usp=sharing
Rollins: https://docs.google.com/drawings/d/1E-K0_npXFkM1g2bKwOSID4H0zmBqmWlJ5EUMQK2U2_k/edit?usp=sharing
Emory College: https://docs.google.com/drawings/d/1b-7olliPlF5seqrotAz624GrNF8VHOJyMhiH3kMHZ5U/edit?usp=sharing
Candler: https://docs.google.com/drawings/d/1dnrZWlKgDTEhZ0udKYPkiLsaZ0EoBkp8sEziRsMDWQ8/edit?usp=sharing

**Comment by fpici** [comment]
On May 16th, Bess wanted to know if we want to streamline the review and approval process for School Reviewers. I reached out to Candler, College Honors, and Rollins to see if they use the “reviewed” status queue like Laney uses the "reviewed queue." In other words, do they have a process where they need to have a record sitting in the “reviewed status queue” before it is “approved?” If not, we can eliminate that step for Candler, Rollins, and College Honors and continue to retain for Laney. As of May 24th all schools have replied to me BUT Rollins. They have folks on vacation and will give me their answer next week. So, this will surely need to move to the next sprint but it has been an Action Item for this sprint.

**Comment by bess** [comment]
@fpici What was the answer from Candler and Emory college? Can we eliminate it for them?

**Comment by fpici** [comment]
Hi Bess. Yes, we can eliminate the "reviewed queue" for Candler and College Honors. Waiting on Rollins to respond maybe next week :-)

**Comment by bess** [comment]
Great! Thank you!

**Comment by fpici** [comment]
Good Morning Bess. It is now confirmed, we can eliminate the "reviewed queue" for Rollins School of Public Health too :-)
