### ISSUE TITLE
Hitting "C", "E", "L", "R" or accidentally releasing my mouse selects a school that I can't change

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1651]
**ISSUE**
Users should be able to see and change the school options until they hit "Save and Continue"

**ACCEPTANCE**
- [ ] School remains selectable until I hit "Save and Continue" on the "About Me Tab"

**Comment by RachelDCE** [comment]
This is fixed. 

Tested on QA | 2017 Emory University. Version master updated 17 August 2018.
