### ISSUE TITLE
Once submitted - Embargo type doesn't display on review screen as expected

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts/laevigata#1666]
![screen shot 2018-08-17 at 9 48 36 am](https://user-images.githubusercontent.com/23509160/44272555-cdbab600-a202-11e8-8f7a-c6f384ace1d6.png)

Testing on QA / © 2017 Emory University. Version rebased_hyrax_2.2 updated 16 August 2018.

**Comment by RachelDCE** [comment]
The form asks: 
-Length
-Content to embargo

The review shows Content Types before Length and the true/false format isn't clear.

**Comment by mark-dce** [comment]
We believe this was resolved in the course of other fixes.  Will open a new ticket if users report any related issues.
