### ISSUE TITLE
Can't edit an ETD in Safari

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts/laevigata#1674]
Rachel is testing the edit screen. I asked her to check that each field is individually editable. In safari, when she attempts to edit the first field, the name, she cannot resubmit -- it just spins. The same ETD is editable by the tezprox user in chrome. I have tested this on my local laptop and I see the same behavior -- the edit screen does not work as expected in Safari.

**Comment by little9** [comment]
This is related to a bug in Safari 11: https://bugs.webkit.org/show_bug.cgi?id=184490
