### ISSUE TITLE
Replacing the primary PDF file only works the first time

### ISSUE THREAD

**Issue by val99erie** [curationexperts/laevigata#1677]
**Steps to reproduce the problem:**

* Log in as a student, fill in the form for a new ETD, and submit it.

* Log in as an approver, and mark the ETD as 'changes requested'.

* Wait for background jobs to finish running.

* Log in as the student, and press the button to edit the ETD.

* In the edit form, remove the primary PDF file, add a new primary PDF file, and submit the form.

* Wait for background jobs to finish running.

* Reload the ETD show page, and you should see your new PDF file (as expected).

* Hit the edit button again.

* Do it again:  In the edit form, remove the primary PDF file, add a new primary PDF file, and submit the form.

* Wait for background jobs to finish running.

**Notice these problems:**

* You won't see it in the list of files on the ETD show page, but if you click 'File Manager', you'll see the old PDF file that you supposedly deleted.

* The new file did get saved, but the thumbnail and representative are still set to the old file.

* If you look in the Rails log, you'll see 403 errors from CANCAN access denied.  This was from the request to delete the file.

```
[CANCAN] Checking edit permissions for user: valerie with groups: ["public", "registered"]
[CANCAN] edit_groups: []
[CANCAN] edit_users: []
[CANCAN] decision: false
Completed 403 Forbidden
```

* If you check the rails console, you can see that there's one more FileSet record than you would expect, and there's an extra primary PDF file attached to the Etd record:

```
etd.primary_file_fs.count
 => 2   # This should be 1
```

**Comment by val99erie** [comment]
I suspect this same problem will exist for supplemental files - you'll be able to remove files that you added the first time you submit, but if you add files later, probably those files will have this same 'access denied' problem.

**Comment by bess** [comment]
As of version v2.0.0-beta4 updated 20 August 2018, I cannot re-create this error. On the qa-upgrade server I took an existing ETD. I replaced the primary PDF several times in a row. I attached supplemental files and replaced each of them several times in a row. I believe this got fixed by some other change we made. I see the correct behavior in the UI, and when I check the object on the console I also see only the expected file sets attached:
```
irb(main):002:0> etd.file_sets
=> [#<FileSet id: "th83kz366", embargo_length: nil, pcdm_use: "primary", file_type: nil, head: [], tail: [], depositor: "P1529006", title: ["Wonderful Thesis"], date_uploaded: "2018-08-20 16:52:57", date_modified: "2018-08-20 16:52:57", label: "Application_Step_by_Step__Duke___2_.pdf", relative_path: nil, import_url: nil, resource_type: [], creator: ["P1529006"], contributor: [], description: [], keyword: [], license: [], rights_statement: [], publisher: [], date_created: [], subject: [], language: [], identifier: [], based_near: [], related_url: [], bibliographic_citation: [], source: [], access_control_id: "faaaaee6-a3e7-4c48-ba6d-201f4f14474c", embargo_id: nil, lease_id: nil>, #<FileSet id: "0k225b092", embargo_length: nil, pcdm_use: "supplementary", file_type: "Image", head: [], tail: [], depositor: "P1529006", title: ["Hydra"], date_uploaded: "2018-08-20 16:57:02", date_modified: "2018-08-20 16:57:02", label: "Hydra.tif", relative_path: nil, import_url: nil, resource_type: [], creator: ["P1529006"], contributor: [], description: ["woodcut"], keyword: [], license: [], rights_statement: [], publisher: [], date_created: [], subject: [], language: [], identifier: [], based_near: [], related_url: [], bibliographic_citation: [], source: [], access_control_id: "d8164578-fe26-4c2f-8090-56701812ff2a", embargo_id: nil, lease_id: nil>]
irb(main):003:0> etd.file_sets.count
=> 2
irb(main):004:0> etd.primary_file_fs.count
=> 1
```

**Comment by bess** [comment]
@mark-dce and @RachelDCE Would you please verify that you also cannot re-create this bug?

**Comment by bess** [comment]
We need to insert this somewhere: 
```
 Hyrax::Workflow::GrantEditToDepositor.call(target: etd) 
```

**Comment by RachelDCE** [comment]
Tested and this works now.

Tested on QA | © 2017 Emory University. Version master updated 23 August 2018.
