### ISSUE TITLE
Validation on "My Files" tab

### ISSUE THREAD

**Issue by val99erie** [curationexperts/laevigata#1678]
When you add a supplemental file on the "My Files" tab, you aren't supposed to be able to save the tab until you have filled in all the metadata fields, but I was able to save with some fields missing.

**Comment by val99erie** [comment]
I suspect you can fix this in `app/javascript/Files.vue`, if you trigger the tab validation at the end of the `onMetadataChange` method.
(i.e. Every time the user fills in one of the metadata fields, it should check whether or not the tab is valid.)

**Comment by RachelDCE** [comment]
Tested and is fixed

Tested on QA | © 2017 Emory University. Version v2.0.6 updated 19 September 2018.
