### ISSUE TITLE
Make a config file for partnering agencies

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#168]
- [x] Work from the PDF document we have already to type in a list of partnering agencies into a JSON config file
- [x] Drive a drop down menu from it
- [x] Check with Bethany to see if the list is correct

**Comment by shanitajohn** [comment]
Make a config list from this PDF: https://drive.google.com/drive/folders/0B8imcSJ3yFamSHFWejZFQWh6SEE

Page 15

**Comment by alexBLR** [comment]
Emily: "I do have some suggestions in the ETD metadata sheet (see ETD18). https://docs.google.com/spreadsheets/d/13Y8iEqT2daThb6qqeKSsmZFKbPeDHhWGxXzfJWUAFSQ/edit#gid=854977831 If all else fails, we could use one of the various generic "Contributor" predicates."
