### ISSUE TITLE
Should not be able to select an embargo w/out an embargo type

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#1683]
- [x] In the initial submission, I shouldn't be able to select an embargo length without an embargo type
- [x] When I'm editing my ETD I should not be able to select an embargo length without an embargo type

**Comment by RachelDCE** [comment]
Tested and acceptance criteria is met.

Tested on QA |  2017 Emory University. Version v2.0.0-beta6 updated 21 August 2018
