### ISSUE TITLE
Submit button disappears when I check agreement

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1687]
Server: https://qa-upgrade-etd.emory.edu/
Release: Version v2.0.0-beta3 updated 19 August 2018

**ISSUE**
I can submit an ETD without having the submission checkbox checked / I have to uncheck the agreement box to unhide the submission button.

**STEPS TO REPRODUCE**
https://youtu.be/POlUV2B1pJ8
At least one possible way to reach this state is as follows:
1. Close Chrome
1. Launch Chrome
1. Open a new incognito window
1. Login as MBUSSE2
1. Enter a an ETD using the default option wherever possible and any data in string fields
1. On the review screen, check the submission checkbox
1. Go back to the "Keywords" tab (any tab probably works)
1. Make a change like adding a keyword
1. Click the "Save & Continue" button
1. Scroll to the bottom of the "Submit" tab

**EXPECTED BEHAVIOR**
* I should be able to check the submission agreement *AND* click on the "Submit" button

**ACTUAL BEHAVIOR**
* I can check the submission agreement *OR* click on the "Submit"

**ACCEPTANCE**
- [x] The checkbox is always displayed
- [x] The submit button is *always* displayed and enabled
- [x] If I click the "Submit Your Thesis or Dissertation" button without having the agreement checked, I get an error message below the agreement checkbox.

**Comment by RachelDCE** [comment]
Tested and is fixed.

Checkbox on review remains clicked after changing, adding or deleting a keyword.
And the Submit is displayed. 
And if I uncheck the box the Submit button is disabled.
Check it again and I can submit

Tested on QA - 2017 Emory University. Version v2.0.0-beta5 updated 20 August 2018
