### ISSUE TITLE
Approvers should not have to re-check submission agreement when editing an ETD

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1688]
Server: https://qa-upgrade-etd.emory.edu/
Release: Version v2.0.0-beta3 updated 19 August 2018

**ISSUE**
When I edit an existing ETD as an approver or administrator, the student's acceptance agreement status is not persisted and I have to re-check it before submitting.

**STEPS TO REPRODUCE**
https://youtu.be/bJIj_9ooaJs
1. Close Chrome
1. Launch Chrome
1. Open a new incognito window
1. Login as tezprox
1. Find an existing ETD to edit
1. On the submit tab, scroll to the bottom

**EXPECTED BEHAVIOR**
* The submission agreement checkbox should be checked and I can click on "Submit"

**ACTUAL BEHAVIOR**
* I have to re-click on the acceptance agreement checkbox before the submit button appears to let me save any changes

**ACCEPTANCE**
- [x] The checkbox state is not lost when editing already submitted ETDs
- [x] The user editing the ETD can submit the edits without having to re-check the checkbox

**NOTES:** 
* It would be acceptable to disable the checkbox after the student initially submits the ETD to the department.

* Students should not be able to submit an ETD without checking the agreement box - also see #1687

**Comment by RachelDCE** [comment]
Tested and fixed. 

Tested on QA | 2017 Emory University. Version v2.0.0-beta6 updated 21 August 2018
