### ISSUE TITLE
Department should have a disabled default value

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1695]
**ISSUE**
On the "My Program Tab" Degree and Submission type both have default values that are disabled, Department does not.  All three should be handled the same way.

**ACCEPTANCE**
- [x] Add the default option to Department (requested 6/12) OR remove it from the other fields on the form (v1.6.9)

**NOTE:** The current version of the UI v1.6.9 does not have default values.  The 6/12 wireframe requested that all fields on the "My Program Tab" have default selections that are disabled.  

![2 my program](https://user-images.githubusercontent.com/3064318/44313322-16719b00-a3cc-11e8-96a9-3482437416be.png)

**Comment by RachelDCE** [comment]
Tested and is fixed. Department now has a placeholder like the other fields on this tab. 


Tested on QA | 2017 Emory University. Version v2.0.0-beta6 updated 21 August 2018.
