### ISSUE TITLE
Department options disappear when I click refresh

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1697]
Server: https://qa-upgrade-etd.emory.edu/
Version v2.0.0-beta3 updated 19 August 2018.

**ISSUE**
The the "My Program" tab, if I click refresh for any reason, the department dropdown becomes empty.

**STEPS TO REPRODUCE**
https://youtu.be/Ea7yZevz67Y
At least one possible way to reach this state is as follows:
1. Close Chrome
1. Launch Chrome
1. Open a new incognito window
1. Login as MBUSSE2
1. Fill in the "About Me" tab with any valid data
1. Click "Save and Continue"
1. On the "My Program" tab, select a department
1. Hit refresh on your browser

**EXPECTED BEHAVIOR**
* My department selection should be cleared (along with any other selections) and I should be able to select a new department

**ACTUAL BEHAVIOR**
* The department dropdown is blank

**ACCEPTANCE**
- [ ] When I hit refresh, the department selection gives me the correct options for my school (similar to the behavior of the degree and submission type lists)

**Comment by little9** [comment]
Dupe of #1668 , addressed in the open PR #1689

**Comment by mark-dce** [comment]
UPDATE: 
It appears that the selection state can be retained - for instance see School selection behavior on the "About Me" tab.  If possible, we should be consistent about the behavior across fields: if refresh can retain any current selections on the current tab, that would be nice.

**Comment by mark-dce** [comment]
@little9 sorry for the duplicate - I thought I'd scanned all the open issues, and missed this one.
