### ISSUE TITLE
Subdepartment should be displayed on the "Submit" tab

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1708]
**ISSUE**
When I enter a sub-department on the "My Program" tab, it does not appear when I review my entries on the "Submit" tab

**ACCEPTANCE**
- [x] When I have selected a Sub-department, both are displayed on the "Submit" tab.
- [X] When my selected Department does not have sub-department options, sub-department is not displayed on the "Submit" tab

**Comment by RachelDCE** [comment]
Tested and fixed. Subfields show on Submit page and that field doesn't show up on Submit  if there isn't a subfield.
