### ISSUE TITLE
After submission, let students know their file won't appear right away

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#1725]
Out of the box, Hyrax has a flash notice that says something like "It will take a few minutes for your files to appear" that a user sees immediately after submission. We should add something similar so that after a student submits they don't think their attached files have been lost.

**Comment by mark-dce** [comment]
How about "Your files are being processed and your school will be notified. It will take a few minutes for your files to appear here. Once your submission has been reviewed and approved, or if there are changes requested, you will be notified."

**Comment by mark-dce** [comment]
We believe this has been resolved via other changes to UI
