### ISSUE TITLE
Add placeholder text for Content to Embargo

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts/laevigata#1729]
We use placeholder text in other fields in other tabs. Could we use "Select the content to embargo"? As a student I might think that the defaulted "Files" is all encompassing and means that everything is embargoed and I'm good to go -- so might save without engaging the pull down. Therefore my table of contents or abstract aren't embargoed when I actually wanted to embargo all"

**Comment by mark-dce** [comment]
Will open a new ticket if more specific user issues occur.
