### ISSUE TITLE
All connections must be SSL encrypted

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#173]

**Comment by acozine** [comment]
Related to #89. Baseline on the server side on emory.curationexperts.com is done - default connection is https: and if you try to connect with http: you get redirected to https:. 

I have not tried issuing curl commands to sub-URLs seeking clear-text (http) responses.

**Comment by mark-dce** [comment]
@acozine implemented the server side configuration.  We tested to ensure that any application url called via http would successfully redirect to it's https equivalent:

http://emory.curationexperts.com/admin_sets/5999n3367?locale=en
http://emory.curationexperts.com/
http://emory.curationexperts.com/about
http://emory.curationexperts.com/catalog?utf8=✓&search_field=all_fields&q=

All of the above link types were checked and redirect appropriately to their secure http (HTTPS) equivalents.

**Comment by acozine** [comment]
In addition to the systems setup changes, we needed to uncomment `config.force_ssl = true` in `config/environments/production.rb`. Without this change, pages will be sent over HTTPS but cookies will be sent via HTTP only. See #760.
