### ISSUE TITLE
Embargo Management "Return to editing" link behaves erratically

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1731]
**ISSUE**
As an administrator or approver, when I use the Manage Embargos page to manage a specific Work's embargo, there is a button that says "Return to editing this ETD" that takes me to a blank page

Server: https://qa-upgrade-etd.emory.edu/
Version v2.0.0-beta6 updated 21 August 2018.

**STEPS TO REPRODUCE**
https://youtu.be/upZhhE0_dJI
1. Login as an administrator
1. Go to the dashboard
1. Click on the "Manage Embargos" link in the left navigation bar
1. Click on any work listed on the "All Active Embargos" tab
1. Click on the "Return to editing this ETD" button

**ACTUAL BEHAVIOR**
* The application sometimes takes me to a blank page, sometimes a blank ETD form, sometimes partially populates the form, and sometimes fully populates the form.  

**DESIRED BEHAVIOR**
* The application should take me to the edit view for the ETD I selected with all data fully populated
OR
* Just remove the button from this page

**Comment by val99erie** [comment]
I think this is just interference with turbolinks.  If so, it's easy to fix.  I'll do some more testing in the morning.

**Comment by RachelDCE** [comment]
I tested this with 2 graduated, embargoed ETDs 

1.  "testing embargo on edit matches ETD - 8/24".  It is an ETD known to have all fields filled.
2.  "Effects on Anthropogenic Disturbance on Zoonotic..." by Michele Parsons  

Following the steps above I found it to show desired behavior. 

Tested on QA | © 2017 Emory University. Version master updated 27 August 2018.
