### ISSUE TITLE
file limit exceeded user msg displays before upload begins

### ISSUE THREAD

**Issue by jenlindner** [curationexperts/laevigata#174]

**Comment by jenlindner** [comment]
This is a sub-ticket of #111, and should fulfill the following: “let the user know before they start upload if their file is too big (because of poor user experience) to use the the built-in uploader.”

**Comment by jenlindner** [comment]
Initial testing found that there is a red error message displayed to the user if a file over 500MB is submitted, a default config setting, and the user must choose cancel to get back to a submit state. Incidental testing gave me a timeout on a 300 MB file on one attempt. I'll update this ticket with more data as I get it.

**Comment by jenlindner** [comment]
Starting to work with Browse Everything, uploaded a 470MB file quickly, but fits ran out of memory before finishing processing. I'm using Fits 1.0.5.

**Comment by jenlindner** [comment]
hi @acozine, is there a production-testing environment I could push this branch to, in order to get more accurate information about CPU and memory usage? And also, do we have test cloud keys I could use in the Browse-everything config? I need to find which cloud providers we're supporting, as well.

**Comment by acozine** [comment]
@jenlindner the sandbox environment is set up in production mode - deploy a branch there with `BRANCH_NAME=mybranch bundle exec cap aws deploy`.

**Comment by jenlindner** [comment]
We have Browse-everything working on the stress-test server, and I was able to upload a 474MB file from one of the providers, Box, in a few seconds.

**Comment by jenlindner** [comment]
This ticket has spawned other work, defining the feature of uploading very large files. This ticket then has the extremely concise scope of 'display error message when the user tries to upload a file that exceeds the configured file size limit', and that requirement is met.
