### ISSUE TITLE
I should get an error when I try to save from the My Files tab without a primary PDF

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1741]
**ISSUE**
I can click "Save and Continue" on the "My Files" tab and continue to the "Embargo" tab without selecting a primary PDF. 

Server: https://qa-upgrade-etd.emory.edu
Version v2.0.0-beta7 updated 21 August 2018

**STEPS TO REPRODUCE**
https://youtu.be/KD51Q9_IX_Q
1. Login to qa-upgrade as a student (& clear any existing submissions)
1. Fill in the tabs up to "My Files"
1. On the "My Files" tab, click "Save and Continue" without adding any files

**EXPECTED BEHAVIOR**
* I should get an error indicating that I need to attach a primary PDF

**Comment by RachelDCE** [comment]
Tested and got an error message. 

Tested on QA | © 2017 Emory University. Version master updated 23 August 2018.
