### ISSUE TITLE
Supplemental files appear not to submit

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#1743]
Supplemental files (from box, definitely, and we should check whether this is true for local files too) do not appear as expected on an ETD. The file is fetched from Box, a fileset is created and attached, but all files are attached as "primary", which means only the first primary file shows up on the screen.

Tested in v2.0.0-beta8 locally and on qa-upgrade and etd-upgrade

**Comment by RachelDCE** [comment]
Have tested this many times today with both local and box files logged in as MBUSSE2. The supplemental file DOES appear as it should - as supplemental files on the Submit tab. 

However I cannot get them to show up as expected when I go back to MyFiles and delete the supplement. Supp files deleted on MyFiles persist on the Submit tab. See ticket #1755. 

And I would like to test to see what it looks like as an approver, but can't get through to save the ETD. See ticket #1757.

**Comment by RachelDCE** [comment]
This issue has been tested and is fixed.
