### ISSUE TITLE
'ETD' should be uppercase on the tab

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#1749]
On the submission form tab, 'ETD' should be capitalized

**Comment by mark-dce** [comment]
Confirmed fixed
Version v2.0.0-beta10 updated 27 August 2018

<img width="1195" alt="1749 - etd capitilization - fixed" src="https://user-images.githubusercontent.com/3064318/44675555-813b5b80-a9f6-11e8-87d9-b0b7892de24e.png">

**Comment by mark-dce** [comment]
DOH!  It should also be capitalized in the text on the tab :(

<img width="544" alt="1749 - capitalization in body of tab" src="https://user-images.githubusercontent.com/3064318/44700008-701d3980-aa4c-11e8-8de6-a63d4d6ef1e8.png">

**Comment by RachelDCE** [comment]
This is fixed. Tested on QA | © 2017 Emory University. Version v2.0.1-beta1 updated 28 August 2018.
