### ISSUE TITLE
Determine rules for who has to submit to ProQuest

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#175]
Related to #116

**Comment by shanitajohn** [comment]
Related to #116

**Comment by shanitajohn** [comment]
Hi @fpici and @bnash108,  Bess and I are reviewing ProQuest tickets to make sure we have all  requirements gathered and documented.

**Comment by bess** [comment]
We are assuming that only Laney students are submitting to ProQuest, and all Laney students are submitting to ProQuest

**Comment by bnash108** [comment]
@bess correct

**Comment by bnash108** [comment]
@bess @shanitajohn Sorry, I just read the comment above again. All Laney ph.d students are required to submit to ProQuest. It's optional for masters students.

Re: masters students -- not sure if this is a question that originated on y'all's end our ours while I was on medical leave, but I did follow up with ProQuest about submitting masters theses & any special considerations. Response from ProQuest below:

"There is nothing special that needs to happen here. Masters can be packaged up with doctoral submissions. The XML that comes with them, as they do currently, ingests into our systems and are separated at that point."
