### ISSUE TITLE
Local supplemental files get wiped out when open Box

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts/laevigata#1758]
If I add two _local_ supplemental files and then try to add a file from _box_ - the two local files get wiped out. The file from Box persists, but I don't see the two local files at Submit.

If I add a file from Box first, I can add and save another supplemental from my files. 

Once Box is opened - I cannot cancel or get rid of Box. -- Cancel button doesn't do anything.

Then cannot submit my ETD. See ticket #1757 

(I add all these notes because I assume some of the behavior is related to the others.)

Tested on QA | 2017 Emory University. Version master updated 23 August 2018

**Comment by RachelDCE** [comment]
A warning was added for students to save and continue after each supplemental file.

I am still seeing issues with adding local and box files. Jen will work on it some more. 

Tested on QA | © 2017 Emory University. Version v2.0.1 updated 29 August 2018.

**Comment by jenlindner** [comment]
Cannot reproduce the issues Rachel demonstrated to me locally.

**Comment by RachelDCE** [comment]
Tested and is fixed. 

Tested on QA | © 2017 Emory University. Version v2.0.6 updated 19 September 2018.
