### ISSUE TITLE
Decide how to submit address to ProQuest

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#176]
* Can we figure out a way not to have to store people's addresses? 
* Can we get the address from ESD at the time of submission to ProQuest?

**Comment by shanitajohn** [comment]
Related to #205

**Comment by bess** [comment]
We have decided that we will not store student addresses. We will pass along the address they have on file with the registrar. When we are migrating content from legacy data, we will discard student addresses instead of migrating them. Students will *not* be asked to update their address during the ETD submission process. Instead, if they have the wrong address displaying, we should ask them to contact the registrar's office and update it there.
