### ISSUE TITLE
Thumbnails not displaying for non-authenticated users

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1763]
**ISSUE**
Thumbnails for public works are not displaying for non-authenticated users.

**STEPS TO REPRODUCE**
1. Log out and close your browser (to ensure shibboleth logout)
1. Open a new browser
1. Do a query of all items in the repository - e.g.
https://qa-upgrade-etd.emory.edu/catalog?utf8=%E2%9C%93&locale=en&search_field=all_fields&q=
1. Visit any single public item - e.g.
https://qa-upgrade-etd.emory.edu/concern/etds/3j3332367?locale=en
1. Login as 

**EXPECTED BEHAVIOR**
* I should see thumbnails for all public items in search results
* I should see thumbnails for public items in single items views

**ACTUAL BEHAVIOR**
* Search results display thumbnails inconsistently, even for public ETDs
* ETDs don't show thumbnails in the single item view unless I'm logged in as the submitter or an admin/approver.

**Comment by mark-dce** [comment]
<img width="815" alt="1763 - search results tezprox" src="https://user-images.githubusercontent.com/3064318/44698244-c25a5c80-aa44-11e8-94c6-8b668b1a077d.png">
<img width="903" alt="1763 - search results unathenticated" src="https://user-images.githubusercontent.com/3064318/44698245-c25a5c80-aa44-11e8-8fe4-03cbb3636b65.png">
<img width="860" alt="1763 single item submitter" src="https://user-images.githubusercontent.com/3064318/44698246-c2f2f300-aa44-11e8-9a60-357ab473f135.png">
<img width="861" alt="1763 single item unauthenticated" src="https://user-images.githubusercontent.com/3064318/44698247-c2f2f300-aa44-11e8-85d3-e928b13a3cf4.png">

**Comment by no-reply** [comment]
As a first breadcrumb, the `#representative` file for the works exhibiting this behavior seem to be marked `restricted` even though the works themselves are `open`.
