### ISSUE TITLE
No Validation Errors but can't submit with blank Abstract or Table of Contents

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1765]
**ISSUE**
When I click to "Save and Continue" from the "My ETD" tab without entering an abstract or table of contents, nothing happens.  I should get some kind of notification.

**STEPS TO REPRODUCE**
1. Login as a student
1. Start a new ETD
1. Fill in each tab up to "My ETD"
1. Fill in the Title and Language on the "My ETD", leave "Abstract" and "Table of Contents" blank
1. Click "Save and Continue"

**EXPECTED BEHAVIOR**
* I should get a validation error saying "Abstract is required" (i.e. same behavior as Title currently has)
* I should get a validation error saying "Table of Contents is required"

**ACTUAL BEHAVIOR**
* I click on the button and nothing appears to happen

**Comment by RachelDCE** [comment]
Tested and it is fixed. 

Tested on QA | © 2017 Emory University. Version v2.0.6 updated 19 September 2018.
