### ISSUE TITLE
Remove code for old UI

### ISSUE THREAD

**Issue by val99erie** [curationexperts/laevigata#1770]
Tasks:

PRIOITY
- [x] Update Travis config to remove builds for old UI
- [x] Ensure non-UI code tests still run when `NEW_UI_ENABLED=false` tests are no longer being run

BEST EFFORT
- [ ] Remove code and specs for the old UI.  Grep the code for things like:
- `new_ui`
- `NEW_UI_ENABLED`
- "Old UI", "New UI"

**Comment by jenlindner** [comment]
There is one feature spec that will not run, the controlled_vocabulary_spec.rb, but the functionality it tests is covered in the javascript/test/GraduationDate.spec.js file. Any further tests of that feature should be done in the js file as well.
