### ISSUE TITLE
File ServiceNow tickets for Shibboleth and ESD

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#180]
Collin needs to submit two separate ServiceNow requests, one for "shibboleth" and one for "ESD", even though we expect all info to be delivered via the same system.

- [x] Phone call for Collin, Anne Marie, and Bess to go through metadata spreadsheet
- [x] What info precisely needs to be in these requests?
- [x] Track whether the info we need is gathered
  - [x] Confidentiality agreement needs to be signed by DCE
- [x] Actually submit the requests

**Comment by rotated8** [comment]
All our metadata will come from Shibboleth or the Registrar, and no ESD request is necessary.
