### ISSUE TITLE
Screen for students who shouldn't be submitting

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#181]
If someone logs in and they are not a member of one of our expected departments / programs, direct them elsewhere.

**Comment by mark-dce** [comment]
@bess Is this a requirement from Emory?  It's a good idea, but it wasn't described in the initial requirements gathering as far as I know and wasn't included in the work scoped for the project.  Maybe move this to the bottom of the backlog and attempt if time permits?

**Comment by mark-dce** [comment]
We haven't seen this to be a significant issue in the time the system has been running.
