### ISSUE TITLE
Everyone at Emory should be able to log in for research

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#182]
Everyone at Emory should be able to log in for the purposes of reading institution-only ETDs

**Comment by mark-dce** [comment]
What is an institution-only ETD?  I don't know that Ive seen that in previous requirements.

**Comment by bess** [comment]
An ETD that has been embargoed to institution-only.

**Comment by mark-dce** [comment]
Is that a project requirement for Emory (or just functionality in Hyrax)?  I don't think it's an emory requirement - see step 26 & 27 of https://drive.google.com/drive/u/0/folders/0B8imcSJ3yFamSHFWejZFQWh6SEE - it looks like there's only embargo for everyone / don't embargo options.

**Comment by rotated8** [comment]
I think Fran or Lisa asked about restricting an ETD at the demo last week, when they saw the functionality in Hyrax. If it isn't in the requirements, can we move this to the bottom of the backlog?

**Comment by mark-dce** [comment]
Closing this ticket because it no longer aligns with the current embargo strategy.  We should open a new ticket with updated requirements if there's still a need in this area.
