### ISSUE TITLE
Copy Fran on all embargo expiration emails

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#1851]
- [x] All embargo expiration emails should also go to fpici@emory.edu

**Comment by fpici** [comment]
@rotated8 Just checking to see if this ticket  is functioning in Production right now?. The reason I ask is that we have a few expiration notifications today and I don't see any emails copied for me? No rush and many thanks in advance, Fran

**Comment by bess** [comment]
@fpici This work has not been released to production yet. I can talk to @rotated8 about how to prioritize that today.

**Comment by fpici** [comment]
Hi Bess. Not to worry and no real rush :-)
