### ISSUE TITLE
Runtime error when editing an ETD

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#1855]
We can recreate this bug by attempting to edit the embargo for this work:
https://etd.library.emory.edu/concern/etds/qr46r110q?locale=en

[Emory laevigata PROD/production] RuntimeError: Cannot find admin set config where school = Rollins School of Public Health and department =

According to fedora the department isn't blank:
```
irb(main):002:0> etd.school
=> ["Rollins School of Public Health"]
irb(main):003:0> etd.department
=> ["Executive Masters of Public Health"]
```
I can re-create the bug like this:
```
irb(main):004:0> etd.determine_admin_set
RuntimeError: Cannot find admin set config where school = Rollins School of Public Health and department = Executive Masters of Public Health
        from app/models/etd.rb:270:in `determine_admin_set'
        from (irb):4
```

## Backtrace

    line 270 of [PROJECT_ROOT]/app/models/etd.rb: determine_admin_set
    line 277 of [PROJECT_ROOT]/app/models/etd.rb: assign_admin_set
    line 55 of [PROJECT_ROOT]/app/actors/hyrax/actors/default_admin_set_actor.rb: ensure_admin_set_attribute!

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/56306/faults/40349594)

**Comment by bess** [comment]
The problem was that the department for this ETD was "Executive Masters of Public Health", but the admin set was called "Executive Masters of Public Health - MPH". When I manually updated the department value to match the name of the admin set the embargo edit feature began working again. If we want to prevent this from happening we'll need to add a lookup table to the `etd.determine_admin_set` method so that it doesn't require 100% strict matching on the names between the department and the admin set. However, I'm not sure how widespread this problem is. I'm going to do more investigation to see if I can figure that out.

**Comment by bess** [comment]
Update: There are about 336 objects affected by this, but it only covers a few department values:
* Biostatistics and Bioinformatics
* Career Masters of Public Health
* Executive Masters of Public Health

And three items where the department is blank.

**Comment by fpici** [comment]
Bess,

Thank you so much for jumping on this!

This will be interesting going forward because this record was a migrated record from Legacy ETDs.

I will be on the lookout for more as these legacy records’ embargo durations become due.

Frances Anne Pici (She, Her, Hers)
Scholarly Repository Application Support Analyst
Scholarly Communications Office
Emory University Libraries and Information Technology
Robert W. Woodruff Library
540 Asbury Circle
Atlanta, GA 30322
404.727.7673
fpici@emory.edu<mailto:fpici@emory.edu>
Check out our new websites!
Scholarly Communications http://sco.library.emory.edu/index.html
Research Data http://researchdata.emory.edu/index.html

**Comment by fpici** [comment]
Bess,

Thank you so much for this summary!!

Frances Anne Pici (She, Her, Hers)
Scholarly Repository Application Support Analyst
Scholarly Communications Office
Emory University Libraries and Information Technology
Robert W. Woodruff Library
540 Asbury Circle
Atlanta, GA 30322
404.727.7673
fpici@emory.edu<mailto:fpici@emory.edu>
Check out our new websites!
Scholarly Communications http://sco.library.emory.edu/index.html
Research Data http://researchdata.emory.edu/index.html

**Comment by rotated8** [comment]
Errors produced in 2.3.4 by [5d86p104d](https://etd.library.emory.edu/concern/etds/5d86p104d), [6m311q283](https://etd.library.emory.edu/concern/etds/6m311q283), and [5m60qr98k](https://etd.library.emory.edu/concern/etds/5m60qr98k)
