### ISSUE TITLE
School changes when an ETD is edited

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#1869]
When editing some ETDs, the school shown on the edit form is different from the school on the ETD's show page, and when the edited record is saved, the school changes.

Examples:
https://qa-etd.library.emory.edu/concern/etds/jm214p91d (Emory College --> Candler)
https://qa-etd.library.emory.edu/concern/etds/k930bz05d (Rollins --> Candler)
https://qa-etd.library.emory.edu/concern/etds/5x21tg372 (Laney --> Candler)

**Comment by bess** [comment]
This bug does not exist for all browsers. Colin can see it in Firefox 65.0.2 on Windows 10 (17.09).

**Comment by bess** [comment]
Updated:
Collin Brittle11:21 AM
I figured it out! The field is being set with data from an in progress ETD. If you start an ETD as Rollins, every ETD you edit will edit as Rollins. Start over with Candler, and they'll all switch to Candler.

**Comment by rotated8** [comment]
This means a work around to allow someone to edit an ETD is:
1. Identify the school for the ETD you want to edit
1. Log in
1. Click "Submit My ETD"
1. Fill in the "About Me" tab, choosing the school identified earlier.
1. Click "Save and Continue"
1. Navigate to the ETD you want to edit, and click "Edit"
1. Confirm that the correct school shows up in the edit form.

If you've already started an ETD:
1. Click on "Submit My ETD"
1. Click on the "About Me" tab
1. If the school isn't the one identified previously, click on "Start Over With a New School", which clears the in progress ETD, and sends you the homepage, then follow the steps above.

I have confirmed this works with @fpici

**Comment by rotated8** [comment]
Scratch that. Clicking submit after doing the above produces an error.

**Comment by bess** [comment]
Collin says this happens if you have an in-process ETD that's over-writing the value.
