### ISSUE TITLE
Create research field drop-down menu

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#188]
**STORY**
As a depositor, I would like to be able to select my research field from a list of available ProQuest options so that in the future, when researchers browse work by topic or fields, they will discover my work as well. 

**ACCEPTANCE CRITERIA**
- [x] I would like to be able to click on the drop-down and see a list of ProQuest research fields 
- [x] I would like to be able to choose a research field by clicking on the name in the list
- [ ] I would like to be able to designate a research field as "primary"
- [x] I would like to be able to add Additional Research fields (up to 2)
- [x]  I would like to be able to remove an Additional Research field 
- [ ] Since I can add up to 3 research fields, I would like a way to see which field I have designated as my primary research field 

**WIREFRAMES (updated 6/2/17)**
https://emory.box.com/s/l2gsln7vzsl972r0x8pe5i305f3h8ktf

Sample config file: 
https://emory.box.com/s/877m5ouglzg8a7sq383a5x2one5bgi4b

**Comment by shanitajohn** [comment]
Related to Ticket #242

**Comment by rotated8** [comment]
Parts of this were implemented in #277

**Comment by rotated8** [comment]
Config file in app: https://github.com/curationexperts/laevigata/blob/about-me-UI/config/authorities/research_fields.yml

**Comment by shanitajohn** [comment]
@rotated8 Can you add a "size" to this ticket please? Thanks!

**Comment by rotated8** [comment]
I'm not sure how to size this ticket, because I'm not sure how to approach the primary designation. Thoughts, @bess ? Limiting to three fields is a 1 for the backend, not sure about the frontend.

**Comment by bess** [comment]
I took the primary designation out of this ticket, since the research drop down menu is otherwise done. Let's regroup over in ticket #365
