### ISSUE TITLE
Run April Registrar data

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1884]
See https://curationexperts.freshdesk.com/a/tickets/97

**Comment by bess** [comment]
Data run in production. There were five new ETDs published, which I believe represent the missing undergraduate theses that Collin has been trying to track down and that are finally showing up in the registrar data as expected.

![degree_awarded_april_2019.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/9f71d9d6-3a6e-478d-a291-a5cac2294f5b)
