### ISSUE TITLE
Able to run in client AWS

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#190]
**ACCEPTANCE CRITERIA**
- [x] They have an account
- [x] We have administrative access to the account
- [x] Test building a server on that account
- [ ] ~Test backup and restore~ see #262 and #263 
- [ ] ~We can use DCE IAM credentials to access the client AWS resource(s)~

**Comment by acozine** [comment]
Today @SolomonHD and I ran through the Ansible scripts. Emory has an account and we can build servers on that account.

**Comment by shanitajohn** [comment]
Shanita to follow up with Rosalyn re: timing for getting an account, etc.

**Comment by acozine** [comment]
We can build servers on the Emory AWS account with IAM credentials. We are good to go.
