### ISSUE TITLE
Security vulnerability in all versions of Hyrax since 2.1.0

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#1901]
The following email just went out to samvera-partners. 

- [x] Check to ensure Emory's ETD application is not vulnerable to this security issue

**VULNERABILITY** 

**ASSESSMENT AND REMEDIATION** 
  
To view a list of Collections that may be affected, the following code may be executed in the Rails console: 

     CollectionBrandingInfo.where("target_url IS NOT NULL")

**Comment by bess** [comment]
The ETD application is not vulnerable to this issue.

```
deploy@etd:/opt/laevigata/current$ RAILS_ENV=production bundle exec rails c
Loading production environment (Rails 5.1.6.1)
irb(main):001:0>      CollectionBrandingInfo.where("target_url IS NOT NULL")
=> #<ActiveRecord::Relation []>
irb(main):002:0> exit
```

**Comment by bess** [comment]
Updated to redact the security details from this ticket, since it isn't supposed to be public yet.

**Comment by mark-dce** [comment]
Dear Samvera Community,

Hyrax 2.5.1 has just been released, and it includes an important security bug fix. We recommend upgrading to this version.

See the release notes for further information [1]

Julie Allinson

[1]  https://github.com/samvera/hyrax/releases/tag/v2.5.1
