### ISSUE TITLE
Two ETDs for force approval

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#1909]
https://curationexperts.freshdesk.com/a/tickets/101

These ETDs should be published, but didn't get caught by our registrar publication process somehow:

qf85nb31g - George, Nisha - Sum 2018
41687j53g - Stopa, Graham - Fall 2018

**Comment by mark-dce** [comment]
In checking the two ETDs before force publishing them, both appear to be published and publicly discoverable already.  I updated the FreshDesk ticket and asked Collin if there was anything else that needed to be handled.

qf85nb31g - George, Nisha - Sum 2018
https://etd.library.emory.edu/concern/etds/qf85nb31g?locale=en

41687j53g - Stopa, Graham - Fall 2018
https://etd.library.emory.edu/concern/etds/41687j53g?locale=en

If I don't hear back from him by EOD Tuesday, I'll reach out over slack and see what else needs to be done to resolve & close this issue.

**Comment by mark-dce** [comment]
From Freshdesk:
>Fran confirmed, these are good now. Thanks!
>
>Collin
