### ISSUE TITLE
Determine what counts as an outage

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#191]
- [x] Make a list of things to check and how to check them
  - [x] sign in (shibboleth connection)
  - [x] search
  - [x] fedora
  - [x] derivative creation
  - [x] file characterization
  - [x] fetch of data from ESD

**Comment by acozine** [comment]
We already have checks for:
- cpu load
- users logged in over ssh
- disk space on all mounted volumes
- home page (https) response
- ping (basic server up & responding)
- number of processes
- resque-pool workers active and working from current code
- ssh response
- solr response
- fedora response
