### ISSUE TITLE
Update rspec config to match current DCE practice

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#1913]
The rspec config for laevigata doesn't match what we did for californica and I suspect it might be out of date and not matching our current practice. At the moment, this is preventing consistent running of system specs. Seems worthwhile to fix this and document our recommended setup.

**Comment by little9** [comment]
@bess Could you use the capybara config from ursus:
https://github.com/UCLALibrary/ursus/blob/master/spec/support/capybara.rb
