### ISSUE TITLE
Create graduation date drop-down

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#193]
**STORY**
As a depositor, when I am in the About Me tab, I would like to be able to select my graduation date from a dropdown menu, so that my ETD is reviewed in time. I don't know how this all works but selecting the wrong graduation date seems like it would screw up my submission. 

**ACCEPTANCE CRITERIA**
- [x] I should be able to find the correct "Term" / "Year" combination to match my graduation in the list
- [x] I should not have to select the "Term" separately from the "Year"
- [x] Dropdown should exist on the About Me tab

**WIREFRAME (updated 6/2/17)**
https://emory.box.com/s/81oqmmp1q1g78czadl2g39z5h0ze7zx2

A sample cvs can be found here: 
https://emory.box.com/s/xmsvfaal2jv2dgwt3uaufe11wsvimtj3

**Comment by shanitajohn** [comment]
Related to Ticket #241

**Comment by jenlindner** [comment]
There is a dropdown for graduation dates built into the UI, but it needs to be populated with the correct data and persisted correctly as well.
