### ISSUE TITLE
Admin stats view raising exception in some cases

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#1934]
The actual error here is `undefined method `gsub' for nil:NilClass`, and it can be traced here:
``` 
NoMethodError: undefined method `gsub' for nil:NilClass
 user.rb  124 to_param(...)
[GEM_ROOT]/gems/hyrax-2.5.1/app/models/concerns/hyrax/user.rb:124:in `to_param'
```
Looks like there is a method being called on a `User` object that involves a `gsub`, which is failing. In the past we have seen this when we have users who don't have an email address or some other expected metadata populated. That would be the first thing I'd check.

[Emory laevigata PROD/production] ActionView::Template::Error: undefined method `gsub' for nil:NilClass

## Backtrace

    line 9 of [PROJECT_ROOT]/config/exception_middleware.rb: call

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/56306/faults/52248859)

**Comment by mark-dce** [comment]
I found a specific date range that triggers the issue which should help us narrow down the issue.  I think this is the issue that Fran/Collin we're reporting in Freshdesk about stats producing an error.

See #1935 for more details.
