### ISSUE TITLE
Filtering stats report produces an error

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1935]
**ISSUE**
When I enter specific filter dates into the "Statistics By Date" report screen, I get a "We're sorry, but something went wrong." error message.

**STEPS TO REPRODUCE**
1. Login to https://etd.library.emory.edu as a user with admin privileges
2. Go to the admin Dashboard
3. Click on [Reports](https://etd.library.emory.edu/admin/stats) under the Activity menu at the left of the dashboard
4. Enter start date `2018-01-01` and end date `2018-08-01` and click the "Load Stats" button - i.e. https://etd.library.emory.edu/admin/stats?utf8=✓&locale=en&stats_filters%5Bstart_date%5D=2018-01-01&stats_filters%5Bend_date%5D=2018-08-01&commit=Load+Stats
5. The page should refresh with 756 results for the selected date range
6. Enter start date `2018-01-01` and end date `2018-09-01` and click the "Load Stats" button - i.e. https://etd.library.emory.edu/admin/stats?utf8=✓&locale=en&stats_filters%5Bstart_date%5D=2018-01-01&stats_filters%5Bend_date%5D=2018-09-01&commit=Load+Stats
7. You will get an error

**DETAILS**
It looks like this may be a missing or corrupt data issue since it appears to happen only when ETDs/users in specific date ranges are included (on production):
* GOOD: 2018-01-01 to 2018-08-19
* BAD: 2018-08-20 to 2018-08-30 **i.e. it looks like there might be bad data with an ETD somewhere between Aug 20-30 2018**
* GOOD 2018-09-01 to 2018-12-15

The related hone badger error can be seen here https://app.honeybadger.io/projects/56306/faults/52248859

NOTE:  There is an associated bug about how hyrax treats missing dates, but that doesn't seem to be the exact issue described above. see https://github.com/samvera/hyrax/issues/1335

**ACCEPTANCE**
- [x] I can enter a date range of 2000-01-01 to 2020-01-01 and get statistics without an error
- [x] I can enter any date subset and get filtered results without errors.

**Comment by little9** [comment]
There was a user without an email address on the production server: 
```
[#<User id: 1140, email: "", created_at: "2018-08-20 18:07:06", updated_at: "2018-08-20 18:07:06", guest: false, facebook_handle: nil, twitter_handle: nil, googleplus_handle: nil, display_name: nil, address: nil, admin_area: nil, department: nil, title: nil, office: nil, chat_id: nil, website: nil, affiliation: nil, telephone: nil, avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, linkedin_handle: nil, orcid: nil, arkivo_token: nil, arkivo_subscription: nil, zotero_token: nil, zotero_userid: nil, provider: "shibboleth", ppid: nil, uid: nil, preferred_locale: nil>]
```

I gave that user the email address `email@example.com` and the error is no longer occurring at any
of those links. 

https://etd.library.emory.edu/admin/stats?utf8=%E2%9C%93&locale=en&stats_filters%5Bstart_date%5D=2018-01-01&stats_filters%5Bend_date%5D=2018-08-01&commit=Load+Stats

**Comment by rotated8** [comment]
Odd. That user [should be impossible to create](https://github.com/curationexperts/laevigata/blob/master/app/models/user.rb#L48). It should at least [have '@emory.edu'](https://github.com/curationexperts/laevigata/blob/master/app/models/user.rb#L52).

**Comment by bess** [comment]
We have seen an issue where sometimes one of the Emory shibboleth servers return an empty hash for an authenticated user, and then that creates an empty `User` object. I wonder if this could be caused by that?

**Comment by mark-dce** [comment]
It looks like there are still a number of users on production that don't have e-mail addresses associated.  Some of them, like `admin_set_owner` are probably OK, but some look like they might be actual submitters.

*on etd.library.emory.edu*
```
irb(main):005:0> u = User.where(email: '')
. . . 
irb(main):006:0> u.each{|user| puts "id: #{user.id}\t email: #{user.email}\t ppid: #{user.ppid}\t created: #{user.created_at}"}
id: 1	 email: 	 ppid: admin_set_owner	 created: 2017-08-18 02:58:23 UTC
id: 2	 email: 	 ppid: notification_owner	 created: 2017-08-18 02:58:23 UTC
id: 286	 email: 	 ppid: audituser@example.com	 created: 2017-12-04 13:30:19 UTC
id: 9	 email: 	 ppid: thairst	 created: 2017-08-18 02:58:27 UTC
id: 15	 email: 	 ppid: ksgarne	 created: 2017-08-18 02:58:32 UTC
id: 149	 email: 	 ppid: P1447951	 created: 2017-10-18 17:57:30 UTC
id: 782	 email: 	 ppid: ltompkins	 created: 2018-04-16 19:14:38 UTC
id: 783	 email: 	 ppid: bshe	 created: 2018-04-17 13:05:54 UTC
id: 1098	 email: 	 ppid: bess	 created: 2018-07-19 17:43:13 UTC
id: 1992	 email: 	 ppid: migration_	 created: 2018-08-28 14:47:30 UTC
id: 7450	 email: 	 ppid: letompk	 created: 2018-10-25 20:11:22 UTC
```

**Comment by mark-dce** [comment]
One or more of these still seem to be associated with an ETD, or we have some other error that results in the same behavior because running the date range 1990-01-01 to 2020-01-01 still produces an error.  e.g. https://etd.library.emory.edu/admin/stats?utf8=✓&locale=en&stats_filters%5Bstart_date%5D=1990-01-01&stats_filters%5Bend_date%5D=2020-01-01&commit=Load+Stats

**Comment by mark-dce** [comment]
**STAGING**
```
irb(main):003:0> nils.sort{|u1, u2| u1.created_at <=> u2.created_at}.each{|u| puts "id: #{u.id}\t ppid: #{u.ppid}\t email: #{u.email}\t created: #{u.created_at}"}
id: 1		 ppid: admin_set_owner	 email: 	 created: 2017-08-18 02:58:23 UTC
id: 2		 ppid: notification_owner email: 	 created: 2017-08-18 02:58:23 UTC
id: 9		 ppid: thairst			 email: 	 created: 2017-08-18 02:58:27 UTC
id: 15		 ppid: ksgarne			 email: 	 created: 2017-08-18 02:58:32 UTC
id: 149		 ppid: P1447951			 email: 	 created: 2017-10-18 17:57:30 UTC
id: 286		 ppid: audituser@example.com email:	 created: 2017-12-04 13:30:19 UTC
id: 782		 ppid: ltompkins		 email: 	 created: 2018-04-16 19:14:38 UTC
id: 783		 ppid: bshe				 email: 	 created: 2018-04-17 13:05:54 UTC
id: 1098	 ppid: bess				 email: 	 created: 2018-07-19 17:43:13 UTC
id: 1140	 ppid: 					 email: 	 created: 2018-08-20 18:07:06 UTC
id: 1992	 ppid: migration_		 email: 	 created: 2018-08-28 14:47:30 UTC
id: 7433	 ppid: zray				 email: 	 created: 2018-10-25 19:38:30 UTC
id: 7435	 ppid: kshann4			 email: 	 created: 2019-02-14 19:00:19 UTC
id: 7436	 ppid: jebail5			 email: 	 created: 2019-02-14 19:00:19 UTC
id: 7437	 ppid: letompk			 email: 	 created: 2019-02-14 19:00:53 UTC
```

**Comment by fpici** [comment]
I recognize two of those ppids as Leah Tompkins, a former RSPH approver: letompk and ltompkins.
For some reason she has two user IDs and she is no longer working ta Emory.

Cheers,

Frances Pici
Scholarly Repository Application Support Analyst
Scholarly Communications Office
Emory University Libraries and Information Technology
Robert W. Woodruff Library
540 Asbury Circle<x-apple-data-detectors://2/1>
Atlanta, GA 30322<x-apple-data-detectors://2/1>
404.727.7673<tel:404.727.7673>
fpici@emory.edu<mailto:%7Cfpici@emory.edu>

Check out our new websites!
Scholarly Communications http://sco.library.emory.edu/index.html
Research Data http://researchdata.emory.edu/index.html

On Jul 16, 2019, at 6:43 PM, Mark Bussey <notifications@github.com<mailto:notifications@github.com>> wrote:

letompk

________________________________

This e-mail message (including any attachments) is for the sole use of
the intended recipient(s) and may contain confidential and privileged
information. If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution
or copying of this message (including any attachments) is strictly
prohibited.

If you have received this message in error, please contact
the sender by reply e-mail message and destroy all copies of the
original message (including attachments).

**Comment by little9** [comment]
What should the approach for this be? Should I assign a stub email address to each of the users without one or should I override the stats code in Hyrax that is trying to use an email address?

**Comment by bess** [comment]
Seems like the stats code in Hyrax shouldn't be using an email address anyway... it should use `User.user_key`, which for this application should be `ppid`. The email address gets added when someone authenticates from shibboleth, so if we created an account for someone ahead of time (e.g., because they were an approver) but they never logged in with that id via shibboleth, that would explain why they never got an email address.

I think the better approach is that the stats module shouldn't rely on an email address existing, since it isn't required for `User` objects in laevigata.

**Comment by little9** [comment]
@mark-dce @bess Like we discussed I added email addresses to any users that were missing them. 

It turned out that the ultimate source of the exception was the blank user mentioned above not having a PPID. After assiging a PPID to the blank user you can run this and it is able to generate the stats key for all the users: 

```ruby
User.all.each { |u| puts "#{u.id} #{u.to_param}" }; 0
```

All of the stats pages are working now.

**Comment by mark-dce** [comment]
Awesome - I'm 99% sure this fixes Fran's fresh desk ticket [112 Intermittant Issue Filtering by Dates ](https://curationexperts.freshdesk.com/a/tickets/112).

@little9 could you run the same update on staging and qa?

**Comment by little9** [comment]
This has been applied to stage and qa as well as prod:
https://staging-etd.library.emory.edu/admin/stats?utf8=%E2%9C%93&locale=en&stats_filters%5Bstart_date%5D=1990-01-01&stats_filters%5Bend_date%5D=&commit=Load+Stats

https://qa-etd.library.emory.edu/admin/stats?utf8=%E2%9C%93&locale=en&stats_filters%5Bstart_date%5D=1990-01-01&stats_filters%5Bend_date%5D=&commit=Load+Stats
