### ISSUE TITLE
Approver Updates

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1940]
There are a number of approver changes requested by Emory.  See the fresh desk ticket for full details https://curationexperts.freshdesk.com/a/tickets/106

**ACCEPTANCE**
- [x] NFERLAN updated
- [x] rfreem2 removed
- [x] letompk removed
- [x] any other changes per fresh desk #106

**Comment by bess** [comment]
I'd like us to use this method for keeping the approvers list in sync across environments from now on: 

https://github.com/curationexperts/laevigata/wiki/How-to-update-ETD-approvers
