### ISSUE TITLE
Timestamp off on Review Submissions Page (Due 11/21)

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#1964]
The timestamp on the Review Submissions page for when the ETD was submitted is  about two hours early. This has an impact on schools who have a submission deadline of midnight.

https://curationexperts.freshdesk.com/a/tickets/117

**Comment by little9** [comment]
rotated8:octocat: 12:32 AM
Looked into the timestamp issue, and I can't reproduce it. I'll ask Fran for more info, but feel free to close the ticket.

**Comment by mark-dce** [comment]
I added a note and closed the ticket in freshdesk
