### ISSUE TITLE
Produce and test workflow for Rollins

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#197]
- [x] Determine (from Fran) whether "reviewed" status should be dropped (yes, it should be)
- [ ] The workflow should implement this diagram:  https://docs.google.com/drawings/d/1E-K0_npXFkM1g2bKwOSID4H0zmBqmWlJ5EUMQK2U2_k/edit
- [ ] The workflow should be auto-populated with approvers and sample submitters
- [ ] The Rollins admin set should be set to use this workflow

**Comment by fpici** [comment]
Hi Bess. I sent emails to Candler, Rollins, and College Honors Admins on 5.17morning. So far, 2 of the 3 have replied and as soon as Rollins answers, we will know how to proceed. See below email:  "With the rebuild we have an opportunity to streamline the review and approval process and want to know if you and your ADAPs use the “reviewed” status queue? In other words, do you have a process where an ADAP needs to have a record sitting in the “reviewed status queue” before it is “approved?” If not, we can eliminate that step and the ADAP can move directly from the “submitted queue” to “accept or request changes” to the “approved queue.”
 Cheers, fran
