### ISSUE TITLE
Add Max to DCE hosting AWS

### ISSUE THREAD

**Issue by maxkadel** [curationexperts/laevigata#1974]
Bess tried, and it didn't work for some reason

**Comment by mark-dce** [comment]
Are we trying to get Max's primary IAM id from the curationexperts organization to have access to DCE Hosting or Emory Hosting organizations, or both?  (I ask because this ticket is in the laeviagata repo)

**Comment by maxkadel** [comment]
Both, please, should have been created under "in-house," my mistake.
