### ISSUE TITLE
Restrict access to etd-staging and -qa (Due 12/18)

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#1976]
Via freshdesk:

We are concerned that ETD records in QA and Staging site are searchable in Google. We have handled at least three Alumni tickets who have contact us when ever their embargoed record in Production shows up in a Google search on the QA and/or Staging site URL. Can we confirm if there is a robots.txt in place or other measures to stop Google indexing QA and Staging? Please let me know if you need other information or if discussing this in our regular meeting would help. Thanks -Doug

https://curationexperts.freshdesk.com/a/tickets/121

**ACCEPTANCE**
- [ ] Research at least 3 potential solutions
- [ ] Document pros & cons of each solution in the comments on this ticket
- [x] Select an option and implement it

**Comment by mark-dce** [comment]
Here's some useful background:
https://searchengineland.com/how-to-keep-staging-development-site-index-286987
https://support.google.com/webmasters/answer/93710?hl=en
https://yoast.com/prevent-site-being-indexed/

Please test the selected solution on tenejo-stage before implementing on any of the etd servers.

**Comment by mark-dce** [comment]
This post seems to have some useful code snippets for different authentication and authorization strategies at the Apache level - we may just want to put a static password file or IP restrictions on the apache server _in front of_ any application-level login - i.e. you have to make the request from a known IP or enter an apache username and password before you get to the rails application which then still requires Shibbloleth level authentication to access non-public resources.

http://www.yolinux.com/TUTORIALS/LinuxTutorialApacheAddingLoginSiteProtection.html

**Comment by bess** [comment]
![password.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/90bff8f4-dca8-41b7-8182-00029634e000)
