### ISSUE TITLE
SSL certs will expire 9 May

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#1990]
SSL certs on ETD servers have let us know they'll expire in three months. I have asked @SolomonHD to generate new certs and we can install those as soon as we have them. 

![ssl_expiration.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/c75e95c4-1cc7-4ee4-b737-5b98beebf911)

ACCEPTANCE CRITERIA
- [x] certs are replaced and this warning has gone away
- [x] the process for replacing the certs is documented so someone other than Bess can do this next time. Documentation started here: https://github.com/curationexperts/laevigata/wiki/Update-SSL-certs

**Comment by RachelDCE** [comment]
Per 3/19 Hosting Status meeting: 

Doug will check in with Solomon and Collin on process to get new SSL certs issued.  We’re targeting having new certificates by Friday, April 24th.  This gives us two working weeks to get them applied before the current certificates expire.

**Comment by bess** [comment]
We now have updated SSL certs for the ETD application. The certs are attached to the freshdesk ticket, here: https://curationexperts.freshdesk.com/a/tickets/129
Note that the current certs expire on 9 May, so this work MUST happen before then.

- [ ] Put new certs in place and ensure they are working properly 
- [ ] Nagios alerts for SSL expiration should turn green after these are in place

**Comment by bess** [comment]
The SSL certs we were given do not appear to work. When I install them, apache won't restart. 

![Screen Shot 2020-04-10 at 11.18.36 AM.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/f80b1aa9-b8fa-4422-a07e-e1a99dacc891)

I am talking to Doug about it and he's going to check in with the Middleware team about how these certs usually get generated:

![Screen Shot 2020-04-10 at 11.12.43 AM.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/e0c5c28e-7eec-43f6-a910-ed1a777c6f5c)

**Comment by bess** [comment]
They expect to get us an updated cert on Monday.

**Comment by bess** [comment]
Done!
