### ISSUE TITLE
ETD States of Review

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#200]
As Queen, a school reviewer for Laney Graduate School, while reviewing an ETD, I would like to be able to change its status to show that it is in one of six states of review. I want to do this so that I can easily tell what work has been done and what needs to happen next. 

**ACCEPTANCE CRITERIA**
- [ ] I can set an ETD to have the status "Inactive"
- [ ] In the Inactive state it is available to SCO Staff or a software engineer.
- [ ] I can set an ETD to have the status "Draft" 
- [ ] In the Draft state a student should be able to make edits to it 
- [ ] In the Submitted state neither the student nor reviewer can make edits

Reviewed 
Approved
Published

**Comment by shanitajohn** [comment]
@bess I opened this ticket a month back but didn't finish writing it because I didn't understand all the states an ETD could be in. Since then, I believe this work has been completed in the single and 2-step workflows. Can you confirm? Then I'll close it.

**Comment by bess** [comment]
We don't have a workflow status called "draft", but I think the functionality that is being described is present. If someone hasn't submitted their ETD yet, they can save it and come back to it. And if they have submitted it and it needs to be sent back for revisions Queen can send it back with a comment and the student can edit it. I think we should close this ticket.
