### ISSUE TITLE
Update Process for handling large file attachments in ETDs

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts/laevigata#2000]
Freshdesk ticket # 130 - **ETD: Broken function - Link to Box to add supplemental files is broken **
Status: Open
15 Apr 2020, 11:39 AM

Doug Goans reported via the portal, 5 hours ago:
 
Kylie is reporting the following issue. Please advise on any next steps or other info we can provide. Thanks -Doug
.....
I have been trying to get this video uploaded to this students submission for most of the morning. The file is over 900MB. I’ve tried adding it to her submission through box (as we are supposed to be able to do with larger files) but something is wrong with the ETD link to box. When I click the “Add supplemental file from Box” tab it takes me to a screen to grant access to box, but when I click the “grant access” button, it takes me right back to the submission form with no change to the file selection options – it’s supposed to create a link to box so you can select the file. I tested the system in February when DCE was releasing v2.5.3 and it worked correctly. Not sure why it’s not working now, but am open to suggestions.
 
~Kylie
 
 
 
> Form Name: ETD Help Form
> Submitted: Apr 14, 2020 04:53 PM
> Report link: https://emory.libwizard.com/forms/reports/9baa5e7aa513921e376116bbfe23b665
> Full Name:
> Samah Meghjee
> 
> EmailYour email address, so ETD staff can follow up with you (please use an Emory email address if you have one).:
> samah.meghjee@emory.edu
> 
> Graduation DateExpected graduation date (for students submitting an ETD).:
> 05/11/2020
> 
> SubjectBrief description of your question or request.:
> Unable to upload additional document.
> 
> MessageFull details of your question or request. Please be as descriptive as possible.:
> I completed a film production thesis and am unable to upload the film to ETD because it is above 100MB, and my attempts to upload it using Box have been unsuccessful. Here is the video: https://app.box.com/s/ucljb8aeqcbzriww6lwfcqrnytcuxhs8

**Comment by bess** [comment]
I have manually attached the file to the ETD in question, here: https://etd.library.emory.edu/concern/etds/9w0324248?locale=en

I also wrote up a guide in case anyone else needs to do this in the future: https://github.com/curationexperts/laevigata/wiki/How-to-manually-attach-a-file-to-an-ETD

Next I'm going to try to figure out why the box.com link isn't working.

**Comment by RachelDCE** [comment]
At our Monthly DCE/Emory ETD Check-in we reported the following to client:

**Freshdesk #130 ETD: Broken function - Link to Box to add supplemental files is broken**

- Interim solution - DCE can manually attach files 

- We will have a long-term solution for this by Fall submission

**Comment by RachelDCE** [comment]
Outcome of 2020-05-21 meeting:

Until we have the long-term solution, Emory will make a Freshdesk ticket for each ETD that needs to have large files attached and attach any such files to the ticket.

**Comment by mark-dce** [comment]
We've been getting a very small number of requests of this type annually and have been able to handle them based on the instructions posted in the WIKI, so no further action is required on this issue.

WIKI Instructions for attaching a large file:
https://github.com/curationexperts/laevigata/wiki/How-to-manually-attach-a-file-to-an-ETD
