### ISSUE TITLE
Investigate derivatives error

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#2002]
On Friday April 24 ETD production experienced two minutes of recorded downtime because a create derivatives job was using so much CPU the system couldn't respond to requests. The error messages were:

```
{"_aj_globalid"=>"gid://laevigata/FileSet/mk61rh69c"}, "mk61rh69c/files/530d1eea-a1f4-4edc-8ab7-298b1d7bb352", "/opt/uploads/hyrax/uploaded_file/file/26732/SreenathShreyasDissertation-Final.pdf"
```
```
MiniMagick::Invalid: `magick identify /tmp/mini_magick20200424-1367-129soo7.pdf` failed with error: **** Warning: considering '0000000000 XXXXX n' as a free entry. **** Warning: considering '0000...
```

This is an exception we've hit before: 

https://app.honeybadger.io/projects/56306/faults/61913557

However, this was the first time I've seen this exception bring the box down. We should catch this exception so this doesn't happen again.

**Comment by bess** [comment]
Update: The ETD referenced in this error looks like it is fine. I was able to download and open the PDF. The only ill-effect I can see is the lack of a thumbnail image, and I don't think that's worth bothering the student over.

**Comment by mark-dce** [comment]
Unable to replicate at this time.
