### ISSUE TITLE
Update Graduation Job to handle non-embargoed works correctly

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#2027]
**ISSUE**
The Graduation Job that is run to process Registrar data does not handle open access works correctly in some cases, leaving them in a state where the ETD is accessible as expected, but with an indication that files are restricted (when they are not).

- [ ] Fix existing incorrectly set embargos (Potentially resolves https://curationexperts.freshdesk.com/a/tickets/133)

**ACCEPTANCE**
- [ ] When the graduation job is run, open access works a processed successfully

**SEE ALSO**
Embargo visibility is not set correctly on newly created and submitted ETDs #2065 

**PLAN**
- [x] Update the Graduation Job to address the issue
- [ ] Test the updated job on qa with the Spring 2020 Registrar data - fix any issue encountered
- [ ] Run the updated Graduation Job on staging
- [ ] Run the updated Graduation Job on production (Wed 7/22)

**Comment by fnibbit** [comment]
https://app.honeybadger.io/projects/54217/faults/65909990 Error updating embargo release date on nonexistent embargos while running on qa.

**Comment by maxkadel** [comment]
Fixed by work on ticket #2065
