### ISSUE TITLE
Restrict Approvers from extending embargo

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#2028]
**STORY**
Emory has identified at least one department-level approver who can extend embargo expirations.  That capability should be restricted to super-admins.

**ACCEPTANCE**
- [ ] Only SuperAdmins can extend embargo dates
- [ ] Departmental approvers and others cannot modify embargo dates

**ADDITIONAL DETAIL**
See Freshdesk [131](https://curationexperts.freshdesk.com/a/tickets/131)
Rollins ADAP who is able to make embargo changes & the links to the records for which she was able to extend embargoes
Farah Dharamshi: fdharam
https://etd.library.emory.edu/concern/etds/ww72bb53h?locale=en
https://etd.library.emory.edu/concern/etds/4x51hj066?locale=en
https://etd.library.emory.edu/concern/etds/9k41zf17q?locale=en (embargo expired)
https://etd.library.emory.edu/concern/etds/df65v8733?locale=en

<img width="900" alt="image" src="https://user-images.githubusercontent.com/3064318/87705176-208ca780-c763-11ea-9aad-a12f2bddba43.png">

**Comment by RachelDCE** [comment]
Spec/system/embargo_edit_spec.rb has an "approver can change embargo" test

**Comment by fnibbit** [comment]
And that test has existed since August 2018 (previously in spec/features/embargo_edit_spec.rb).  Is this a bug or a change in requirements?

**Comment by maxkadel** [comment]
It appears that the ability for approvers to be able to edit / manage embargoes has been there from the beginning of this application, from the "Manage Embargoes" screen. What is the desired behavior?

- No link to to the "Manage Embargoes" interface at all for approvers? 
- Allow approvers to see a "read only" version of the "Manage Embargoes" interface?
  - If so, the current title links need to behave differently - either remove link entirely, or have it go to a different view of the ETD in question (currently goes to an embargo edit screen)
- What should the message be to approvers who try to manage embargoes? At what point in the process should it come up? 

@mark-dce

**Comment by maxkadel** [comment]
Notes on attempting to update this property - https://docs.google.com/document/d/1N-D6MIZ8m4WKE0nCDn1ghpeO_K2lZXMjSnyDWETjWc8/edit

**Comment by mark-dce** [comment]
Let's proceed with the path of no link to "Manage Embargos" for approvers and restrict access to the "Manage Embargos" controller to SuperAdmins.

Approvers Will still be able to see the Embargo information on the primary work view: 
![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/8ae9569a-4a24-498e-9123-4c16066a31f1)
