### ISSUE TITLE
Remove automated runs of the graduation job

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#2038]
At one time we thought we'd be getting automated uploads of Emory registrar data, and we set up the graduation job to run automatically. We never started getting those automated data uploads, and instead we've moved to a manual system for running the registrar data. However, we still have the automated runs of the graduation job in place. 

See https://github.com/curationexperts/laevigata/blob/master/config/schedule.rb#L24-L26

- [ ] Remove the graduation job from the automated job runs

**Comment by mark-dce** [comment]
From @fnibbit 

The "Cron jobs in production" section plus this section of config/schedule.rb:

>  # Weekly, check whether students have graduated and kick off
> # graduation jobs if so
> every :monday, at: '12:20am' do
>   rake "emory:graduation"
> end
together suggest that the running of the graduation job is more automatic than I think it is.

**Comment by mark-dce** [comment]
The crontab changes implemented via the [whenever gem](https://github.com/javan/whenever#capistrano-integration) will take place during the next deploy via Capistrano.

I also updated the project README to remove references to obsolete cron jobs.

**Comment by fnibbit** [comment]
rachel k will deploy to qa to confirm

**Comment by fnibbit** [comment]
crontab -l
SHELL="/bin/sh"
PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"

# Begin Whenever generated tasks for: laevigata at: 2021-02-26 16:22:47 -0500
55 23 * * * /bin/bash -l -c 'cd /opt/laevigata/releases/20210226212119 && RAILS_ENV=production bundle exec rake emory:proquest_notifications --silent'

20 2 * * * /bin/bash -l -c 'cd /opt/laevigata/releases/20210226212119 && RAILS_ENV=production bundle exec rake emory:embargo_expiration --silent'

55 23 * * * /bin/bash -l -c 'cd /opt/laevigata/releases/20210226212119 && RAILS_ENV=production bundle exec rake blacklight:delete_old_searches[1] --silent'

0 1 * * * /bin/bash -l -c '/usr/bin/find /tmp -type f -mtime +7 -user deploy -execdir /bin/rm -- {} \;'

# End Whenever generated tasks for: laevigata at: 2021-02-26 16:22:47 -0500
