### ISSUE TITLE
From Freshdesk: ETD Data Dump

### ISSUE THREAD

**Issue by maxkadel** [curationexperts/laevigata#2042]
https://curationexperts.freshdesk.com/a/tickets/135

From 8/4/2020
We are requesting our annual data dump of Emory ETDs. Please let us know if we can provide any other info. Thanks -Doug

From 8/11/2020
Hello. Checking to see if it would be possible to get the data dump this week or early next week? We have a service request from one of the colleges that the data would help Jody and Kylie fill. Please let me know what you think or if you need more info. Thanks -Doug

8/14 More info via Jody on slack: 
This is the actual request they're trying to fulfill:
“I wanted to check in to see if there was a report that could be pulled of all ETD deposits for RSPH that could include student name, semester of graduation, thesis title, and faculty advisor and committee members. Some of our departments provide salary support for thesis and we want to make sure we have the most accurate records. It would be great to have Fall 19, Spring 20, and Summer 20.” (edited)

**Comment by bess** [comment]
This is the actual request they're trying to fulfill: 
“I wanted to check in to see if there was a report that could be pulled of all ETD deposits for RSPH that could include student name, semester of graduation, thesis title, and faculty advisor and committee members. Some of our departments provide salary support for thesis and we want to make sure we have the most accurate records. It would be great to have Fall 19, Spring 20, and Summer 20.” (edited)
