### ISSUE TITLE
Capture more detail when systems are rebooted by Nagios

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts/laevigata#2043]
**STORY**
There is an ETD reboot script on panopticon at /usr/local/nagios/libexec/event_handlers/restart-prod-etd. Unfortunately, it gives us minimal information about when and why the reboot event occurred.

**ACCCEPTANCE**

- [ ] The script should capture the state of the system console before reboot, see https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/get-console-screenshot.html
- [ ] The script should capture the most recent console output as text (in case services failed before logs were successfully forwarded to Splunk)
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/get-console-output.html
- [ ] The script should capture the system status BEFORE reboot, see https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/monitoring-system-instance-status-check.html#viewing_status
- [ ] The script should log when it has been run
- [ ] The script should log when it reboots a server
- [ ] The location of those log files is recorded on the wiki page for Panopticon

**Comment by mark-dce** [comment]
Nagios is no longer in use.
