### ISSUE TITLE
What format does ProQuest need the permanent address in?

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#205]

**Comment by fpici** [comment]
Hi Shanita. Based on what I learned from ProQuest, we still need to collect addresses and send them as part of the package we FTP. ProQuest needs an address in order to send any royalties, etc. I have a question out to Proquest about formatting just in case the "FTP package" response is not enough.

**Comment by fpici** [comment]
Hi Shanita. Here is a snippet of the permanent address formatting that Proquest just sent to me:

From Lewis: "I’ve attached one of the recent XML files we received from Emory University. We are hoping that the addresses will remain formatted the same as they are currently, moving forward. Here is the section in question, pasted from the XML itself:"
 
  <DISS_authorship>
    <DISS_author type="primary">
      <DISS_name>
     <DISS_surname>Thorstad</DISS_surname>
     <DISS_fname>Robert</DISS_fname>
     <DISS_middle/>
     <DISS_suffix/>
     <DISS_affiliation>Psychology</DISS_affiliation>
      </DISS_name>
      <DISS_contact type="current">
     <DISS_contact_effdt>08/22/2016</DISS_contact_effdt>
     <DISS_phone_fax type="P">
       <DISS_cntry_cd></DISS_cntry_cd><DISS_area_code>610</DISS_area_code><DISS_phone_num>348-6680</DISS_phone_num><DISS_phone_ext/>
     </DISS_phone_fax>
     <DISS_address>
       <DISS_addrline>1659 Briarcliff Rd NE, Apt 1105B</DISS_addrline><DISS_city>Atlanta</DISS_city><DISS_st>GA</DISS_st><DISS_pcode>30306</DISS_pcode><DISS_country>US</DISS_country>
     </DISS_address>
     <DISS_email>rthorst@emory.edu</DISS_email>
      </DISS_contact>
      <DISS_contact type="future">
     <DISS_contact_effdt>01/01/2019</DISS_contact_effdt>
     <DISS_phone_fax type="P">
       <DISS_cntry_cd></DISS_cntry_cd><DISS_area_code>610</DISS_area_code><DISS_phone_num>348-6680</DISS_phone_num><DISS_phone_ext/>
     </DISS_phone_fax>
     <DISS_address>
       <DISS_addrline>1659 Briarcliff Rd NE, Apt 1105B</DISS_addrline><DISS_city>Atlanta</DISS_city><DISS_st>GA</DISS_st><DISS_pcode>30306</DISS_pcode><DISS_country>US</DISS_country>
     </DISS_address>
     <DISS_email>thorstadrs@gmail.com</DISS_email>
      </DISS_contact>
    </DISS_author>
  </DISS_authorship>

**Comment by shanitajohn** [comment]
Thanks, Fran! I'm going to add @bess and @rotated8 to this ticket and ask that they take the next step of turning this ticket into a development task to complete the work, before closing this out.

**Comment by shanitajohn** [comment]
Related to #176

**Comment by shanitajohn** [comment]
We have this XML from Buddy, closing this ticket.
