### ISSUE TITLE
Does the school reviewer or super admin need to the student's current or permanent address or phone?

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#206]
Does the school reviewer or super admin need to the student's current or permanent address or phone?

**Comment by fpici** [comment]
Hi Shanita. There is really no need for the school reviewer or super admin  to have the student's current address or phone. This is information that is better stored in the University directory while they are a student. The student's permanent address will need to be stored for Proquest to contact students (see Ticket #44) and the student's NON-Emory email address will also need to be stored for after-graduation communications. Let me know if this answer helps. :-) fran

**Comment by shanitajohn** [comment]
Just double checking. The permanent address was displayed on a screen to the superadmin in the PDF walkthrough so I wanted to be certain we didn't need that pulled in. Thank you!

**Comment by fpici** [comment]
Hi Shanita. The Superadmin has no need for the student's current or permanent address BUT 
the student's permanent address will need to be stored for Proquest to contact students (see ticket #44). Hope this helps ya!
