### ISSUE TITLE
Update ETD Supplemental File upload option

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts/laevigata#2069]
As a interim fix to Freshdesk #130 ETD: Broken function - Link to Box to add supplemental files is broken
https://curationexperts.freshdesk.com/a/tickets/130

DCE will:

- [x] Determine threshold for size of supplemental file
- [x] Remove “Add file from Box” options for primary and secondary files 
- [x] Add with the following verbiage in place of the box upload option:
     >Please contact [Emory’s Scholarly Communications Office](http://sco.library.emory.edu/etds/help-form.html) if you have a supplemental file over (insert threshold size here) for assistance with uploading your file(s).

**Comment by fnibbit** [comment]
![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/dab415cb-9e02-42d6-bce2-74b7ac70e6ee)

**Comment by fnibbit** [comment]
https://github.com/curationexperts/laevigata/pull/2078

**Comment by RachelDCE** [comment]
Updated on QA.
