### ISSUE TITLE
Fix availability issues

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#2083]
**ISSUE**
Some ETDs display as "Published" but do not display content and show the following error message:
"The work is not currently available because it has not yet completed the publishing process"

**EXAMPLES**
* Evaluation of Emory Healthy Kitchen Collaborative (EHKC) as a Worksite Wellness Program (http://etd.library.emory.edu/concern/etds/9s1617348) deposited by Krystyna Rastorguieva
* Food Flows to Assess Community Exposure to Escherichia Coli O157:H7 in Romaine Lettuce (http://etd.library.emory.edu/concern/etds/ns0647074) deposited by Thomas Burke

See Freshdesk # 145 https://curationexperts.freshdesk.com/a/tickets/145  for additional examples.  

**ACCEPTANCE**
- [ ] Identify the root cause of the issue and resolve it so that it does not recur for new ETDs
- [x] Generate a complete list of existing ETDs with the issue - i.e. the problem may extend back further than the fresh desk ticket.
- [ ] Resolve the issue for existing ETDs

**Comment by mark-dce** [comment]
To fix this as a one-off, the following code can be run from the console
```
e = Etd.find('hq37vp71n')
e.embargo_release_date = Time.now + 1.day
e.embargo.save
#or e.embargo.delete!
e.reload
e.state = ::RDF::URI('http://fedora.info/definitions/1/0/access/ObjState#active')
e.save!
```

**Comment by fnibbit** [comment]
solr/laevigata/select?fl=id,system_create_dtsi,system_modified_dtsi,title_tesim,graduation_year_tesim,files_embargoed_bsi,abstract_embargoed_bsi,toc_embargoed_bsi,embargo_length_ssm,suppressed_bsi,hidden?_bsi,workflow_state_name_ssim,visibility_ssi&indent=on&q=has_model_ssim:"Etd"%20AND%20workflow_state_name_ssim:"published"%20AND%20suppressed_bsi:true&rows=100&wt=csv  against qa and staging both show 6q182m12q "Applying Public Health Informatics to Explore Emerging Technologies  In Systematic Data Reconciliation " as the earliest record with suppressed_bsi true and workflow_state_name_ssim "published", with a system_modified_dtsi of 2019-11-16.

**Comment by mark-dce** [comment]
Writing up a draft diagnostics doc for testing and tracking here https://docs.google.com/document/d/1SjRtcQHJNQfGaNV6tCQNGSuPILUxMguRRDqdrEmk5HM/edit
