### ISSUE TITLE
Review and update README

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#2084]
**ISSUE**
We've recently updated the ruby version and other dependencies in the repo and should update the readme to reflect ruby 2.7.2 and any other relevant changes.

**ACCEPTANCE**
- [x] Two team members have reviewed the README and made any appropriate updates

**Comment by fnibbit** [comment]
The "Cron jobs in production" section plus this section of config/schedule.rb:

>  # Weekly, check whether students have graduated and kick off
> # graduation jobs if so
> every :monday, at: '12:20am' do
>   rake "emory:graduation"
> end
together suggest that the running of the graduation job is more automatic than I think it is.

**Comment by fnibbit** [comment]
https://github.com/curationexperts/laevigata/pull/2085
