### ISSUE TITLE
Command prompt should show hostname instead of IP

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#209]
**STORY**
As a systems administrator, I would like the command prompt to show the hostname instead of the IP address of the box, so that I can easily distinguish what system I'm connected to

**CURRENT BEHAVIOR**
```
mark@ip-10-0-0-99:/opt/laevigata/current$ grep -r queue_adapter config
config/application.rb:    config.active_job.queue_adapter = :inline
```

```
mark@ip-10-0-0-216:/opt/laevigata/current$ grep -r queue_adapter config
config/application.rb:    config.active_job.queue_adapter = :inline
```

**EXPECTED BEHAVIOR**
```
mark@emory:/opt/laevigata/current$ grep -r queue_adapter config
config/application.rb:    config.active_job.queue_adapter = :inline
```

```
mark@emory-stress-test:/opt/laevigata/current$ grep -r queue_adapter config
config/application.rb:    config.active_job.queue_adapter = :inline
```

**ACCEPTANCE**
- [x] Servers on AWS display their primary DNS hostname in the command prompt when one is assigned.

**Comment by acozine** [comment]
Looks like the prompt is showing the hostname, but the hostname has not been correctly reset on AWS boxes. I need to make the ansible task that sets the hostname work with the 16.04 parameters, see http://manpages.ubuntu.com/manpages/xenial/man1/hostnamectl.1.html

**Comment by acozine** [comment]
I've made the change on the existing sandbox servers and will open a ticket on the Ansible side to make sure the change gets implemented upstream so new servers get built with this set correctly.
