### ISSUE TITLE
ETD: Attributes graduation_date and graduation_year are being stored as the same predicate in Fedora

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#2090]
**ISSUE**
Two attributes are using the same predicate:
```
W, [2021-02-24T20:01:54.006580 #962]  WARN -- : Same predicate (http://purl.org/dc/terms/issued) used for properties graduation_date and graduation_year
```

This means values stored to `graduation_date` will overwrite values stored for `graduation_year`.  Both attributes occur in multiple locations throughout the codebase and it's not clear if they support the same or different functions.

OPTION 1:
Do nothing - this leaves the code and the data in a opaque state that's difficult to reason about because changes to `graduation_date` might impact logic intended for `graduation_year` etc.

OPTION 2:
Assign one attribute a new predicate and re-index the data.  This works if there aren't any hidden dependencies on the two fields having identical values.

OPTION 3:
Rename `graduation_date` & `graduation_year` to `graduation_term` since this appears to be the type of value in the field (see screenshot at bottom)

**OPTION 4:**
Separate graduation_semester and graduation_year and index them as a new field year+semester for the facet

**ACCEPTANCE**
- [ ] We no longer get the "same predicate" warning

<img width="1132" alt="image" src="https://user-images.githubusercontent.com/3064318/109093777-c3c87680-76cd-11eb-9252-cd28fd1d2a81.png">

<img width="1406" alt="image" src="https://user-images.githubusercontent.com/3064318/109093959-1a35b500-76ce-11eb-9712-80348e3c6109.png">

**Comment by maxkadel** [comment]
So, http://purl.org/dc/terms/issued is supposed to be a valid ISO 8601 date, but we're currently using strings for both graduation_year and graduation_date. It looks like we also have mixed / inconsistent data in the "Year" facet 

![image](https://user-images.githubusercontent.com/45948126/109314161-021d7d00-7817-11eb-837a-2dd565c7a78e.png)


OK, newsflash, y'all! ISO 8601 allows for expression of seasons as YYYYSS
```
21-24 = Spring, Summer, Autumn, Winter, independent of “Hemisphere”
25-28 =	Spring - Northern Hemisphere, Summer - Northern Hemisphere, Autumn - Northern Hemisphere, Winter	- Northern Hemisphere
```

So I'm thinking translate the registrar data into a valid date with northern hemisphere season and call that graduation_term and give it the predicate, and then for when we want only the year, we can parse that from the graduation_term?

**Comment by mark-dce** [comment]
Would it make sense to use a different predicate that didn't imply it was an ISO date?  That would have the advantage of letting us implement, index, and validate the new term while leaving the old data in place.

**Comment by fnibbit** [comment]
Where/when do we see these predicate warnings?

**Comment by mark-dce** [comment]
I know I get them consistently when I run the graduation job.  Maybe try the specs for the graduation job and see if you see it there; otherwise, you can run and re-run the graduation job with the same registrar data and the warning should show up even when there are no new works to graduate.

**Comment by mark-dce** [comment]
To be more precise, you should see these error in the production log.  I know that they occur when running the graduation job.  I suspect that they occur when restarting the application after deployment as well - so they might show up when launching the application server locally too.

Here's a snippet of the log after starting the graduation job:
```
tail -f /opt/laevigata/current/log/production.log
W, [2021-03-12T12:36:23.935730 #13601]  WARN -- : Same predicate (http://purl.org/dc/elements/1.1/subject) used for properties research_field and subject
W, [2021-03-12T12:36:23.968682 #13601]  WARN -- : Same predicate (http://purl.org/dc/terms/issued) used for properties graduation_year and graduation_date
W, [2021-03-12T12:36:23.968770 #13601]  WARN -- : Same predicate (http://purl.org/dc/terms/issued) used for properties graduation_date and graduation_date
W, [2021-03-12T12:52:06.742167 #14146]  WARN -- : Same predicate (http://purl.org/dc/terms/issued) used for properties graduation_year and graduation_date
W, [2021-03-12T12:52:06.791894 #14146]  WARN -- : Same predicate (http://purl.org/dc/elements/1.1/subject) used for properties research_field and subject
W, [2021-03-12T12:52:06.824715 #14146]  WARN -- : Same predicate (http://purl.org/dc/terms/issued) used for properties graduation_year and graduation_date
W, [2021-03-12T12:52:06.824808 #14146]  WARN -- : Same predicate (http://purl.org/dc/terms/issued) used for properties graduation_date and graduation_date
W, [2021-03-12T12:52:11.175922 #14146]  WARN -- : Running GraduationService with file /opt/laevigata/current/config/emory/registrar_data_20201005.json
W, [2021-03-12T12:52:11.176076 #14146]  WARN -- : Graduation service: Running graduation service with file /opt/laevigata/current/config/emory/registrar_data_20201005.json
W, [2021-03-12T12:52:11.176173 #14146]  WARN -- : Graduation service: found registrar data
```

**Comment by mark-dce** [comment]
property graduation_semester --> [seasonNumber](https://github.com/ruby-rdf/rdf-vocab/blob/3.2.1/lib/rdf/vocab/ebucore.rb#L5511) -OR- [artefactPeriod](https://github.com/ruby-rdf/rdf-vocab/blob/3.2.1/lib/rdf/vocab/ebucore.rb#L1646) -OR- [code](https://github.com/ruby-rdf/rdf-vocab/blob/3.2.1/lib/rdf/vocab/bf2.rb#L1319-L1325) -OR- [temporalCoverage](https://github.com/ruby-rdf/rdf-vocab/blob/3.2.1/lib/rdf/vocab/bf2.rb#L2571-L2577) -OR-  [occurredAt](https://github.com/ruby-rdf/rdf-vocab/blob/3.2.1/lib/rdf/vocab/edm.rb#L338-L345) -OR- [DC:issued](https://github.com/ruby-rdf/rdf-vocab/blob/3.2.1/lib/rdf/vocab/dc.rb#L445-L453)
property graduation_year --> [EDM:year](https://github.com/ruby-rdf/rdf-vocab/blob/3.2.1/lib/rdf/vocab/edm.rb#L338-L345) -OR- [BF2:date](https://github.com/ruby-rdf/rdf-vocab/blob/3.2.1/lib/rdf/vocab/dc.rb#L445-L453)

**Comment by mark-dce** [comment]
provisional plan:
1. Leave graduation_date in place to access existing data
2. Add graduation_year and graduation_semester properties; add index value for graudation_date + graduation_year
3. Update input form to separate out year from semester (to handle newly submitted ETDs)
4. Iterate over all ETDs to populate graduation_year and graduation_semester from existing graduation_date field
5. [Optional] remove graduation_date field
6 [Optional] reindex to remove buggy graduation_date

*ALTERNATE 1*
1. Replace all references to graduation_date with graduation year
2. Live with existing funky data - e.g. graduation_year = "Fall 2021"

*ALTERNATE 2*
1. Replace all references to graduation_date with graduation year
2. Update the controlled vocab to use "2020 Fall" instead of "Fall 2020" - https://github.com/curationexperts/laevigata/blob/v2.12.0/config/authorities/graduation_dates.yml
3. Re-index everything to reflect the change

**Comment by mark-dce** [comment]
BEFORE (.json view)
```
  "graduation_year": "Fall 2021",
...
  "graduation_date": [
    "Fall 2021"
  ],
...
  "degree_awarded": "2022-01-11T00:00:00.000+00:00",
```

AFTER
```
  "graduation_date": "Fall 2021",
  "degree_awarded": "2022-01-11T00:00:00.000+00:00",
```
