### ISSUE TITLE
Configure authentication to Emory shibboleth

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#210]
- [x] Be able to authenticate to Emory shibboleth and retrieve ppid, netid, and name

**Comment by acozine** [comment]
Our application now retrieves two attributes (uid and mail) from the DCE test Shibboleth server on the emory-stress-test machine. Next steps are:
- [ ] install and configure an SP on emory.curationexperts.com
- [ ] create users in the test ldap with ppid, netid, and name in their records
- [ ] update the code and config to pass those fields from the DCE test shibboleth server
- [ ] review the users created on emory.curationexperts.com from the DCE test shibboleth server
- [ ] send the emory.curationexperts.com metadata to Gerry Hall for addition to the Emory Shibboleth system
- [ ] change the SP on emory.curationexperts.com to connect to the Emory shibboleth server
- [ ] confirm that real Emory users can log into emory.curationexperts.com with their Emory NetIDs and create local user records with the data laevigata needs

**Comment by acozine** [comment]
For each field we want to retrieve from the Emory Shibboleth IDP, we need to know (from the field's Attribute Definition):
- [ ] the `id`
- [ ] the `xsi:type`
- [ ] the `sourceAttributeID`
- [ ] the `name` from the SAML2 AttributeEncoder (may look like `urn:oid:0.9.2342.19200300.100.1.`)
- [ ] the `encodeType` from the SAML2 AttributeEncoder

**Comment by acozine** [comment]
To make `ppid` a valid field in our LDAP server, it looks like we may need to add the CardSpace schema - see https://stackoverflow.com/questions/765273/modifying-ldap-schema-to-support-cardspace-and-openid

**Comment by acozine** [comment]
Here's where we are EOD Friday. The `emory_shib` branch is deployed on emory-stress-test. It provides functioning user authentication and creates new user records in the laevigata database from the Emory Shibboleth server, with `ppid` and `name`. However the `uid` field is still coming back `nil` - see https://gist.github.com/acozine/f997e34a073c5225c875b2c87d690fb7.

Also, the test for user creation is failing on the branch. I don't know how to fix the failing part, which tests what happens when a user logs out and back in again.
```
 1) User signing in twice finds the original account instead of trying to make a new one

     Failure/Error:
       where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
         user.ppid = auth.info.ppid
         user.uid = auth.info.uid
         user.display_name = auth.info.name
       end
     ActiveRecord::RecordNotUnique:
       SQLite3::ConstraintException: UNIQUE constraint failed: users.email: INSERT INTO "users" ("created_at", "updated_at", "display_name", "provider", "ppid") VALUES (?, ?, ?, ?, ?)
     # ./app/models/user.rb:27:in `from_omniauth'
     # ./spec/models/user_spec.rb:27:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # SQLite3::ConstraintException:
     #   UNIQUE constraint failed: users.email
     #   ./app/models/user.rb:27:in `from_omniauth'
Finished in 3 minutes 44.4 seconds (files took 14.42 seconds to load)
145 examples, 1 failure, 5 pending
```
I suspect we should use `ppid` as the unique field instead of `email` but I don't know where to set that.

**Comment by acozine** [comment]
Code changes in #400. 
Both sandbox servers are now set up to receive AuthN from Emory's Shibboleth server, and user creation works correctly. To create a superuser, you must now add that user's `ppid` to the `config/emory/superusers.yml` file and run `RAILS_ENV=production bundle exec rake db:seed` or deploy the code with Capistrano (which runs the `db:seed` task).
