### ISSUE TITLE
Vue UI Test Suite

### ISSUE THREAD

**Issue by maxkadel** [curationexperts/laevigata#2102]
- [x] Figure out how to run the Vue UI code test suite (in app/javascript/tests)
- [x] Get it passing
- [x] Document how to run in readme
- [x] Have it run as part of CI (split into separate ticket?)

**Comment by fnibbit** [comment]
https://github.com/curationexperts/laevigata/pull/2103

**Comment by maxkadel** [comment]
Coverage (found by running `yarn test --coverage`, can configure to run on each test run but significantly slows tests according to documentation - see https://jestjs.io/docs/en/configuration#collectcoverage-boolean ).

---------------------------------|----------|----------|----------|----------|-------------------|
File                             |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
---------------------------------|----------|----------|----------|----------|-------------------|
All files                        |     71.2 |    52.78 |    66.39 |    71.66 |                   |
 javascript                      |    68.46 |    57.14 |    52.05 |    69.17 |                   |
  App.vue                        |    69.35 |    59.09 |      100 |    69.35 |... 99,300,302,304 |
  CommitteeMember.vue            |    83.33 |      100 |      100 |    83.33 |            89,100 |
  CopyrightQuestions.vue         |      100 |      100 |      100 |      100 |                   |
  Degree.vue                     |      100 |       70 |      100 |      100 |          35,40,45 |
  Department.vue                 |    85.71 |       75 |      100 |    85.71 |             71,72 |
  Embargo.vue                    |      100 |      100 |      100 |      100 |                   |
  FileDelete.js                  |    92.31 |      100 |    66.67 |    92.31 |                15 |
  FileUploader.js                |    70.59 |     37.5 |    66.67 |       75 |       12,20,21,24 |
  Files.vue                      |    56.14 |       75 |        0 |    56.14 |... 53,256,286,287 |
  GraduationDate.vue             |    93.75 |      100 |    66.67 |    93.75 |                32 |
  Keywords.vue                   |      100 |      100 |      100 |      100 |                   |
  Language.vue                   |      100 |       75 |      100 |      100 |                36 |
  PartneringAgency.vue           |      100 |      100 |      100 |      100 |                   |
  ResearchField.vue              |      100 |      100 |      100 |      100 |                   |
  SaveAndSubmit.js               |    30.65 |     7.14 |    23.08 |    30.65 |... 17,118,119,121 |
  School.vue                     |    83.33 |      100 |      100 |    83.33 |             47,48 |
  Subfield.vue                   |      100 |      100 |      100 |      100 |                   |
  Submit.vue                     |      100 |      100 |      100 |      100 |                   |
  SubmittingType.vue             |    93.75 |    66.67 |      100 |    93.75 |                42 |
  SupplementalFileDelete.js      |      100 |      100 |      100 |      100 |                   |
  SupplementalFileUploader.js    |     62.5 |     37.5 |       50 |    66.67 |     6,19,20,23,30 |
  formStore.js                   |    60.93 |    55.93 |       32 |    61.95 |... 40,641,643,644 |
  quillKeyboardBindings.js       |        0 |      100 |        0 |        0 |                 2 |
  quillToolbarOptions.js         |        0 |      100 |        0 |        0 |                 2 |
 javascript/components           |    72.22 |      100 |        0 |    72.22 |                   |
  RichTextEditor.vue             |     87.5 |      100 |      100 |     87.5 |                30 |
  StartOverModal.vue             |       60 |      100 |        0 |       60 |       48,49,52,53 |
 javascript/components/submit    |    90.91 |       40 |      100 |    90.91 |                   |
  AboutMe.vue                    |      100 |      100 |      100 |      100 |                   |
  Affiliation.vue                |      100 |      100 |      100 |      100 |                   |
  Embargo.vue                    |      100 |       50 |      100 |      100 |                28 |
  FinalSubmission.vue            |      100 |      100 |      100 |      100 |                   |
  Keywords.vue                   |    42.86 |        0 |      100 |    42.86 |       54,55,57,58 |
  MyAdvisor.vue                  |      100 |      100 |      100 |      100 |                   |
  MyEtd.vue                      |      100 |      100 |      100 |      100 |                   |
  MyFiles.vue                    |      100 |      100 |      100 |      100 |                   |
  MyProgram.vue                  |      100 |       75 |      100 |      100 |                42 |
  UserAgreement.vue              |      100 |      100 |      100 |      100 |                   |
 javascript/lib                  |    79.78 |     5.56 |    90.91 |    78.82 |                   |
  BoxFileUploader.js             |    67.74 |        0 |    66.67 |    67.74 |... 46,47,50,58,59 |
  BoxSupplementalFileUploader.js |        0 |      100 |        0 |        0 |                 5 |
  Chair.js                       |      100 |      100 |      100 |      100 |                   |
  ChairList.js                   |      100 |      100 |      100 |      100 |                   |
  Keyword.js                     |      100 |      100 |      100 |      100 |                   |
  KeywordList.js                 |      100 |      100 |      100 |      100 |                   |
  Member.js                      |      100 |      100 |      100 |      100 |                   |
  MemberList.js                  |      100 |      100 |      100 |      100 |                   |
  PartneringAgency.js            |      100 |      100 |      100 |      100 |                   |
  PartneringAgencyList.js        |      100 |      100 |      100 |      100 |                   |
  formDataNoBlankFiles.js        |        0 |        0 |        0 |        0 |... 11,12,13,15,18 |
  isSafari11.js                  |      100 |       50 |      100 |      100 |                 2 |
 javascript/test                 |      100 |      100 |      100 |      100 |                   |
  dummy.js                       |      100 |      100 |      100 |      100 |                   |
  setupFile.js                   |      100 |      100 |      100 |      100 |                   |
---------------------------------|----------|----------|----------|----------|-------------------|
Test Suites: 47 passed, 47 total
Tests:       121 passed, 121 total
Snapshots:   0 total
Time:        6.846s
Ran all test suites.
✨  Done in 7.52s.
