### ISSUE TITLE
Do we need to notify faculty members about workflow progress?

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#212]
Do we need to notify faculty members (e.g., an ETDs advisor) about the ETD's submission, approval, etc? 

If we need to notify faculty members, we'll need to collect their contact info somehow. Is this a requirement?

**Comment by fpici** [comment]
Yes. Currently we notify Emory faculty chair and committee members when an ETD record 'reviewed and approved' and when it is 'successfully submitted'. The Emory Faculty emails are captured in the Student’s ETD record. I don’t believe there is a way to capture the Non-Emory committee members and therefore, probably NOT a requirement for the emails to go to them. See attached screenshots of sample emails to Emory Faculty. Hope this helps :-)

**Comment by fpici** [comment]
![approvedemail1](https://cloud.githubusercontent.com/assets/7809072/26358675/408ed9f6-3fa1-11e7-932e-d6a6a423677b.png)
![approved email 2](https://cloud.githubusercontent.com/assets/7809072/26358683/465c811c-3fa1-11e7-9704-b61f3c5ba10d.png)
![submittedemail](https://cloud.githubusercontent.com/assets/7809072/26358688/4985256a-3fa1-11e7-82db-db238d70f32c.png)

**Comment by shanitajohn** [comment]
Related to #289
