### ISSUE TITLE
Can we remove the Affiliation field for thesis advisors/committee members?

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#214]
How does Emory utilize the affiliation field for Emory and non-Emory thesis advisors/committee members? If the field is nonessential, can it be removed?

**Comment by fpici** [comment]
Hello there. We do not have an affiliation field for Emory Faculty but we do have an affiliation field for NON-Emory faculty. (see attached screenshot). we would like to retain the affiliation field for NON-Emory Facylty advisors. Hope this helps :-)
![affiliation](https://cloud.githubusercontent.com/assets/7809072/26355442/b1349ff2-3f96-11e7-8e4d-952ceef4e5f6.png)

**Comment by shanitajohn** [comment]
Sounds good. Yep, currently, only non-Emory faculty have the affiliation field. Because the decision was made that both non-Emory AND Emory faculty would have free form text fields for the names I envisioned that both would need affiliation, but that's actually not necessary with the dropdown. Thanks for weighing in!

**Comment by shanitajohn** [comment]
@bess and @mark-dce, Emory would like to keep the affiliation field for non-Emory faculty. 

This would still be consistent with the wireframes here:  https://emory.box.com/s/hs5ixiohij1l4l8c1vrxd5vgsvqgkhp9

I'll default to one of you to decide if this ticket warrants follow-up or if it can be moved to Done.

**Comment by mark-dce** [comment]
@bess could you add a comment documenting why we closed this ticket?

**Comment by bess** [comment]
Sounds like we do require the affiliation field for thesis advisors and committee members, and those fields are already represented in the wireframes.
