### ISSUE TITLE
Submit an ETD

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts/laevigata#2144]
**STORY**
As a student, I want to be able to submit my ETD. 

**DETAILS**
On [staging](staging-etd.library.emory.edu) - Version v2.7.2 updated 20 April 2021, once I log in and select "Submit my ETD" I get the following message:   "We're sorry, but something went wrong. If you are the application owner check the logs for more information."

**ACCEPTANCE** 
- [ ] Once I have successfully logged into the ETD application, when I select "Submit my ETD", I am able to go through the process of successfully submitting my ETD.

**Comment by mark-dce** [comment]
Fixed via https://github.com/curationexperts/laevigata/releases/tag/v2.7.3
