### ISSUE TITLE
Remove "Versions" option from "Actions" list

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#2153]
**ACCEPTANCE**
See freshdesk ticket [154](https://curationexperts.freshdesk.com/a/tickets/154) for details
- [x] The versions link is removed from the UI for individual files for all users
  - [x] Both Primary PDF and Supplemental Files
- [x] [BONUS] Set it up as a feature flag

<img width="1357" alt="image" src="https://user-images.githubusercontent.com/3064318/125833226-976b488c-3f09-4a1a-b7c3-f56ace096b6a.png">

**Comment by maxkadel** [comment]
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/8b0fe277-46c2-490a-ac03-1bc42f606f81)

![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/da050f9e-df7f-4dd2-aa88-bc1edd7a328b)
