### ISSUE TITLE
Add "I am submitting a..." metadata field

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#223]
- [x] Define a controlled vocabulary per spreadsheet
- [x] Define a "hasType" metadata field
- [x] Add it to the UI with a drop down menu
- [x] This is a single valued field
- [x] This field should be facetable

**Comment by shanitajohn** [comment]
**WIREFRAME**: https://emory.box.com/s/vntxy0nqr6zo5k8o99bj6uyerctxyo17
