### ISSUE TITLE
Add "school" drop down menu

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#224]
- [ ] Define a controlled vocabulary service
- [ ] Augment the school metadata field
- [ ] Add it to the UI with a drop down menu
- [ ] This is a single valued field
- [ ] This field should be facetable

**Comment by fpici** [comment]
Added a spreadsheet to Box called: SchoolsProgramsCourseStudy. I have revisions from Laney, Candler, College Honors and Pending Rollins: https://emory.box.com/s/rzv3foci3lcvl9a2xz09okrf5439adq1

**Comment by shanitajohn** [comment]
**WIREFRAME**: https://emory.box.com/s/vntxy0nqr6zo5k8o99bj6uyerctxyo17
