### ISSUE TITLE
Delete multiple objects gives "Something Went Wrong" error

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#225]
**ISSUE**
When I go to my works and try to delete multiple works simultaneously by checking their checkboxes and then clicking the "Delete Selected" button, I get a "Something Went Wrong" Page.

**STEPS TO REPRODUCE**
* Create two or more works (that you can delete)
* Make sure the works are approved
* Go to "My Dashboard"
* Click on "View Works"
* Select at least two works
* Click on the "Delete Selected" button

**EXPECTED BEHAVIOR**
* the works are deleted and you are returned to the "Works listing" or "My Dashboard" page

**ACTUAL BEHAVIOR**
* I get a "We're sorry, but something went wrong." message
* Only one of the selected works is actually deleted.

**Comment by bess** [comment]
I tried to re-produce this bug with the latest version of the workflow (Laney) can I cannot reproduce it. Instead, if I try to delete an approved work I get a a permission denied error, which seems right to me. A user shouldn't be able to log in and delete an ETD that's already been submitted and approved, right? 

@mark-dce Once we've got the latest code and workflow up on the demo server, would you try to re-create this and see if it's still an issue?
