### ISSUE TITLE
Ensure all metadata fields are present in application

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#227]
Using the master metadata spreadsheet (https://docs.google.com/spreadsheets/d/12EITagvnK3V8-6AJj7EWoPp4GrnY11HAtxmxrzgkL48/edit#gid=0) : 
- [ ] track which ones have been added to application
- [ ] audit this against the single item view page

**Comment by rotated8** [comment]
There is now a link to the spreadsheet in the main ETD Rewrite folder in Box.
