### ISSUE TITLE
Complete Security Requirements Spreadsheet

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#233]
**STORY**
The Architecture Review includes questions relating to DCE's security practices including.  We need to review and respond to the questions provided.

A google sheets version of the questionnaire can be found at 
https://docs.google.com/a/curationexperts.com/spreadsheets/d/1BkD9qq3tfCHASA-Af69E4yYP78wk3npZekH1FNBwttM/edit?usp=sharing

**ACCEPTANCE**
- [x] Review spreadsheet
- [x] Enter all known answers
- [x] Create tickets for any open issues or gaps and list in the comments to this ticket
- [x] Resolve all linked tickets

**Comment by mark-dce** [comment]
@acozine I've made a first pass at filling in the answers I can and highlighted areas I don't know the best answer for.  Can you please review my answers and fill in any of the missing info you can.  For items that you can't immediately complete, let's either schedule time to figure out next steps or create tickets to follow-up on individual issues.

**Comment by mark-dce** [comment]
@bess I have identified some of the application security related questions as possibly needing your input by highlighting them in yellow and marking them "? Bess to respond"

**Comment by bess** [comment]
I see a section titled "5.7.4. Attempts to access sensitive data"... Can we ask what their definition of "sensitive data" is? I would argue that we aren't storing any. We would be (I assume, let's verify with @acozine) logging any ssh attempts to the system. Or, is the ability to approve considered "sensitive"? Do we need to log every connection from a superuser?

**Comment by rosy1280** [comment]
I believe that "sensitive data" is more along the lines of PHI, HIPPA, PCI data.  But perhaps @SolomonHD would know better than I (or at least know someone that could answer that question).

@SolomonHD see @bess question above about the filling out necessary information for the Security/ART Review.

**Comment by SolomonHD** [comment]
As far as I know academic data isn't considered sensitive I think simply stating no sensitive data will be stored or collected on ETD will be enough.

**Comment by mark-dce** [comment]
@shanitajohn - Alicia and I were able to finish answering open questions so I'm marking this ticket as complete (closed).  Alicia is getting the architecture diagram #103 started and then the rest of us will help fill in details as needed.  Once all of the ART review documents are completed, we should schedule a final comprehensive review to make sure all of the documents (security review spreadsheet, design questions, system architecture diagram, and anything else) are all consistent and use similar terminology before we make the final submission.
