### ISSUE TITLE
Get representative test files onto our test cloud drives

### ISSUE THREAD

**Issue by jenlindner** [curationexperts/laevigata#234]
**ACCEPTANCE CRITERIA**
- [ ] 2.5GB (max expected size) of video, audio, and image formats

**Comment by mark-dce** [comment]
@shanitajohn & @jenlindner I've just finished uploading 3 very large videos .8Gb - 4.1Gb to https://app.box.com/folder/28931523456.  They all are are available under CC licenses, so we are free to post and display them.  

Generally audio and image files will be 1/10th to 1/1000th the size of a video file on average.  So, do you think we also need really huge (>1mb audio and image files) or are we good to go with the video files?

**Comment by jenlindner** [comment]
We have a 1.7GB tif already, here's the doc where we're keeping track of technical and policy requirements for uploading large files: https://docs.google.com/document/d/1wLFXH3XChgVoQGWH3L1I5XJFJ3Jk9orLIM-Ua-pa__A/edit. I think we definitely need an audio format test file, in the normally expected file-size range sounds fine.

**Comment by mark-dce** [comment]
I've added two additional audio files to the same box folder.  Closing this ticket for now, but happy to add more images or audio if that's helpful.
