### ISSUE TITLE
Test upload and ingest including large file formats

### ISSUE THREAD

**Issue by jenlindner** [curationexperts/laevigata#235]
**ACCEPTANCE CRITERIA**
- [ ] Each representative format has been successfully uploaded and ingested

**Comment by acozine** [comment]
File format list:
- [ ] PDF
- [ ] Images 
- [ ] Sound
- [ ] Video
- [ ] Confirm supported image formats (TIFF, JPEG, JP2, PNG, others?)
- [ ] Confirm supported sound formats
- [ ] Confirm supported video formats

**Comment by shanitajohn** [comment]
Closing this ticket for large files. Opening new tickets for supported file formats for audio, video, documents and images.
