### ISSUE TITLE
Check Coveralls coverage %

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#24]
**ISSUE**
Coveralls is currently reporting 98% coverage, which seems surprising given that all or our test suite is currently skipping all tests

**ACCEPTANCE**
- [x] Coveralls documentation reviewed to understand coverage metrics better
- [x] Team discussion about coverage metric
- [x] Coveralls reports a number consistent with the outcome of the team discussion

**Comment by bess** [comment]
@mark-dce: You and I talked about this today. Does that fulfill the requirement for a team discussion? Or did you want to talk to everyone?

**Comment by mark-dce** [comment]
Yup - let's call it good for now.  I'll try and spend some time reading up and educating myself on how the metrics work.
