### ISSUE TITLE
Questionnaire Tab

### ISSUE THREAD

**Issue by fpici** [curationexperts/laevigata#246]
Here is the  text for Copyright Questionnaire and Patent question on Questionnaire page. Please make it three separate questions:

1)    Does your thesis or dissertation contain any third-party text, audiovisual content or other material which is beyond a fair use and would require permission?  
2)    Does your thesis or dissertation contain content, such as a previously published article, for which you no longer own copyright?”
3)    Does your thesis or dissertation disclose or describe any inventions or discoveries that could potentially have commercial application and therefore may be patented?

**Comment by shanitajohn** [comment]
Thanks! I added the copy to the wireframes but will keep the ticket open until the copy has been added to the application.

**Comment by shanitajohn** [comment]
Regarding the third question on "Questionnaire Tab #246" 

3) Does your thesis or dissertation disclose or describe any inventions or discoveries that could potentially have commercial application and therefore may be patented?
Answer: If so, please contact the Office of Technology Transfer (OTT) at Phone: (404) 727-2211.

**Comment by shanitajohn** [comment]
This copy has been added to the application -- there is no longer a questionnaire tab
