### ISSUE TITLE
Patent Question/Information

### ISSUE THREAD

**Issue by fpici** [curationexperts/laevigata#247]
Regarding the third question on "Questionnaire Tab #246" 3) Does your thesis or dissertation disclose or describe any inventions or discoveries that could potentially have commercial application and therefore may be patented?
Answer: If so, please contact the Office of Technology Transfer (OTT) at Phone: (404) 727-2211.

**Comment by shanitajohn** [comment]
Related to Ticket #247 -I also copied this content there.
