### ISSUE TITLE
PDF/A instructions on  "My Primary PDF" Page

### ISSUE THREAD

**Issue by fpici** [curationexperts/laevigata#248]
SCO would like to add an explainer/ instructions in the Descriptive Text on the "My Primary PDF" page to assist users with PDF/A conversion and upload. For example: "PDF/A is an ISO-standardized version of the Portable Document Format (PDF) specialized for use in the archiving and long term preservation of electronic documents." 
For assistance converting your manuscript to PDF/A format please contact Student Digital Life http://it.emory.edu/studentdigitallife/

**Comment by shanitajohn** [comment]
Related to Ticket #146

**Comment by shanitajohn** [comment]
This copy has been added to the content doc and approved and will be added to the application.
