### ISSUE TITLE
Copyright & Patent Questions

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#251]
**DETAILS**
Copyright and Patent questions should be added to the bottom of the My ETD Tab, per the below wireframes.

**ACCEPTANCE CRITERIA**
- [x] There should an area designated for a brief description of the tab
- [x] Each question should have Yes or No radio button, forcing a binary response. 

**WIREFRAME (updated 06/13/2017)** 
https://emory.box.com/s/n37yl4hssql1xhf87j1xxtf4zepzp58m

Related to Ticket #246

**Comment by shanitajohn** [comment]
Questionnaire questions have been labeled as "Copyright and Patent" and moved to the bottom of the My ETD tab. Updating ticket language.

**Comment by jenlindner** [comment]
I added a header and lorum ipsum copy in the same formatting as the rest of our helper text in PR #431.
