### ISSUE TITLE
Kill SSH connections to sever after inactivity

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#259]
Per Emory security requirements, inactive ssh should have their idle timeout set to 15 minutes or less.

**Comment by acozine** [comment]
Set the ClientAliveInterval in `/etc/ssh/sshd_config` - setting is # of seconds to allow inactive connections. See https://linux.die.net/man/5/sshd_config

**Comment by acozine** [comment]
Set to 900 seconds (15 x 60)
