### ISSUE TITLE
Enable syslog rotation

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#260]
As a sysadmin, I would like to be able to periodically archive syslog data and purge older archives so that my syslog does not grow infinitely big.

- [x] Log rotation is configured
- [x] Log archives are save for 60 days minimum (per Emory security requirements)

**Comment by mark-dce** [comment]
Potentially useful info at https://help.ubuntu.com/community/LinuxLogFiles

**Comment by acozine** [comment]
Updated the definitions in `/etc/logrotate.d/rsyslog`, which includes rotation routines for many system logs.
