### ISSUE TITLE
Update ClamAV virus definition files on a daily basis

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#261]

**Comment by mark-dce** [comment]
Blocked until ClamAV is configured for the application.  See #221

**Comment by bess** [comment]
ClamAV is now configured for the application. We have this working with manual configuration on the server. FreshClam takes care of virus updates. What is needed now is to get all of that into the ansible setup scripts.

** Acceptance Criteria **
- [ ] FreshClam is set to run (recommended is 2x daily)
- [ ] ClamAV is installed and configured via ansible
- [ ] FreshClam is installed and configured via ansible
- [ ] FreshClam and ClamAV will restart in case of server reboot

**Comment by acozine** [comment]
By default on Ubuntu, ClamAV checks for a new database hourly:
```
# Check for new database 24 times a day
Checks 24
```
For simplicity's sake, I'd recommend we try the default setting for a while and see how it goes. If it ends up burning up system resources, we can scale it back.
