### ISSUE TITLE
Document Backup and Recovery Procedures

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#262]
**STORY** 
As an application owner, I want to ensure that my application and data can be restored after any type of incident which might compromise my system, so that I can make the application and data available to my users in a reasonable timeframe.

NOTE: This ticket covers implementing and documenting the backup and restore process.  Testing the process is covered in #263

**ACCEPTANCE**
- [x] Regular backup process for the following is documented
  - [x] Application server
  - [x] Application database
  - [x] Application data (fedora repository)
  - [x] [Optional?] Solr index 
- [x] Restore process for the following is documented
  - [x] Application server (can be full rebuild or restore from backup)
  - [x] Application database
  - [x] Application data (fedora repository)
  - [x] Solr index (can be restore from backup or reindex of fedora data)

**TBD**
- [ ] Document and prioritize any requirements for recovery of in-process submissions

**Comment by bess** [comment]
Document here: https://github.com/curationexperts/playbook/pull/59

There shouldn't be anything special needed to recover in-process submissions.
