### ISSUE TITLE
Metadata fields for ETD search results

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#27]
When I search the ETD database the search results should come back with the following metadata: 

**ACCEPTANCE CRITERIA** 
- [x] I want be able to see the title of the ETD 
- [x]  I want to be able to see the submitter's first and last name, formatted consistently
- [x]  I want to see the year the ETD was submitted 
- [ ] ~I want to see the name of the submitter's Master's Thesis Committee Chair or Thesis - Advisor **~
- [ ] ~I want to see the names of other Committee Member **~
- [x] I want to see related Research Fields
- [ ] ~I want to see Partnering Agencies **~
- [ ] ~I want to see related Keywords **~
- [x] I want to see the name of the Program/Department the submitter is a part of 
- [ ] ~I want a link to a Permanent URL for the ETD **~

**Comment by shanitajohn** [comment]
@bnash108 In there interest of keeping the initial search result page uncluttered, I'm suggesting we don't need to see the ** items until you click in.  Do I have your approval to show just the Title, Student Name, Submission Year and Research fields?

**Comment by bnash108** [comment]
@shanitajohn I think that sounds like a good plan. @fpici what do you think?

**Comment by fpici** [comment]
I totally agree with this reasoning :-)

**Comment by val99erie** [comment]
@shanitajohn The appearance of the student's name will depend on how the data was entered.  We are not storing the student's first and last name separately (and I don't recommend that we do), so we don't have the ability to sort parts of the name in a certain way.

If all students follow the instructions on the form to enter the data as 'Last name, First name', then all the names will appear consistent.  But if a student enters their name in a different way (and if the approver allows that), then the name will appear different in the search results.

If this is a problem, we can discuss options, but separating storage of first and last name has its own set of complications.  In my opinion, storing the full name as one string is the best way to do it.

**Comment by fpici** [comment]
@val99erie Hi Val. I am sending this to Lisa for her thoughts.I will let you know as soon as she responds. Many thanks!

**Comment by fpici** [comment]
@val99erie @rosy1280 @rotated8 Hi Val.  I discussed this with Lisa and she asked me to consult with Collin to see if we could pull the  full name in as one string populated by the depositor's NetID. This is the way Old ETDs worked and we would like the same for New ETDs. Collin thinks that it is possible and perhaps we can start a conversation around this need, how much time, what it could take away from, etc. Many thanks!
