### ISSUE TITLE
Emory to provide SSL certificates for production system

### ISSUE THREAD

**Issue by acozine** [curationexperts/laevigata#271]
Once we know the domain name for the ETD system, purchase SSL certificates for the site. I'd recommend using AWS certs and load balancing for simplicity, ease of maintenance, and response to spikes in demand.

**Comment by acozine** [comment]
Related to #173.
Blocked by #90.

**Comment by shanitajohn** [comment]
Both of the above tickets have been closed. @SolomonHD Is this something you can take on?

**Comment by SolomonHD** [comment]
Usually we use InCommon Certs which we get for free. Not totally sure if InCommon will cover this but I'll investigate

**Comment by SolomonHD** [comment]
After talking things over with my team and Alicia, the current plan is to transfer over the SSL cert we are already using for old ETD to the new ETD when it goes live.
