### ISSUE TITLE
Filtering search results

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#28]
**STORY**
As a human being searching the ETD repository, on the results page I would like to be able to use the following criteria to narrow my results so that I can find what I am looking for.

**ACCEPTANCE CRITERIA**
- [x] Year 
- [x] Subject (Research field)
- [x] Committee (seems to be referencing names from both the committee chair and members)
- [x] Program 
- [ ] ~Author (Creator)~
- [x] Keyword

**Comment by shanitajohn** [comment]
@fpici @bnash108 Can you confirm that these are the data points we should allow user to facet on? These are from the current application.

**Comment by bnash108** [comment]
@shanitajohn Those are indeed the filtering options in current ETDs, and we should keep them. If, at some point in the future, Fran & co. realize there is a need for a different facet, is that something that could be added?

**Comment by shanitajohn** [comment]
@bess Not sure how easy or difficult these are to add in the future, I'll have to default to a developer. @val99erie,  @bess?

**Comment by bess** [comment]
Not too hard to add new ones in the future.

**Comment by bess** [comment]
@bnash108 and @fpici Are you *sure* you want an author facet? How often will you have more than one work by a given author? I would suspect almost never. That's work and screen real estate for very little pay off.

**Comment by fpici** [comment]
I agree with you Bess. Every once and awhile we may have an author with two works (Master's thesis and Dissertation) or in a rare case, but possible three (Honors and Master's and Dissertation). So, no author facet :-)
