### ISSUE TITLE
notifications to Emory faculty 

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#289]
- [ ] "Work has been approved" notifications go to appropriate Emory faculty

**Comment by shanitajohn** [comment]
Related to #310

**Comment by fpici** [comment]
Yes. Currently we notify Emory faculty chair and committee members when an ETD record is 'reviewed and approved' and when it is 'successfully submitted'. The Emory Faculty emails are captured in the Student’s ETD record. I don’t believe there is a way to capture the Non-Emory committee members and therefore, probably NOT a requirement for the emails to go to them. Hope this helps!

**Comment by mark-dce** [comment]
Closing this ticket since we currently have no reliable way to acquire (& keep updated) contact information for faculty.
