### ISSUE TITLE
Add a "hidden" state to all workflows

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#291]
- [x] the ETD model has a field indicating "hidden" that is persisted to the object
- [x] Superusers and workflow approvers can hide a work from any workflow state
- [x] Superusers and workflow approvers can unhide a work from any workflow state
- [x] Marking a document hidden does not otherwise affect its workflow (e.g., it still needs approval etc)
- [x] Question: Who should get notifications when a work has been hidden / unhidden? I have assumed this should be approvers and depositing users, but let me know if I'm mistaken.
- [x] Implemented for all workflows
  - [x] Laney 2 step approval
  - [x] Emory 1 step approval (the wf used by Rollins, Emory College, and Candler)

**Comment by fpici** [comment]
Hi Bess. Forgive me for this question but by "dark" do you mean "inactive."

**Comment by bess** [comment]
Hi, @fpici. Take a look at this diagram: https://docs.google.com/drawings/d/1oCNgx4XiDzZdsomnTkP4LVkVBtr0rHJ4OJhZUXlmJo0/edit
I believe that in your current ETD application you use the term "inactive" to indicate that an ETD should not be displayed to the public, but admins and school approvers can still see it, is that right? And I believe that we decided in this app we would use the term "dark" instead.

**Comment by fpici** [comment]
Yup. That is what I thought. Just making sure. Thank you for clarifying … I will now venture forth ☺



Frances Pici
Scholarly Repository Application Support Analyst
Scholarly Communications Office
Emory University Libraries and Information Technology
Robert W. Woodruff Library
540 Asbury Circle
Atlanta, GA 30322
404.727.7673
fpici@emory.edu<mailto:%7Cfpici@emory.edu>

Check out our new websites!
Scholarly Communications http://sco.library.emory.edu/index.html
Research Data http://researchdata.emory.edu/index.html
