### ISSUE TITLE
Update research fields with latest data from ProQuest

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#292]
- [ ] Research fields file updated with latest data from ProQuest (@bnash has asked for the latest data)

**Comment by bnash108** [comment]
[ProQuestSubjectCategories_06-12-2017.xlsx](https://github.com/curationexperts/laevigata/files/1068787/ProQuestSubjectCategories_06-12-2017.xlsx)

**Comment by bnash108** [comment]
@bess @shanitajohn ProQuest provided updated list of research fields above

**Comment by shanitajohn** [comment]
@rotated8 Please use the XLS that Bethany provided above to complete your work on the research fields drop down. Thanks!

**Comment by rotated8** [comment]
@bnash108 The spreadsheet appears to have problems, which you can see better in github: https://github.com/curationexperts/laevigata/pull/335/files. Can we ask ProQuest for fixes?

**Comment by bnash108** [comment]
[ProQuest_subjects_06-19-2017.xlsx](https://github.com/curationexperts/laevigata/files/1086234/ProQuest_subjects_06-19-2017.xlsx)

**Comment by bnash108** [comment]
@rotated8 Above is the updated spreadsheet from ProQuest
Let me know if I need to circle back to ProQuest with questions
