### ISSUE TITLE
Re-order submission type list

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#295]
**STORY**
As a submitter, I would like the submission type list to show the options in academic progression, so that they match my mental order.

**ACCEPTANCE**
- [ ] The "I am submitting" dropdown should show options in this order: Honors Thesis, Masters Thesis, Dissertation
- [x] The label reads "I am submitting my".

**Comment by shanitajohn** [comment]
Degree types are still displaying in the wrong order. Order should be: 
Honors Thesis
Master's Thesis
Dissertation

**Comment by bess** [comment]
These are now in the right order but "Master's Thesis" needs its missing apostrophe
