### ISSUE TITLE
Set up server environment on AWS

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#3]
**ACCEPTANCE**
- [x] Staging environment configured

NOTE: we will setup up additional environments after the team has discussed promotional models

**Comment by mark-dce** [comment]
Use Ruby 2.3.4 https://www.ruby-lang.org/en/news/2017/03/30/ruby-2-3-4-released/

**Comment by acozine** [comment]
Staging environment running at emory.curationexperts.com. Currently using passenger with apache. Ruby version: `ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-linux]`
