### ISSUE TITLE
Implement Primary File metadata

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#300]
**ACCEPTANCE CRITERIA** 
- [x] Language 
- [x] Abstract or Summary 
- [x] Table of Contents
- [x] Keywords 
- [x] Rights 
- [x] Identifier (not on the form) 

**NOTES**
Metadata Spreadsheet: https://docs.google.com/spreadsheets/d/12EITagvnK3V8-6AJj7EWoPp4GrnY11HAtxmxrzgkL48/edit#gid=0

**Comment by bess** [comment]
@alexBLR  I have added abstract, rights_statement, and identifier.

**Comment by bess** [comment]
Question for Emily: The Language field already exists in Hyrax with the predicate http://purl.org/dc/elements/1.1/language. Do we care enough about doing something different that we want to override this?

**Comment by bess** [comment]
@alexBLR I went ahead and finished this since I was on a roll.
