### ISSUE TITLE
Implement Supplemental File metadata

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#301]
**ACCEPTANCE CRITERIA** 
- [x] Title
- [x] Author
- [x] Description 

**NOTES** 
https://docs.google.com/spreadsheets/d/12EITagvnK3V8-6AJj7EWoPp4GrnY11HAtxmxrzgkL48/edit#gid=0

**Comment by bess** [comment]
Moving human readable file type to its own ticket
