### ISSUE TITLE
Respect workflow field indicating hidden visibility in display

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#303]
- [x] Hidden ETDs don't display unless you are a superuser or workflow approver
- [x] When viewing a hidden work, you see a visual indication that the work is hidden

**Comment by bess** [comment]
What is the expected behavior when an unauthorized user goes to a hidden file? Re-direct? Or some kind of "you are not authorized" message?

**Comment by fpici** [comment]
I like the idea of an "authorized message." Currently, in old ETDs, the superuser or workflow approver sees this: "This record is not published. Current status: inactive."  Hope this helps,

**Comment by bess** [comment]
This work should be hidden: https://etd.library.emory.edu/concern/etds/ks65hc22c?locale=en

It was not submitted to ProQuest, which was correct, but it got published. I've marked it "restricted" manually for right now, but we need a better solution.

**Comment by mark-dce** [comment]
We should ensure our solution here is harmonious with our solution for https://github.com/emory-libraries/etd-issues/issues/21
