### ISSUE TITLE
Basic ETD show page

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#306]
- [x] Wireframe for display screen
- [x] Display all the fields for an ETD

**Comment by shanitajohn** [comment]
**WIREFRAME:** https://emory.box.com/s/wdiz63c6tntt08hk6v158hb5wnh65m8r

**Comment by bess** [comment]
This is done, but for metadata fields only. Still required is Files and FileSet metadata. Tracking that work under #359 and #360
