### ISSUE TITLE
Split Research Field metadata into two fields

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#309]
- [ ] research_field_id should store the proquest id of the research field selected (predicate TBD, ask Emily)
- [ ] research_field should store the human readable string
- [ ] research_field should use http://purl.org/dc/elements/1.1/subject instead of dcterms:subject

**Comment by rotated8** [comment]
@bess should research_field_id be stored in solr?

**Comment by bess** [comment]
I don't think so. I can't see anyone wanting to search by that. It doesn't seem meaningful for anyone except ProQuest.
