### ISSUE TITLE
Object level show page

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#31]
As a general user, when I click on the title of an ETD on the search results page, I want to be taken to a page where I can see the below information, so that I can know more about the ETD I clicked on. 

**ACCEPTANCE CRITERIA**
- [x] Title of the ETD 
- [x] Author's name
- [x] Year the ETD was submitted 
- [ ] ~Total number of pages in the ETD **~
- [x] Name of the Committee Chair / Thesis Advisor
- [x] Names of all Committee Members 
- [x] Research Fields 
- [x] Keywords 
- [x] Program name 
- [ ] ~Permanent URL~
- [x] An abstract from the ETD (unless under embargo)
- [x] The ETD table of content (unless under embargo)
- [x] A link to download the ETD file (unless under embargo)

**Comment by shanitajohn** [comment]
**Is this a requirement?

**Comment by bnash108** [comment]
@shanitajohn I think this does not have to be a requirement. What do you think, @fpici?

I think it's nice to have, but not so nice that it is worth extensive development time.

**Comment by bess** [comment]
I would remove number of pages and permanent URL from this list

**Comment by shanitajohn** [comment]
@bess That's totally valid. @bnash108 @fpici Can we move forward with Bess' recommendation?

**Comment by bess** [comment]
Are we *sure* we want abstract and toc in the search results? And the file download there too? I'd caution against re-creating the entire show screen on the search results page. Also, re-creating the embargo checking logic in the search results is going to be expensive and time consuming. These search results have already been adjusted to match the wireframes that Shanita made:

https://emory.curationexperts.com/catalog?locale=en

Could we take a look at what we've already built and decide whether anything necessary is really missing?

**Comment by bnash108** [comment]
@shanitajohn @bess I'm getting an update from @fpici about sprint planning yesterday. I wanted to confirm that this ticket now refers to the record/object page rather than search results page. If so, the abstract and TOC should be visible on the record page (as it is previously built). But I agree that those, the embargo info, and download don't need to be in the search results.

**Comment by bess** [comment]
Double checked and all of these fields are present on the work show page.
