### ISSUE TITLE
Persist correct committee members and chair metadata

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#310]
- [x] Committee Member and Thesis Advisor need to be their own Faculty Member object. That object needs its own fields:
  - [x] Name (last, first)
  - [x] Affiliation 
  - [x] Emory email address if affiliation == Emory

Related #49 and #51

**Comment by shanitajohn** [comment]
@fpici @bnash108 We have a few open questions

When do we need to notify faculty? 
- [ ] Who do we notify? 
- [ ] Emory Faculty chair, upon approval? 
- [ ] Non-Emory Faculty chair, upon approval? 
- [ ] Emory Committee members, upon approval? 
- [ ] Non-Emory Committee members, upon approval? 
- [ ] Do we need email addresses for non-Emory committee members and chairs?

**Comment by bnash108** [comment]
- Who? - Emory committee chair/thesis advisor and Emory committee members
- Receive notifications at: submission, review, approve, and publish

Current ETD application does not collect emails for non-Emory committee members and chairs.

More info and sample of email sent to faculty @ https://github.com/curationexperts/laevigata/issues/212

**Comment by bess** [comment]
Note: this is done, but needs review of the RDF predicates I picked

**Comment by bess** [comment]
Predicates reviewed and approved by Emily
