### ISSUE TITLE
Build ProQuest packages

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#317]
- [x] Build ProQuest specified packages of exported ETDs
  - [x] Check submission criteria
    - [x] for PhD
    - [ ] ~for Master's~ 
  - [x] Export XML
    - [x] XML must validate against ProQuest provided DTD
    - [x] XML must use only ProQuest approved tags for formatting
      - [x]  Use &lt;italic&gt; instead of &lt;em&gt; tags
  - [x] Export and package files
  - [x] Zip exported files together in a uniquely named directory

**Comment by bess** [comment]
@bnash108 and @fpici : There is a ProQuest required field called `apply_for_copyright`. Here is the field description: "     
```
*apply_for_copyright = indicate if the author want us to apply for copyright. 
     There is an additional $65 fee for copyright registration, and for FTP sites, 
     the author must submit a signed paper form with the additional payment.-->"
```
How do I know how to answer this question for a given ETD?

**Comment by bnash108** [comment]
@bess Emory students will not be able to apply for copyright via ProQuest going forward, so the answer should always be no. Do you need the exact format for the answer (ex: no vs. n)? If so, I can check into that for you
