### ISSUE TITLE
Create recurring nagios reports

### ISSUE THREAD

**Issue by acozine** [curationexperts/laevigata#320]
As a first step to notifying Emory folks about the status of their systems and overall uptime, configure nagios to send a PDF of a baseline CGI view of the week's outages.

**Comment by acozine** [comment]
First Pass at the report:
[Nagios-WeeklyStatus-2017-06-29.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/551c64404c50c61e00481270/125516c66e82c728ace21e0d46c6959d2a8d90e4b8ecba48a844c380285232606456f37a27c8b37ef2102243434d0eee1e020a17b8eb8339a3be6823825a0cb8d63b0b27923a11acb9d34bb807ee28dd5d99a4fedb1294b7607caddecd5d340c061983fe593ca89e4ccf5dff4fe44854b65e.pdf)

**Comment by acozine** [comment]
Where should I send the reports, and on what schedule?

**Comment by fpici** [comment]
Hi all. Bethany and I and the LibSystems folks are on the Nagios alerts now for current ETDs and Bethany and I should be on the new ETDs Nagios alerts. But we are not sure if the LibSystems team should be on the new ETDs Nagios alerts. That would be a question for Steve Collins scolli9@emory.edu and or Rosalyn.
Hope this helps!

fran

**Comment by rosy1280** [comment]
Hi All,

I'd like to have a conversation with the Emory team about Nagios alerts before making a decision. @tmiles2 can you put this on the agenda for next week? @acozine is it ok to get back to you in a week?

**Comment by acozine** [comment]
@rosy1280 please note that the mention of "outages" in the original description is misleading. I'm not actually talking about Nagios alerts, but about a weekly (or could be daily or monthly) status report that goes out whether or not there are any outages. This report will be the basis for evaluating uptime.

**Comment by acozine** [comment]
That said, we can discuss the details in a week or so, after you've made some decisions about Nagios alerts too. @rosy1280 @tmiles2

**Comment by rosy1280** [comment]
Thanks @acozine, that was my assumption. We'll make sure the Emory team is all on the same page about the reports when I'm back from vacation.

**Comment by tmiles2** [comment]
@rosy1280  I'll add this to the Emory team meeting agenda  for next week.

**Comment by rosy1280** [comment]
@acozine in brief hallway discussions, it was decided that i should get the reports for now, although we may add another person later.

my email address is: rosalyn.metz@emory.edu
