### ISSUE TITLE
Track availability of Shibboleth

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#321]
**ACCEPTANCE CRITERIA** 
- [x] I would like to be able to monitor Shibboleth's availability on an hourly basis
- [x] I would like to receive an email notification when Shibboleth is not up and running
- [x] I would like to save data on the results of these checks

**Comment by acozine** [comment]
First step is to make a successful check for the DCE Shibboleth server - probably will look at https://shibboleth.curationexperts.com/idp/status and make sure the Emory metadata source shows up there: `metadata source: EmorySandboxMetadata` - this check should run from the Emory sandbox.

**Comment by acozine** [comment]
Okay, I have a working DCE Shibboleth check modeled on the idea above:
`command[check_shib]=/usr/local/nagios/libexec/check_http -H 52.6.252.94 -S -p 8443 -u https://shibboleth.curationexperts.com/idp/status -s EmorySandboxMetadata`
For this to work, the sandbox IP (full CIDR) must be included in the list of IPs allowed to access the status page on the Shibboleth IDP (this list is in `shibboleth-idp/conf/access-control.xml`.

**Comment by acozine** [comment]
Per discussion with Gerry Hall at Emory, we cannot have access to the IDP status page on login.emory.edu. I've created a basic check that looks at the IDP metadata page instead, and added it to the nagios suite for emory.curationexperts.com. I have an example for a more thorough check that actually logs in via shibboleth and checks the redirect page, but I haven't gotten it to work against the sandbox server yet. I'll open a separate ticket for that.
