### ISSUE TITLE
Manage static footer pages via external Emory system

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#343]
- [ ] ~Gain access to external page management system~
- [ ] ~Update this ticket with implementation to-dos~

**Comment by shanitajohn** [comment]
@bnash108 @fpici  In talking to @mark-dce I learned that there is an external CMS that we need use to make the static pages (Contact Us, Frequently Asked Questions, etc) editable. Can you provide us with access to this tool please? Thanks!

**Comment by mark-dce** [comment]
This was actually from a discussion I had with @rosy1280 when we were initially scoping the engagement.  Let Rosy and I know if we need to revisit the discussion.

**Comment by rosy1280** [comment]
@bnash108 and @fpici we had talked about these pages living on http://sco.library.emory.edu/.  We should talk to @kristianserrano about how to make this happen.

**Comment by rosy1280** [comment]
The content [Contact, Embargo, FAQ, Help, Instructions, Intellectual Property, Policies, and News Feed] is already in the CMS.  We need to figure out where to publish this content to.

@bnash108 and @kristianserrano will work together to figure that out.  @shanitajohn at that point DCE would need to link to the static pages.

**Comment by kristianserrano** [comment]
The pages have been copied to the SCO site in Cascade.

@bnash108 is working on where to place those pages within the site. I've offered LWUXS services to help with content organization and IA if needed.
