### ISSUE TITLE
research field id lookup is fragile

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#354]
When importing legacy data, research_field values won't always match the most recent ProQuest values. E.g., a legacy value for this field is "Clinical Psychology", but the new term is "Psychology, Clinical", and it also has a different research field id.

-[ ] Refactor research field so it is a complex object (like committee_member) that can store both a label and associated id number. We can't assume we'll always be able to look up the id number from a string, so we have to store it with the ETD when we have it. 
- [ ] research field labels are also used for subject searching and faceting. In addition to storing the value in a field for ProQuest submission, index it at the work level so it can drive UI interaction.

**Comment by tmiles2** [comment]
@bess I marked this ticket close by accident.

**Comment by bess** [comment]
We only need to migrate the legacy data, not look it up in the current ProQuest subject list.
