### ISSUE TITLE
Add an option to "Submit Your ETD"

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#36]
**STORY**
As a frazzled depositor, I would like to see a button on the ETD homepage that tells me simply and without ambiguity where to click to begin the ETD submission process. 

- [x] Change the language on the "Share Your Work" button to read "Submit My ETD"

**Comment by shanitajohn** [comment]
![Screen Shot 2017-07-10 at 12.03.35 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56a796b4884b1f13002fff7c/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77246455f36b7191a379ed0c2b52415c4bbc21254d58eeb9cb74fce36f34985619e8d9390c7cc03a44abeed64ceb06ba208a1ed1b1bade4496fa2137a5dad11b61435c52dcbd4f3fb29b4dc259f242e84a55a2113362ee71336e0a.png)

**Comment by shanitajohn** [comment]
Related to #805
