### ISSUE TITLE
Make sure the user is logged in to submit an ETD

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#37]
As Superadmin Carla, I want students to be required to log in so that I can trust who the submission comes from. 

**NOTE**
This probably already happens by default in Hyrax, but we should confirm the behavior.  We may also want to add a test or two to the test suite to document the desired behavior.

**ACCEPTANCE CRITERIA** 
- [x] Check that the user is logged in before allowing them to start the submission process
- [x] Redirect the user to a login page, if they try to start the submission process, but are not logged in

**Comment by jenlindner** [comment]
PR created.
