### ISSUE TITLE
Build distributed sandbox architecture

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#375]

**Comment by acozine** [comment]
Acceptance:
- [ ] Dedicated security group for Emory Sandboxes
- [ ] Fedora machine in Emory Sandbox SG
- [ ] Solr machine in Emory Sandbox SG
- [ ] Web server in Emory Sandbox SG
- [ ] Three machines work together to provide full functionality of system
- [ ] Ansible scripts can recreate the full triumvirate
