### ISSUE TITLE
Update or remove "terms" page

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#381]
There is a default Hyrax paged called "terms" that outlines the terms of use. Right now it uses default language that seems to be from Penn State, with just the name of the application replaced. See section 13 here: https://emory.curationexperts.com/terms
- [ ] Update terms of service to Emory-appropriate language

**Comment by mark-dce** [comment]
See #343 - I'm guessing this gets replaced by Emory's IP or Policies page content.

**Comment by mark-dce** [comment]
**UPDTE** Let's time bound this, if Emory can provide text by EOD 8/23, we will add this context for the initial launch. If the text is not available by EOD, we will temporarily remove the link until text can be provided.

**Comment by mark-dce** [comment]
@fpici - would you have access to the text we need (that would replace https://emory.curationexperts.com/terms)?

**Comment by fpici** [comment]
Good Morning Mark.

I am checking with Bethany on this one. We will have an answer soon ☺



Frances Pici
Scholarly Repository Application Support Analyst
Scholarly Communications Office
Emory University Libraries and Information Technology
Robert W. Woodruff Library
540 Asbury Circle
Atlanta, GA 30322
404.727.7673
fpici@emory.edu<mailto:%7Cfpici@emory.edu>

Check out our new websites!
Scholarly Communications http://sco.library.emory.edu/index.html
Research Data http://researchdata.emory.edu/index.html

**Comment by fpici** [comment]
Hi Mark. SCO just updated and approved the Terms of Use and I attach it as a word document to this message. Going forward and at a later date, we will probably revise this document but for now this will do. Hope this helps!
[ETDs Terms of Use 2017.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58efcaa2b7100d001a59b5e8/125516c66e82c728ace21e0d46cda0be30c2b7ac9de4ac03ab5bb0a13a4367217955f4693cc7f33ab0487e021b4d44be44500b17f4ff8e7ea1e06823de5b0bedd03c0b73c06919faaa9e0dfd50e474d412dcfce9c85ecafa3a2ce1818e4a3e1d011a8af95d33a59c49da15.docx)
