### ISSUE TITLE
Display Superusers

### ISSUE THREAD

**Issue by acozine** [curationexperts/laevigata#404]
As an administrator, I'd like a report that tells me which users in the database are set up as superusers and which users are set up as school approvers, so I can keep the system up-to-date with staff turnover and other changes.

**Comment by mark-dce** [comment]
Separated school-level approvers to a separate ticket - see #1029.  This one should just be about giving a report of superusers configured in the system.

**Comment by mark-dce** [comment]
This may mean a list of all users with the "admin" role.

**Comment by bess** [comment]
Now that "Manage Users" has been restored, if you sort by "Roles" all the admin users go to the top. Does this meet the requirement?
![admin_users.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5515e9ab52d65b2000638516/125516c66e82c728ace21e0d46e990972a8cbcbc9cecad50e611b2843b492d762a10e17132d0bb2cbc1a2d560a5818f8120c5844fcf8d87fa1b06878dc4e17ff933c0120996048e6edc00db513bb29814e80b5bc8c48c5eb352de68d8d5d73.png)

**Comment by mark-dce** [comment]
Yes this definitely works - with data tables, we can filter on "admin".  Can you confirm that the users listed here are the expected list of Super Admins?  (It's a snapshot from https://etd.library.emory.edu/admin/users?locale=en)  If this list looks right then feel free to close the ticket.

<img width="909" alt="404 - list superusers" src="https://user-images.githubusercontent.com/3064318/42243561-6b0ff248-7ed7-11e8-878c-5c61a6b25eca.png">
