### ISSUE TITLE
Need predicate for copyright

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#405]
We have three copyright questions as part of the ETD submission process:
1. Does your thesis or dissertation contain any third-party text, audiovisual content or other material which is beyond a fair use and would require permission?
1. Does your thesis or dissertation contain content, such as a previously published article, for which you no longer own copyright?”
1. Does your thesis or dissertation disclose or describe any inventions or discoveries that could potentially have commercial application and therefore may be patented?

Each of these answers needs to be stored separately, and so each one needs its own predicate. 
- [x] Get Emily's feedback on what predicates to use
- [ ] Implement predicates in data model
- [ ] Implement predicates in submission form

Related to #247

**Comment by eporter23** [comment]
@bess @shanitajohn not finding many relevant predicates for this, but I wonder if we could make quasi-predicates using SKOS: note? Would these work software-wise?

**Comment by eporter23** [comment]
http://www.w3.org/2004/02/skos/core#note#permissions

http://www.w3.org/2004/02/skos/core#note#copyrights

http://www.w3.org/2004/02/skos/core#note#patents

**Comment by eporter23** [comment]
I'm also assuming we want to store a yes/no value in the above.

**Comment by bess** [comment]
Yes, I agree the stored value is a "yes/no"
