### ISSUE TITLE
Suppress all previews for works under embargo

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#428]
- [x] Create a generic image we'll display indicating a preview is unavailable (Shanita)
- [ ] Don't display any preview for embargoed works
- [ ] Instead, display a generic image indicating the preview is unavailable

**Comment by shanitajohn** [comment]
Here is a link to the No Preview.png: https://emory.box.com/s/33ke9edsbgtem5hexa4dzouduws3w1u0

**Comment by shanitajohn** [comment]
![No_Preview.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56a796b4884b1f13002fff7c/125516c66e82c728ace21e0d46c69ba5139086bf86eca801e81fe086264c22703d46f96925dde72be7142c0458091aff155f5f44fda8dd2ca0e23426984019af80330b2b9b645bf9fa9015ad02bb2a8a4a85b6ba8f4dc8ee3c2de68d9d02.png)

**Comment by shanitajohn** [comment]
![No_Preview_sm-01.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56a796b4884b1f13002fff7c/125516c66e82c728ace21e0d46c69ba5139086bf86eca87cb750bdc478046b313916ac217586f76ae5002e590b0c46aa460d5812a8aadd2ca6b63d21de5b0db9d93b4d68d47f40f2ecdd42e64bef62994597b5bd804dc5e83d23e28a86483c170c1b9bb2.png)
