### ISSUE TITLE
Enforce embargo on FileSet view page

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#430]
If an embargo is in place, don't allow an unauthorized user to go directly to the show page for the embargoed file set, even if they somehow know the noid of that file set

**Comment by mark-dce** [comment]
@bess @shanitajohn - Isn't this kind of a security risk that we need to prioritize even if Emory hasn't?  I.E. does this become a critical urgent priority the minute files are exposed that should be embargoed?

**Comment by mark-dce** [comment]
Is this equivalent to supporting the default Hyrax embargo cascade functionality and ensuring something similar happens in the embargo job?
