### ISSUE TITLE
Disable database authentication in production mode

### ISSUE THREAD

**Issue by val99erie** [curationexperts/laevigata#440]
We need a way to be able to log into the app in development mode that doesn't require us to get fake Shibboleth accounts from Emory.

One possible solution would be to allow Devise's database authentication if the Rails environment is in development mode, so devs can keep using database auth.

Another possible way would be to document how to run Shibboleth on our laptops, and then each dev can maintain their own set of user logins.

In production mode, the only possible way to log in should be through Shibboleth.

- [ ] In production mode, users can only log in using Shibboleth.

- [ ] In development mode, the developer has a way to log in that doesn't require access to external Shibboleth.  (i.e. I should be able to log in on my laptop, even if I'm disconnected from the internet.)

- [ ] In test mode, same as development mode:  I should be able to run the test suite without connecting to the internet.

- [ ] For DCE's demo environment(s), we need to be able to log in somehow (Probably using DCE's Shibboleth.  See comments below)

**Comment by val99erie** [comment]
DCE's demo environment is a special case because it should be a prod-like environment, but we probably want database auth so that we aren't dependent on Emory to provide us with fake Shibboleth accounts.

One possible solution would be to create a new Rails environment called `demo` or `staging` that has identical config to production.  Then we might be able to do something like this:

```ruby
env_whitelist = ['development', 'test', 'demo']
devise database_authenticatable if env_whitelist.include?(Rails.env)
```

@acozine Could you comment on how difficult/annoying would it be to have the demo env be `RAILS_ENV=demo` instead of `RAILS_ENV=production`?  If we made such a change, you'd have to make corresponding changes to your provisioning scripts, right?

**Comment by acozine** [comment]
@val99erie I could make our demo environment run in `staging` or `demo` with some changes to the provisioning and expansion of the config files. Another option is to use the DCE Shibboleth server for our demo environment. That would require adding users to the DCE Shib server with the same fields as the Emory Shib profiles/users.

**Comment by val99erie** [comment]
@acozine Oh, I didn't know that we ran our own Shibboleth.  In that case, it's probably easier to leave the demo envs as `production`.  Thanks for the info.
