### ISSUE TITLE
Test access to ESD database

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#447]
- [ ] Test connection to ESD db from the Emory-hosted VM
- [x] Test loading Registrar's CSV data into Emory DB service.
~~Setup proxy service for connections from AWS~~
~~Schedule next-step meeting for testing from AWS~~

**Comment by rotated8** [comment]
@bess @acozine @SolomonHD Updated acceptance criteria above.

**Comment by acozine** [comment]
Per discussion of Emory concerns after standup today, here is the data the ETD app needs and how it will be used:

ESD:

- Emory faculty names for the Committee Chair and Committee Member dropdowns 
- Emory faculty contact information (email, with NetID as a backup when email is nil) for notifications to faculty when student ETDs are reviewed/approved

Registrar:

- Student graduation status for greenlighting ETD publication
- Student ppid to match graduation status to ETD user record (from Shibboleth)
- If the student is submitting to ProQuest, student home address

We will also submit a student post-graduation email address to ProQuest - this will be supplied within the ETD app by the student.

So there's a tradeoff between data access and offsite data storage. With live queries of the Registrar data, the ETD app can simply relay student addresses to ProQuest; with periodic updates, the ETD app must store student addresses locally. This is only for students who are submitting to ProQuest, and we can delete the data once the ProQuest submission is complete. However, this would be a change from the original ART review discussion.

Immediate Next Steps:
- [ ] confirm the mechanism for getting the data sets
- [ ] get sample data sets

**Comment by rotated8** [comment]
Superceded by #483
