### ISSUE TITLE
Rename emory-stress-test.curationexperts.com

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#464]
- [ ] Rename emory-stress-test.curationexperts.com to training.curationexperts.com

**Comment by acozine** [comment]
Instead of renaming it, I'd like to propose adding an ALIAS record, so either address should bring up the same site on the same server.

**Comment by acozine** [comment]
Redirect is in place - training.curationexperts.com takes you to the stresstest server/site. Actually renaming the server would involve changes to Shibboleth on both the DCE side and the Emory side.
