### ISSUE TITLE
Admin user management screen is broken

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#467]
- [x] remove big blank space at top of screen
- [x] display user display name, uid, and ppid in user management screen (currently blank)

**Comment by bess** [comment]
We believe this will be fixed in core hyrax and we should wait to get the fix in a future upgrade.

**Comment by bess** [comment]
@little9 Can you take a look and give us an effort estimate on this?

**Comment by little9** [comment]
@bess Is there a demo server still up that I can look at this to see what it looks like?

**Comment by bess** [comment]
@little9 See https://qa-etd.library.emory.edu/admin/users?locale=en You have to log in as tezprox. Ask me if you don't have the password.
