### ISSUE TITLE
When I save the form I should see all of the content on the show page

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#474]
**ACCEPTANCE CRITERIA** 
- [x] All the fields I fill in should appear on the show page according to the layout of the wireframes 
- [x] For fields that are not displayed on the show page (for example post-grad email) check the Rails console for the Fedora console to make sure the data's there

**Comment by shanitajohn** [comment]
Related to #462

**Comment by val99erie** [comment]
Known broken fields:
- [ ] committee members
- [ ] committee chair
- [ ] post-grad email

**Comment by val99erie** [comment]
Still left to investigate:
- [ ] Abstract
- [ ] Table of contents
