### ISSUE TITLE
Create Program Tab

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#493]
To minimize scrolling, divide content on About Me into separate tabs, About Me and About My Program. 
- [ ]  Reference these designs for placement & styling (updated 07/10/17): https://emory.box.com/s/jpg7umsu32rnqih4ykpx2irmwjhuvz8c
- [ ] Content for the tag is in this spreadsheet. https://docs.google.com/spreadsheets/d/1MxOKKNqqhHZrAzhEfNdvx3FSn4aw-TundiGlVUr6744/edit?usp=sharing

**Comment by mark-dce** [comment]
Superseded by #1082, #1083, #1087
