### ISSUE TITLE
Additional Metadata to Supplemental Files

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#507]
**STORY** 
As a depositor, when I am on the Supplemental Files tab, after I have uploaded my supplemental file I should have the ability include additional metadata about my file.

**ACCEPTANCE CRITERIA**
- [x] After a supplemental file is uploaded, an “Show Additional Metadata” button should appear in relation to the file 
- [x] Clicking the “Show Additional Metadata” button should expand down to display additional metadata fields
- [x] Once the “Show Additional Metadata” button has been clicked it should read “Hide Additional Metadata” 
- [x] Click “Hide Additional Metadata” should collapse the Title, Description and File Type fields
- [x] I should be able to add a Title to my supplemental file 
- [x] I should be able to write a brief Description of my supplemental file 
- [x] I should be able to choose a file type from a File drop down (Ticket #207)
- [x] I should be able to somehow, save or retain the additional metadata I’ve added (Save button)
- [x] If I have supplemental files I am required to include the Title and Type fields in the additional metadata 
- [x] What I put in the Title field should replace the filename on the ETD show page
- [x] The Description should display in Parenthesis after the File Label on the ETD show page
- [x] I should be able to see the additional metadata I’ve added when I preview my ETD prior to submission
- [x] The file type should not display on the ETD show page

**WIREFRAMES**
https://emory.box.com/s/3zp0gewlg28g5ewalhjfeghqnn55qbgh

**Comment by shanitajohn** [comment]
@bess @jenlindner @val99erie Is this ticket written properly?

**Comment by bess** [comment]
@jenlindner is going to start by creating the UI interaction to submit additional metadata
Then, @bess will follow the pattern we already established for primary and subpplemental files and ensure the metadata is getting persisted to the file objects.
