### ISSUE TITLE
Can't add more than one Keyword

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#519]
**ISSUE**
Clicking "Add another Keyword" has no effect. I should get another blank text field and the option to add as many as I choose.

**STEPS TO REPRODUCE A**
1) Start a new ETD
2) Go to the "My ETD" tab
3) Enter three research fields (the "Add another Research Field" button should dissapear)
4) Enter a keyword
5) Click the "Add another Keyword" button
*Expected result:* I get a new blank keyword field
*Actual result:* The button appears to depress, but nothing happens

**STEPS TO REPRODUCE B**
Follow steps 1-5 Above  

6) Click the "Remove" button on one o the research fields
*Expected result:* I have 3 Research Field entries and a button to add a third 
*Actual result:* There is still no "Add Another Research Field" button
7) I have to delete two research fields before the button reappears

**STEPS TO REPRODUCE C**
Follow steps 1-7 Above  

8) Add a second research field 
9) Add an additional keyword
10) Attempt to add an additional research field
*Expected result:* There is an "Add another Research Field" button I can click
*Actual result:* The "Add another Research Field" button disappears whenever I have two research fields listed and then click on the "Add another Keyword" button

**ACCEPTANCE**
- [ ] There is an active "Add Another Research Field" button any time there are less than three fields entered
- [ ] If I have three research fields shown and then delete one, the "Add another Research Field" is visible and enabled
- [ ] If I have three research fields shown, I can add any number of Keyword fields

**Comment by bess** [comment]
@shanitajohn I can't replicate this. Where are you seeing this behavior? What browser are you using? I just tested on emory-stress-test using chrome and it works for me.

**Comment by shanitajohn** [comment]
I'm using Chrome and I'm logged in as Shanita / 123456. Clicking the button didn't do anything for me. I tried the process all the way through twice just to make sure it wasn't a glitch. I'll try again now too just to be sure.

**Comment by shanitajohn** [comment]
Works for me now

**Comment by shanitajohn** [comment]
Reopening. This bug occurred for Rachel during QA of https://qa-etd.library.emory.edu/

**Comment by mark-dce** [comment]
I believe this is consistently reproducible and related to the logic controlling the buttons.  See the updated detailed steps to reproduce and acceptance criteria in the main issue description above.
