### ISSUE TITLE
Provide a configurable list for Research Fields

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#52]
See Step 14 of the submission manual

**Comment by shanitajohn** [comment]
Created a sample version of this .csv here: https://emory.box.com/s/877m5ouglzg8a7sq383a5x2one5bgi4b

It will need to be replaced with the real one from Proquest.

**Comment by shanitajohn** [comment]
Related to #149

**Comment by bess** [comment]
Just merged the research fields, and they look great! One more acceptance criteria, though. We need to go back and ensure all the fields are in there. Looks like we just have a sub-set right now.

**Comment by rotated8** [comment]
Config file in app: https://github.com/curationexperts/laevigata/blob/about-me-UI/config/authorities/research_fields.yml

**Comment by rotated8** [comment]
@shanitajohn @bnash108 Will we get a list of fields from the current application, or from ProQuest?

**Comment by bess** [comment]
@rotated8 I believe we just need to copy the fields from the current application.

**Comment by bnash108** [comment]
@rotated8 I've requested an updated list of research fields from ProQuest b/c I know the list we have in current ETDs is a little outdated. I also asked Jay to pull the current list so you would have it for reference.

**Comment by bess** [comment]
I'm closing this ticket and I opened a new one to track the updating of the config file with the latest data. See ticket #292
