### ISSUE TITLE
Editing a submitted ETD doesn't show what the embargo settings are

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#522]
- [x] When I go back into an ETD that has already been submitted, I need to see what the submitted values were in the form.

**Comment by shanitajohn** [comment]
Related to #638

**Comment by mark-dce** [comment]
@val99erie is this potentially covered by the work you're doing?  No worries if not, but if so, can you close this ticket when you're done?

**Comment by bess** [comment]
This seems to have been fixed in the 1.1 branch

**Comment by val99erie** [comment]
Yes, this is fixed on edit_etd branch, not on master yet.
