### ISSUE TITLE
Post graduation, admins should be able to enter an arbitrary embargo release date

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#523]
- [ ] As an admin, when I visit a post-graduation etd, and edit it, on the embargoes tab I see a calendar widget. I can pick a date from the widget, submit the form, and the embargo release date will be updated accordingly.
- [ ] It's okay to enter any date, even one in the past.

**Comment by no-reply** [comment]
This is possibly closed or replaced by the Hyrax 2.1.0 upgrade.

**Comment by no-reply** [comment]
@mark-dce can we close this after our discussion with the Emory folks last week?

**Comment by mark-dce** [comment]
No, we need to actually deploy the code and QA it in a prod-like environment.  You can move it to ready for review.
