### ISSUE TITLE
System should send notifications via email

### ISSUE THREAD

**Issue by acozine** [curationexperts/laevigata#534]
**Update description here to articulate current strategy**

Notifications for embargoes and workflow triggers should be sent via email as well as site notifications). We have a couple of options. My preference would be to route all notifications through gmail using `sendemail`. I will investigate whether this can be done with an emory no-reply address. If we can't make it work, we could run a mail server on the web server.
ACCEPTANCE:
- [ ] all notifications should be sent via email unless the user has no email address
- [ ] notifications should have a "sent from" address like `no-reply@etd.library.emory.edu`

**Comment by acozine** [comment]
Waiting on Emory email admins to provide us with an account for sending notifications. I'm going to assign this to @SolomonHD for follow-up.

**Comment by mark-dce** [comment]
**STATUS 8/20**

We have been provided the Sponsored Account MBUSSE2.

* Mark has successfully logged into shibboleth using the account.
* Mark has successfully configured DUO two-factor authentication on the account
    * Given the requirement for DUO two-factor authentication for sponsored accounts, DCE will need at least three team members to have access to ensure uninterrupted support coverage when primary support staff are unavailable.
* The current account gives the error below when attempting to access https://email.emory.edu per Emory e-mail instructions at http://it.emory.edu/office365/O365%20Mobile%20Apps.html 
* Sending a message to mbusse2@emory.edu or etd@emory.edu does not produce a bounced message.  Sending to an invalid address produces a bounce message with a 'Recipient address rejected' error
    * In order to send notifications as etd@emory.edu, DCE will require more detailed configuration information for access to the emory e-mail system from AWS or external networks
    * Until such configuration information is provided, DCE will pursue a fallback of sending e-mail notifications from the systems@curationexperts.com address
    * E-mail notifications will not be supported at the time the 8/24 Public Access Launch; e-mail notifications will be provided as part of the Q1 Hosting Update release (schedule TBD).


```:-(
Something went wrong
We couldn't find a mailbox for this recipient. Either they don't have a mailbox or don't have a license assigned.
X-ClientId: 3CE9AF9929864FCB8E447011E0CE992F
request-id 39246e16-d153-47ef-8e00-ca6fe7b2fac9
X-OWA-Error Microsoft.Exchange.Clients.Owa2.Server.Core.OwaUserHasNoMailboxAndNoLicenseAssignedException
X-OWA-Version 15.1.1385.7
X-FEServer BN6PR1001CA0028
X-BEServer BN6PR05MB2788
Date:8/20/2017 8:50:14 PM
```

**Comment by acozine** [comment]
Connection to Amazon SES is configured in `shared/config/environments/production.rb` and works at the console if you create a class and method like this:
```
 class EmoryMailer < ActionMailer::Base
  def etd_notify
    mail(to: "pick_an_address@emory.edu",
         from: "etd@aws.emory.edu",
         subject: "your subject",
         body: "body of message",
        )
  end
end
```
and use the method at the console with `EmoryMailer::etd_notifymail.deliver_now`. Next step is to hook this up to the notifications created by laevigata/hyrax.
