### ISSUE TITLE
Cron job to run GraduationService.check_for_new_graduates

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#541]
- [ ] Set up a daily cron job to run GraduationService.check_for_new_graduates

**Comment by bess** [comment]
@acozine How would you like us to set up automated jobs? Via cron? Or the whenever gem?

**Comment by acozine** [comment]
@bess cron is fine, thanks

**Comment by rotated8** [comment]
From the phone call with the registrar, we'll get their data once a week. I imagine it'll be over the weekend, but I'm not sure when exactly. All of which is to say, the cron job probably only needs to run once a week.
