### ISSUE TITLE
Training Feedback 1: Embargoed files

### ISSUE THREAD

**Issue by fpici** [curationexperts/laevigata#551]
As a School Approver and a Superuser, I want to be able to view and download embargoed files so I can evaluate the embargoed files a student deposits.

**Comment by bess** [comment]
@fpici Are you saying that you cannot view and download embargoed files? I thought this was working already. Can you give me more details about this, please?

**Comment by fpici** [comment]
Hi Bes. Yesterday during the Rollins training several of the approvers could not access any files that were embargoed. They could see the embargoed jpg but did not have the Actions dropdown to download. Perhaps it was something that occurred during the training and is all better now. Thank you for looking into this ticket :-)

**Comment by bess** [comment]
@fpici Can you give me any other information about this? Can you give me the user id of a user who couldn't access embargoed content?

**Comment by fpici** [comment]
Sorry for the delay Bess. I am going to try and duplicate this right now ...

**Comment by fpici** [comment]
![Screen Shot 2017-08-01 at 10.09.31 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58efcaa2b7100d001a59b5e8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6454f26b7191a379ef0c2b58415c4fbc30254d58eeb9cb74fce36f34985619e8d9390c7cc03a44abeed64ceb06ba208a1ed1b1bade4496fa2137a5dad11b61435c52dcbd4f3fb29a4ac259f34be0485ca2153065e375316e0a.png)
