### ISSUE TITLE
Training Feedback 2: Uppercase "ETD"

### ISSUE THREAD

**Issue by fpici** [curationexperts/laevigata#552]
As a Student Depositor and a Super User I want to see all instances of “Etd” changed to “ETD” so the term is standardized.

**ACCEPTANCE CRITERIA**
- [ ] Universally change all instances of "etd" to "ETD"

**Comment by fpici** [comment]
![About my Etd change to About my ETD..png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58efcaa2b7100d001a59b5e8/125516c66e82c728ace21e0d46c996953696c3a496a99a57a01df39c284820766910ac6b5187ec3dab0276184f2a2ad85f4a4356bcbbd671f3e57862804e0ee5853e5772c16816faecd14bb801ba21da1b82b0e8821ad2f42f67b6d5db1063474f4dcbed5727a29f41c95df64ae04b55ac1a3762e4712431.png)

**Comment by val99erie** [comment]
The fix might be: `self.human_readable_type = 'Etd'` in `app/models/etd.rb`

**Comment by mark-dce** [comment]
also 
https://github.com/curationexperts/laevigata/blob/master/config/locales/hyrax.en.yml#L17
