### ISSUE TITLE
Break out schools in Embargo tab dropdown

### ISSUE THREAD

**Issue by fpici** [curationexperts/laevigata#553]
As an Honors, Rollins, and/or Candler Student Depositor who is setting my embargoes, I want see the “Which school are you in” dropdown broken out by individual schools so I can easily identify my selection.

**Comment by fpici** [comment]
![About My Embargoes.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58efcaa2b7100d001a59b5e8/125516c66e82c728ace21e0d46c996953696c38496a99a4ea65ce293264334316546b3397f8fe62bab0021435a571aff495e5811fbafdd78f2b13c708b0d5fead7395722d42103eee9dc4be05ce36ade0d97bcae884acae93825e68a894f371d051b8afe4f78.png)

**Comment by shanitajohn** [comment]
- [ ] Change "Undergraduate Honors" to "Emory College" to be consistent with the dropdown on "About Me" tab
