### ISSUE TITLE
Update Checkbox styling on "My Supplemental Files" and "Embargoes"

### ISSUE THREAD

**Issue by fpici** [curationexperts/laevigata#554]
As a Student Depositor setting my embargoes, I want to see a more prominent display of the checkbox “I do not want to embargo my thesis …” so I can easily identify it as a selection.

**ACCEPTANCE CRITERIA**
- [x] Apply the below styling to Embargos checkbox
    - [x] Increase the text size
    - [x] Increase checkbox size
    - [x] Offset both elements in light gray box
    - [x] Box color should be consistent with Emory pattern library
    - [ ] Add a hairline rule between the description/checkbox and ADD capabilities

**Comment by shanitajohn** [comment]
Apply this styling to Embargos checkbox.
![Screen Shot 2017-07-28 at 10.51.32 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56a796b4884b1f13002fff7c/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77246456fb6b7191a379ef0c2e50415c4cbc30254d58eeb9cb74fce36f34985619e8d9390c7cc03a44abeed64ceb06ba208a1ed1b1bade4496fa2137a5dad11b61435c52dcbd4f3fb29b4dc259f34be04f50a3113060e075336e0a.png)
