### ISSUE TITLE
Update PDF format notification for primary file

### ISSUE THREAD

**Issue by fpici** [curationexperts/laevigata#555]
As a Student Depositor who is uploading my primary files as a word document, I want to see a more prominent color display of the error message “The Primary must be a file in the .pdf format,” so that I can easily see what I need to do for a successful deposit.

**ACCEPTANCE CRITERIA**
- [ ] Change copy to "The Primary file must be in PDF format"
- [ ] Make the alert box the same length as the green box above 
- [x] Make copy bold
- [x] Make notification block red for "alert"

![Screen Shot 2017-07-28 at 12.20.24 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56a796b4884b1f13002fff7c/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77246456fb6b7191a379ed0c2951415d4abc21254d58eeb9cb74fce36f34985619e8d9390c7cc03a44abeed64ceb06ba208a1ed1b1bade4496fa2137a5dad11b61435c52dcbd4f3fb29b4dc259f34be04f53a6163264e771366e0a.png)

**Comment by fpici** [comment]
![As a primary Pdf.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58efcaa2b7100d001a59b5e8/125516c66e82c728ace21e0d46c987da22c293bb86e4be51bd1dc0902f046b313916ac217586f76ae5002e590b0c46aa460d5812a8aadd2ca6b63d21de5b0db9d93b4d68d47f40f2ecdd42e64bef62994597b5bd804dc5e83c24e18b864b37190c1f9bb2.png)

**Comment by mark-dce** [comment]
Can we change the actual error text to "The Primary file must be in PDF format"?

**Comment by little9** [comment]
There's two versions of the wording above. Right now it is "The Primary must be a file in the .pdf format" Should we keep ".pdf" or make it "PDF"? Also, I could have this look like an actual warning like so:

![Screenshot from 2017-07-31 11-52-08.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/589de7daddc0c81a00399ded/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227e49f37c3dd6b268ee1336545d424ea453444d04bea6d37ef5f22e7a985903b982655973933a47f8ebd618bf01bb71df4883e2b4dc5edcfa7f74b9dfd0126754505a9bf54f36a1934acd58f74ee04a5ca2153e65e2647b.png)

**Comment by shanitajohn** [comment]
The second piece of acceptance criteria wasn't completed. The text is still incorrect.
