### ISSUE TITLE
Provide detailed estimate for #507

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#557]

**Comment by shanitajohn** [comment]
**Here's how to do  the collapsable fields**

To toggle a specific section of a form, you use the css collapsing style.  

There’s a good overview here:
https://www.w3schools.com/bootstrap/bootstrap_collapse.asp

In Hyrax, the view code is here:
https://github.com/samvera/hyrax/blob/master/app/views/hyrax/base/_form_metadata.html.erb#L10-L17
the related javascript and css is included from bootstrap here:
https://github.com/samvera/hyrax/blob/master/app/assets/javascripts/hyrax.js#L12
Overall, you can see all collabsible section related code examples in hyrax with this search:
https://github.com/samvera/hyrax/search?utf8=✓&q=collapse&type=

**Comment by jenlindner** [comment]
Here are the things that seem hard to me about sending the metadata for the supplemental files to the server. 

The files are uploaded without any user intervention, it's handled by ajax, by two very different gems, for local and cloud file access. When the file names appear on the page, they have already been uploaded. It seems difficult to me to try to interrupt that in the two gems, and ask for the student to fill out titles and descriptions for each file as they upload each one.

It seems a lot simpler to achieve by asking the student to fill in new fields, including the filenames of the files they just uploaded, so we can associate each file with its respective title and description later, when the ETD is submitted. This means we should validate that the filename they enter to associate with a title and description matches the one we've uploaded.

**Comment by bess** [comment]
Agreed we shouldn't try to interrupt or replace the upload function. Uploading a file immediately creates a Hyrax::UploadedFile object. Could we have a UI that watches for the creation of that object, and then presents the opportunity to further describe the already-created UploadedFile rails object? Metadata could be persisted to the UploadedFile object (it's just a temporary ActiveRecord object) and copied to the ETD later on, during the AttachFilesToWorkJob. That's how I'm persisting the "primary" vs "supplementary" attribute on files already. @jenlindner I think we should work on this together.
