### ISSUE TITLE
Department is lost when editing an ETD

### ISSUE THREAD

**Issue by val99erie** [curationexperts/laevigata#570]
Steps to reproduce:

1. Edit an existing ETD record
2. Notice that the 'Department' field is blank and is greyed out.
3. If you toggle to a different school, and then back to the correct school, then the field is no longer greyed out, and you can set the department again.

Expected behavior:

When I click the button to edit the ETD, the correct department should already be filled in on the form, and the field should not be greyed out.

**Comment by jenlindner** [comment]
I'm not sure this is incorrect. The department is dependent on the school, and I can see why you wouldn't be allowed to edit it without changing schools. @shanitajohn, what do you think?
