### ISSUE TITLE
Upload Original / PDF / Supplemental files

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#59]
PDF - Required (check MIME type) - One and only one
Original - Required (any MIME type) - One or more
Supplemental - Optional (any MIME type) - Zero or more

File size limit: 2GB on Emory Side
Overall record limit for all files: 4GB currently limited by PHP

**NOTE** Confirm whether to require the original

**NOTE** Follow-up on how to handle really large submissions (i.e. multiple high resolution video supplemental files)

**Comment by shanitajohn** [comment]
@bess @jenlindner - Can this ticket be closed? I'm cleaning up the backlog and I feel like its criteria is covered in other tickets. If not, that's ok too, we can leave it.
