### ISSUE TITLE
Update student dashboard

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#592]
**ACCEPTANCE CRITERIA**
- [ ] Remove create collection from beneath “My Dashboard” 
- [ ] Remove View collections from beneath “My Dashboard” 
- [ ] Remove create collection from right side navigation below “Joined on…” 
- [ ] Remove View collections from right side navigation below “Joined on…” 
- [ ] Rename “Create Work” to be “Submit ETD” 
- [ ] Rename “View Works” to be “View ETD” 
- [x] Reorder top - right hand navigation, “English, Administration, Dashboard, Notifications, user logout” 
- [ ] Remove dropdown menu from Dashboard navigation

**MOCKUP**
![Screen Shot 2017-08-04 at 11.47.28 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56a796b4884b1f13002fff7c/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6454f76b7191a379ee0c2f56415d46bc30254d58eeb9cb74fce36f34985619e8d9390c7cc03a44abeed64ceb06ba208a1ed1b1bade4496fa2137a5dad11b61435c52dcbd4f3fb29b4dc259f34be34c50a6133361e370356e0a.png)

**REMOVE**
![Screen Shot 2017-08-03 at 3.06.29 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56a796b4884b1f13002fff7c/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6454f06b7191a37bf1122d4f5d565ecc3c4a4356bcbbd671f3e57862804e0ee5853e5772c16816faecd14bb801ba21da1b82b0e8821ad2f42f67b6d5db1063474f4dcbed5727a29f41c95df649e04857a41a3564e6742431.png)

**REMOVE**
![Screen Shot 2017-08-04 at 11.58.12 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56a796b4884b1f13002fff7c/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6454f76b7191a379ee0c2e59415e4cbc30254d58eeb9cb74fce36f34985619e8d9390c7cc03a44abeed64ceb06ba208a1ed1b1bade4496fa2137a5dad11b61435c52dcbd4f3fb29b4dc259f34be34c50a6123764e77f346e0a.png)

**Comment by mark-dce** [comment]
Becomes simplified "My ETDs" view in v2.0.0

<img width="903" alt="592- my works" src="https://user-images.githubusercontent.com/3064318/44700301-043bd080-aa4e-11e8-8bc2-9a2918549a12.png">
