### ISSUE TITLE
Change Uid label to say "Network ID"

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#594]
**STORY**
As a non-technical person, attempting to login to the ETDs, I'm not going to know what a Uid is so I won't know what I'm expected to type in the form. 

- [ ] Change the "Uid" to "Network ID" on login screen

![Screen Shot 2017-08-08 at 9.10.35 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56a796b4884b1f13002fff7c/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6454fb6b7191a371f1132b4f5c5a5edd3c4a4356bcbbd671f3e57862804e0ee5853e5772c16816faecd14bb801ba21da1b82b0e8821ad2f42f67b6d5db1063474f4dcbed5727a2904bce52f74ee14f57a4153e66e171337855d9.png)

**Comment by acozine** [comment]
I don't think we need to change this - in production we won't allow database authentication, so this screen will never be seen by any Emory students
