### ISSUE TITLE
Submission Agreement text and checkbox

### ISSUE THREAD

**Issue by fpici** [curationexperts/laevigata#610]
As a student assenting to the Submission Agreement on the "Review and Submit" page, I want to see larger text in the agreement language and I want to see the checkbox and associated sentence on a separate line from the agreement text.

**Comment by shanitajohn** [comment]
**ACCEPTANCE CRITERIA** 
- [ ] Give the text block a title "Submission Agreement" 
- [ ] Set submission agreement in a well  (http://getbootstrap.com/components/#wells)
- [ ] Move checkbox and agreement statement onto its own line
- [ ] Increase the size of the "I agree" statement copy

**Comment by bess** [comment]
@shanitajohn I did most of this ticket, but when I try to put the submission agreement in a bootstrap well it messes up the footer display in a way I could not quickly diagnose. Okay to move forward as-is, given our time crunch?
