### ISSUE TITLE
Redirect requests for pre-existing ETDs

### ISSUE THREAD

**Issue by acozine** [curationexperts/laevigata#611]
Prior to the completed migration, legacy ETD content will remain available at legacy-etd.library.emory.edu. As a user trying to find an ETD that was submitted in 2014, I'd like a clear indication that all content may not be available on  etd.library.emory.edu and the legacy site. 

**ACCEPTANCE**
- [x] There is prominent text on the homepage that says something like  
>Migration in progress, if you can't find the document you're looking for, please visit our legacy ETD site at https://legacy-etd.library.emory.edu
- [x] When a user searches, the bottom of the search results page displays similar text.
- [x] If no search results are found, the application displays a message that additional documents may be available at https://legacy-etd.library.emory.edu

**Comment by shanitajohn** [comment]
Please use the blue Emory "information" alert styling: 
http://template.library.emory.edu/styleguide/patternlibrary/patterns/molecules-50-messaging/index.html
