### ISSUE TITLE
confirm religion departments and subfields are correct

### ISSUE THREAD

**Issue by jenlindner** [curationexperts/laevigata#629]
Where do we get the metadata that distinguishes between the Religion subfields in the Laney Graduate Religion department, and the Religion subfields in the Emory College Religion and Anthropology department?

**Comment by rotated8** [comment]
The subfields are currently a little off. They should match the subfields in this spreadsheet: https://emory.app.box.com/file/176566010762, on the Laney Graduate School tab. Specifically, Comparative Literature and Religion is no longer offered and can be removed, and American Religious Cultures and (separately) Jewish Religious Cultures can be added.

The Religion and <Something> departments in Emory College I believe correspond to dual degrees, and should have the same subfields as the Religion department.

**Comment by jenlindner** [comment]
thank you @rotated8, that was very helpful and I updated the yml in an open PR.
