### ISSUE TITLE
Remove save buttons from application

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#648]
**ACCEPTANCE**
OPTION 1
- [ ] Change the save button to take me to the next tab - i.e. change the text to "Proceed" and have the button link to the anchor for the first item on the next tab

OPTION 2
- [ ] Remove the button and put highly visible text at the bottom of the form that says something similar to "Please proceed to the next Tab to continue the submission process"

COMMON TO BOTH OPTIONS
- [ ] Add the same behavior at the bottom of all tabs (except for the last one)

**Comment by val99erie** [comment]
Note: There are some feature specs that currently use those buttons.  We'll have to figure out a different way to make those work.
