### ISSUE TITLE
Can't connect to Box from QA

### ISSUE THREAD

**Issue by jenlindner** [curationexperts/laevigata#653]
I tried to upload a supplemental file from the cloud button, and was not logged into BOx already, and received a connection error. Here's a screenshot of the error:

**Comment by acozine** [comment]
Added credentials for Box to all three Emory environments. @jenlindner please re-test, close this ticket if you confirm it's fixed.

**Comment by jenlindner** [comment]
Hi @acozine , same error from Box on QA('redirect_uri_mismatch'), but fine on emory.curationexperts.com and emory-stress-test (although still have Google showing as possible drive to connect to, on those two).

**Comment by acozine** [comment]
Ah, got it. The default redirect is to box.com itself. I've updated the redirects on all three of the new sites. Works for me on QA and staging. Sorry for the duplication of work, but now I really want to be sure it works for others besides me.

**Comment by jenlindner** [comment]
Works for me on QA now, @acozine.  :-)
