### ISSUE TITLE
Remove unpopulated links

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#676]
**ACCEPTANCE**
For the initial release
- [x] the `About` link does not show up on navigation bar
- [x] the `Help` link does not show up on navigation bar
- [x] the `Contact` link does not show up on navigation bar
- [x] we have tickets for the proper behavior and content for each of these links for the next interim release

**Comment by bess** [comment]
Tickets #680, #681, and #682 opened to track populating these menu items
