### ISSUE TITLE
Unable to submit work on emory.curationexperts.com

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#68]
**ISSUE**
I'm unable to contribute new work and get an error message.

**STEPS TO REPRODUCE**
1. Create a user account & log in
1. Click on the "Dashboard" link in the upper left navigation bar
1. Select "My Dashboard" from the dropdown choices
1. On the "My Dashboard" page, click the "Create" icon

**EXPECTED RESULTS**
I go to a page where I can enter metadata and upload my file.

**ACTUAL RESIULTS**
I get an error "We're sorry, but something went wrong. If you are the application owner check the logs for more information" at the path http://emory.curationexperts.com/concern/etds/new?locale=en

**Comment by mark-dce** [comment]
**NOTE** I tested the steps to reproduce the issue against my local development environment and the error does not occur.

**Comment by acozine** [comment]
Gist of stacktrace: https://gist.github.com/acozine/bfff3f0531f649788039b8933cf6e804

**Comment by acozine** [comment]
I skipped a step in setting up the environment - I needed to create a default administrative set with the command `rake hyrax:default_admin_set:create` - it works now.
