### ISSUE TITLE
Populate top level About tab

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#680]
**Question**
What should go under the "About" tab on the front screen?

**ACCEPTANCE**
- [ ] The "About" tab on the front page is visible
- [ ] When I click the "About" tab I am presented with information about this ETD submission system

**Comment by fpici** [comment]
Hi Bess. Not sure where the "About" tab is on this front screen that you refer to :-)

**Comment by mark-dce** [comment]
This has been addressed in the homepage redesign.
