### ISSUE TITLE
Populate top level Help tab

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#681]
**Question**
What should go under the Help tab on the front page?

**ACCEPTANCE**
- [ ] The "Help" tab on the front page is visible
- [ ] When I click on the help tab I get information about how to ask for help

**Comment by fpici** [comment]
Hi Bess. We want this text and links to the **Help Form**, **Instructions**, and **FAQ** to be the same text that will appear in the footer "ETD Help."  Kristian is helping us with publishing the pages and links from the old site to the new site. After we meet today at 9:30, I should know more. In the meantime, here is the text for the "Help" tab: 

**Help**

How do I get help with my thesis or dissertation submission?

First, check whether our **instructions** or **frequently asked questions** pages answer your question.
Use our **help form** to report problems and send questions about the ETD submission website.
Contact your school or program's administrator or ADAP with general policy and procedural questions about submitting your thesis or dissertation.

**Comment by fpici** [comment]
Hi Bess. Here an newly updated link to the Help tab: http://sco.library.emory.edu/etds/help-form.html

**Comment by mark-dce** [comment]
There are now FAQ, Contact, and ETD help links in the footer of the application - see https://etd.library.emory.edu/?locale=en
