### ISSUE TITLE
Populate top level Contact tab

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#682]
**Question**
Do we want the top level "contact" tab? If so, where should the messages be sent?

**Comment by fpici** [comment]
Yes we would like the top level Contact Us tab: It can point here: http://sco.library.emory.edu/etds/contact.html

**Comment by shanitajohn** [comment]
Footer contact points to the correct URL.

**Comment by mark-dce** [comment]
Contacts are now linked in the footer - see https://etd.library.emory.edu/?locale=en
