### ISSUE TITLE
"Share Your Work" button doesn't work on emory.curationexperts.com

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#69]
**ISSUE**
The "Share Your Work" button on the home page does not seem to do anything on the demo server.

**STEPS TO REPRODUCE**
1. Visit http://emory.curationexperts.com
1. Click on the "Share Your Work" button

**EXPECTED RESULT**
* Authenticated users should be taken to their Dashboard
* Unauthenticated users should be taken to a login page

**ACTUAL RESULT**
Nothing happens when I click the button

**NOTE** I tested the same steps in my local development environment and the button works as expected.

**Comment by mark-dce** [comment]
**UPDATE** It looks like the button works the very first time after deploy or after I log in, but after that first time if I go back to the home page, the button no longer works.

**Comment by acozine** [comment]
Confirmed and reproduced. When I click on the Share Your Work button, nothing happens in the UI, and there's no output in the production log. The hover text on the button is `emory.curationexperts.com/?locale=en#`.

**Comment by acozine** [comment]
The button works to redirect a non-logged-in user to the login page on the sandbox. But for the logged-in user it does nothing.

**Comment by rotated8** [comment]
The button triggers UI to choose which work type you wish to create _when there are multiple work types_.

**Comment by rotated8** [comment]
Created projecthydra-labs/hyrax#835.
