### ISSUE TITLE
Update links in the footer

### ISSUE THREAD

**Issue by fpici** [curationexperts/laevigata#695]
**STORY**
Update the links in the footer and "Help"

**ACCEPTANCE CRITERIA**
- [ ] Update Frequently Asked Questions link: http://sco.library.emory.edu/etds/faq.html 

- [ ] Update Contact Us link:  http://sco.library.emory.edu/etds/contact.html

- [ ] Update ETD Help link: http://sco.library.emory.edu/etds/help-form.html 

- [ ] Update Copyright & Patents link: http://sco.library.emory.edu/etds/intellectual-property.html

- [ ] Update Policies & Procedures link: http://sco.library.emory.edu/etds/policies.html

- [ ] Update Access Restrictions link: http://sco.library.emory.edu/etds/embargo.html

- [ ] Update the Help TAB: http://sco.library.emory.edu/etds/help-form.html

**Comment by fpici** [comment]
Me again. I made a quick change to the FAQ: http://sco.library.emory.edu/etds/etd-static/pages/faq.html

**Comment by fpici** [comment]
Me again and again. Kristian just came by and says he wants to update these inks to take out the "/etd-static/pages" part of the url. He is doing this now and I will have an updated set of links momentarily :-)

**Comment by fpici** [comment]
New and Improved links without the "/etd-static/pages" 

Here are the updated links to the following pages:

Help TAB: http://sco.library.emory.edu/etds/help-form.html

Footer:

Frequently Asked Questions  http://sco.library.emory.edu/etds/faq.html 

Contact Us:  http://sco.library.emory.edu/etds/contact.html

ETD Help: http://sco.library.emory.edu/etds/help-form.html 

Copyright & Patents: http://sco.library.emory.edu/etds/intellectual-property.html
 
Policies & Procedures:  http://sco.library.emory.edu/etds/policies.html

Access Restrictions: http://sco.library.emory.edu/etds/embargo.html

Any questions, let me know :-)

**Comment by shanitajohn** [comment]
@fpici I updated the main body of the ticket to reflect the new URLs
