### ISSUE TITLE
What steps in the overall submission process are required?

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#71]
Emory team to confirm what steps in the overall submission process are required.

**Comment by fpici** [comment]
Hello there. See attached spreadsheet of ETD Required/Not required steps. Any questions, let me know. 
[DCE_required_steps.xlsx](https://github.com/curationexperts/laevigata/files/962226/DCE_required_steps.xlsx)

**Comment by shanitajohn** [comment]
Thanks, Fran. These have been updated and represented in the wireframes with an asterisk. Closing this ticket.
