### ISSUE TITLE
Derivative styling on PDF

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#718]
![Screen Shot 2017-08-18 at 3.07.16 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56a796b4884b1f13002fff7c/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6455fb6b7191a37bf1122c4f5e595ecc3c4a4356bcbbd671f3e57862804e0ee5853e5772c16816faecd14bb801ba21da1b82b0e8821ad2f42f67b6d5db1063474f4dcbed5727a29941c95df64ce44a51ac143560e5732431.png)

**Comment by shanitajohn** [comment]
[Noahs_Thesis.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56a796b4884b1f13002fff7c/125516c66e82c728ace21e0d46c69b9b2b91bc9d87ecac4ab71fbcd6395428792c07b7692ac7b670bb412357580a49fa150b0b43fcf9887af2b13a24820a19f1c32f0e2a92624cf5f2d75dad0ba8278c4c83bcbd8f4cc3ed3d21e6838d48371c1755.pdf)

**Comment by bess** [comment]
I believe this is related to the versions of the image libraries that are installed in production. I am looking into how to upgrade them.

**Comment by bess** [comment]
We believe that this will be fixed when we upgrade ghostscript to 9.19 in production. I have tested this in staging, against documents known to have been a problem previously. See https://staging-etd.library.emory.edu/concern/etds/qf85nb285. We expect to do this upgrade during the November maintenance window.
