### ISSUE TITLE
Reverse First and Last Name for Committee members on submission preview

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#726]
i.e, Bess Sadler, Emory University 

instead of 

Sadler, Bess, Emory University

**Comment by mark-dce** [comment]
Since the committee member names are entered as a single string, this depends on the submitter entering the data in `last name, first name` format.  We have no way of determining whether `Mark Hamilton Bussey` should become `Bussey, Mark Hamilton` or `Hamilton Bussey, Mark`
