### ISSUE TITLE
Which schools need the committee member section field ?

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#73]
Emory to confirm which schools need the committee member section field out

**Comment by bnash108** [comment]
Committee members field required for: Laney Graduate School, Undergraduate Honors Program, Candler School of Theology
Optional for: Rollins School of Public Health, Nell Hodgson Woodruff School of Nursing (development complete in ETDs for Nursing School, but they have not implemented on their end yet)

**Comment by shanitajohn** [comment]
Updated this in the wireframes: https://emory.box.com/s/6q7ts9597ecuwsuup2sdchel49vcsugg

Closing this ticket.
