### ISSUE TITLE
Set Eastern Timezone on servers

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#731]
**ISSUE**
The servers appear to be set at UMT, which make upload and other timestamps appear a number of hours off the actual time in Atlanta.   The discrepancy can lead to certain items appearing to be an entire day off. 

**ACCEPTANCE**
- [x] Server time reflects correct Eastern time

**EXAMPLE**
```
MARKs-MacBook-Pro-2:laevigata mark$ date
Wed Aug 23 20:20:23 CDT 2017

MARKs-MacBook-Pro-2:laevigata mark$ ssh deploy@qa-etd.library.emory.edu
Welcome to Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-1028-aws x86_64)
...

deploy@qa-etd:~$ date
Thu Aug 24 01:20:40 UTC 2017
```

Similarly
<img width="1439" alt="server timezone 1" src="https://user-images.githubusercontent.com/3064318/29645181-64e96c1a-8841-11e7-84aa-554e52e66d8b.png">

**Comment by acozine** [comment]
Automation failed us here. I have manually updated all 3 prod servers and filed a ticket on the ansible-hydra repo to fix the set_timezone role.
