### ISSUE TITLE
Touch tmp/restart.txt required after deploy

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#732]
**ISSUE**
After deploying to each environment, I consistently had to SSH into the server and `touch /opt/laevigata/current/tmp/restart.txt' before the footer text would update properly.

I attempted forcing page reloads and clearing my local browser cache, but the footer would display information still reflecting the previous release listed in `/opt/laevigata/revisions.log` suggesting that the server wasn't actually being restarted.  

If I touched the restart.txt file manually and refreshed my page, the footer updated as expected.

**STEPS TO REPRODUCE**
1. `BRANCH_NAME=branch1 bundle exec cap qa deploy`
1. Inspect the version (branch name) listed in the footer in your browser
1. SSH into the server and touch restart.text if the version does not display as expected
1. Inspect the version (branch name) listed in the footer in your browser - it should now be _branch1_
1. `BRANCH_NAME=branch2 bundle exec cap qa deploy`
1. Inspect the version (branch name) listed in the footer in your browser

**EXPECTED RESULTS**
The footer should now show _branch2_ as the footer version.

**MY RESULTS**
The footer still listed _branch1_

**Comment by acozine** [comment]
I can't reproduce this one so far. I'm deploying to staging from the master branch at
```
[alicia@mymble]~/rails_projects/laevigata$ git log
commit 5542fbeb8e001e86e03c0fa1d3b175a433ae6f34
Merge: 9cc50ec 3b7d666
Author: Collin Brittle <cnbrittle@gmail.com>
Date:   Thu Aug 24 10:42:23 2017 -0400
    Merge pull request #734 from curationexperts/fix-supplementary-in-spec
    replace supplementary in spec
```
Before first deploy:
```
ubuntu@staging-etd:/opt/laevigata$ cat revisions.log 
Branch master (at cfe548b5026db0993194f8f2b4d2e99635efdd7b) deployed as release 20170818002839 by alicia
Branch master (at 8bebdcb05a2851042e426e18280c9cb3e7304695) deployed as release 20170822035550 by mark
Branch v1.0.rc3 (at cca6fab5234ffbf54c12b5241ec69776fba8c7b2) deployed as release 20170822225023 by bess
Branch v1.0.0 (at c64241afe709a7971c2103ab88b6ef2eb08f8c58) deployed as release 20170824001128 by mark
ubuntu@staging-etd:/opt/laevigata$ 
```
Deployed with:
` BRANCH_NAME=v1.0.rc3 bundle exec cap staging deploy`
Capistrano output includes passenger restart:
```
00:32 passenger:restart
      01 mkdir -p /opt/laevigata/releases/20170824163317/tmp
    ✔ 01 deploy@staging-etd.library.emory.edu 0.098s
      02 touch /opt/laevigata/releases/20170824163317/tmp/restart.txt
    ✔ 02 deploy@staging-etd.library.emory.edu 0.099s
```
After first deploy:
```
ubuntu@staging-etd:/opt/laevigata$ cat revisions.log 
Branch master (at cfe548b5026db0993194f8f2b4d2e99635efdd7b) deployed as release 20170818002839 by alicia
Branch master (at 8bebdcb05a2851042e426e18280c9cb3e7304695) deployed as release 20170822035550 by mark
Branch v1.0.rc3 (at cca6fab5234ffbf54c12b5241ec69776fba8c7b2) deployed as release 20170822225023 by bess
Branch v1.0.0 (at c64241afe709a7971c2103ab88b6ef2eb08f8c58) deployed as release 20170824001128 by mark
Branch v1.0.rc3 (at cca6fab5234ffbf54c12b5241ec69776fba8c7b2) deployed as release 20170824163317 by alicia
```
and in Chrome I see:
![screen shot 2017-08-24 at 11 38 33 am](https://user-images.githubusercontent.com/879121/29677525-fc39fe16-88c0-11e7-8340-e0cbc36a19ce.png)

Deployed again:
`BRANCH_NAME=v1.0.0 bundle exec cap staging deploy`
and saw:
```
00:32 passenger:restart
      01 mkdir -p /opt/laevigata/releases/20170824164154/tmp
    ✔ 01 deploy@staging-etd.library.emory.edu 0.100s
      02 touch /opt/laevigata/releases/20170824164154/tmp/restart.txt
    ✔ 02 deploy@staging-etd.library.emory.edu 0.100s
```
on staging-apache:
```
ubuntu@staging-etd:/opt/laevigata$ cat revisions.log 
Branch master (at cfe548b5026db0993194f8f2b4d2e99635efdd7b) deployed as release 20170818002839 by alicia
Branch master (at 8bebdcb05a2851042e426e18280c9cb3e7304695) deployed as release 20170822035550 by mark
Branch v1.0.rc3 (at cca6fab5234ffbf54c12b5241ec69776fba8c7b2) deployed as release 20170822225023 by bess
Branch v1.0.0 (at c64241afe709a7971c2103ab88b6ef2eb08f8c58) deployed as release 20170824001128 by mark
Branch v1.0.rc3 (at cca6fab5234ffbf54c12b5241ec69776fba8c7b2) deployed as release 20170824163317 by alicia
Branch v1.0.0 (at c64241afe709a7971c2103ab88b6ef2eb08f8c58) deployed as release 20170824164154 by alicia
```
and in Chrome I see:
![screen shot 2017-08-24 at 11 47 27 am](https://user-images.githubusercontent.com/879121/29677851-124fbfd2-88c2-11e7-9666-b5c53577c647.png)

**Comment by mark-dce** [comment]
Ok, it looks like this is Safari specific - I have no idea why the touch restart works and the default capistrano passenger doesn't trigger the browser update for Safari.


SAFARI 
========
(this seems to be 100% repeatable from what I can tell)

On https://staging-etd.library.emory.edu/?locale=en
I see the footer "Version v1.0.0 updated 24 August 2017"
SHA c64241afe709a7971c2103ab88b6ef2eb08f8c58

On my system I ran
```
git checkout master
git pull
bundle install
bundle exec cap staging deploy
```

I have refreshed my browser, cleared my caches, and closed and restarted Safari.
On https://staging-etd.library.emory.edu/?locale=en
I still see the footer "Version v1.0.0 updated 24 August 2017."
SHA c64241afe709a7971c2103ab88b6ef2eb08f8c58

On my system I ran
```
ssh deploy@staging-etd.library.emory.edu
$ cat /opt/laevigata/revisions.log 
Branch master (at cfe548b5026db0993194f8f2b4d2e99635efdd7b) deployed as release 20170818002839 by alicia
Branch master (at 8bebdcb05a2851042e426e18280c9cb3e7304695) deployed as release 20170822035550 by mark
Branch v1.0.rc3 (at cca6fab5234ffbf54c12b5241ec69776fba8c7b2) deployed as release 20170822225023 by bess
Branch v1.0.0 (at c64241afe709a7971c2103ab88b6ef2eb08f8c58) deployed as release 20170824001128 by mark
Branch v1.0.rc3 (at cca6fab5234ffbf54c12b5241ec69776fba8c7b2) deployed as release 20170824163317 by alicia
Branch v1.0.0 (at c64241afe709a7971c2103ab88b6ef2eb08f8c58) deployed as release 20170824164154 by alicia
Branch master (at 5542fbeb8e001e86e03c0fa1d3b175a433ae6f34) deployed as release 20170824171749 by mark
$ touch /opt/laevigata/current/tmp/restart.txt 
$ exit
```

When I refresh my browser, I now see
"Version master updated 24 August 2017"
SHA 5542fbeb8e001e86e03c0fa1d3b175a433ae6f34

CHROME
============

Starting with https://staging-etd.library.emory.edu, I'm at the state above and see
"Version master updated 24 August 2017"
SHA 5542fbeb8e001e86e03c0fa1d3b175a433ae6f34

On my system I ran
```
BRANCH_NAME=v1.0.0 bundle exec cap staging deploy
```

When I refresh my chrome, I immediately see the expected results
"Version v1.0.0 updated 24 August 2017"
SHA c64241afe709a7971c2103ab88b6ef2eb08f8c58
