### ISSUE TITLE
Edit: My Supplemental files should retain their submission state if they're returned

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#742]
- [x] If I checked 'No supplemental files', the checkbox is checked and no other data is on the page until I uncheck it, at which point all of the upload elements should appear, as occurs on the create form. 
- [x] My supplemental files appear as they did when I uploaded them, in rows displaying their filenames, sizes and the ability to delete each one - all of the 'create' functionality, including validations.
 - [ ] ~If I entered supplemental file metadata, it appears as I entered it, and each bit is editable.~
- [x] if there are supplemental files with metadata attached when I go to edit my submission, this section should be marked as complete (i.e. gets a green checkmark)

**Comment by bess** [comment]
- [ ] If you have to edit metadata for a supplemental file you can remove it and re-submit it
