### ISSUE TITLE
Replace image on ETD Main Page with attached new image :-)

### ISSUE THREAD

**Issue by fpici** [curationexperts/laevigata#748]
We have a new image we would like to see on the Main page to replace the lovely tulips. Kristian sized it to to 6.5:1 for the widest possible monitor.

**Comment by fpici** [comment]
![NewImageForETDs.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58efcaa2b7100d001a59b5e8/125516c66e82c728ace21e0d46c6918d0a8f82ae8acfb0518169d4876b0a65633b0ba92e7391a172fd1723050c5748ab145f0910afad8e2ba6b76d248d5a5fe5877f4366846c4ff8e7df46f554f832815d84b1b68b49c0ec3a24e58e874e391c030ac4.png)

**Comment by fpici** [comment]
@rotated8 Hi Collin. Is the RAW image too small or is the image scaling not to spec? Our original scaling specs from Mark are: "We spoke to Mark Bussey and he recommended we have Kristian crop with 7.35:1 aspect ratio actually probably closer to 6.5:1 for the widest possible monitor." 
If the image we supplied will not work, I have 3 other images we can use as backups. See attached :-)

**Comment by fpici** [comment]
![0110803-12bm-f123](https://user-images.githubusercontent.com/7809072/38140625-9a78e5b4-3402-11e8-8770-02baa73b2267.jpg)

**Comment by fpici** [comment]
![0040805-09bm-f023- raw](https://user-images.githubusercontent.com/7809072/38140633-a261c32c-3402-11e8-93d3-43d7693dccb0.jpg)

**Comment by fpici** [comment]
![0012702-10bm-f019- raw -2](https://user-images.githubusercontent.com/7809072/38140643-b209ccb6-3402-11e8-925f-2464b5f3fd00.jpg)

**Comment by fpici** [comment]
![0110803-12bm-f123](https://user-images.githubusercontent.com/7809072/38140924-0a5713dc-3404-11e8-9e5f-819e506f40cf.jpg)

**Comment by fpici** [comment]
Here is the original Unscaled 
![0012702-10bm-f010- raw](https://user-images.githubusercontent.com/7809072/38140954-2d7216dc-3404-11e8-8752-226304ed8c81.jpg)

**Comment by rotated8** [comment]
I'm tagging in @kristianserrano, since he's a better judge of these things than I am.

**Comment by fpici** [comment]
@kristianserrano Thank you so much Kristian. You make great suggestions about the cover. I am intrigued at the possibility of  UI on "Content and Interaction." 

Can you elaborate on that possibility?

I will run all of this by Lisa and in the meantime, I will check with Wade to see if he would be willing to capture a proper image to use ... if we go that route.

Thank you so much for explaining what we will need! Cheers to you :-)

**Comment by fpici** [comment]
Third choice with possible cropping 
![thirdchoice](https://user-images.githubusercontent.com/7809072/39313469-176bb342-4940-11e8-81b5-4ab188a2d40c.jpg)

**Comment by rotated8** [comment]
Hey @kristianserrano, please take a look.

**Comment by kristianserrano** [comment]
@rotated8 and @fpici 
![39398614-3ea6b282-4ade-11e8-8f27-bb38a51a0322](https://user-images.githubusercontent.com/1796189/39531080-67c19110-4df8-11e8-8b86-f5397363e38b.png)

**Comment by fpici** [comment]
Here is another one.
![image2.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58efcaa2b7100d001a59b5e8/125516c66e82c728ace21e0d46e1999b2487d1ebc3abaf51ab57f5973d047d317c5ca72828d3b42de8447f020b584eac40090b43faad817db4aa2e32db025fb28c341521842f1bbeba8215be04b8278d4f81b5b88b4bc9e02f68.jpg)

**Comment by fpici** [comment]
Here is another one
![image3.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58efcaa2b7100d001a59b5e8/125516c66e82c728ace21e0d46e1999b2487d0ebc3abaf51ab57f5973d047d317c5ca72828d3b42de8447f020b584eac40090b43faad817db4aa2e32db025fb28c341521842f1bbeb98515be04b8278d4f81b2bc8948c4ef2f68.jpg)

**Comment by fpici** [comment]
Here is another one
![image4.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58efcaa2b7100d001a59b5e8/125516c66e82c728ace21e0d46e1999b2487d7ebc3abaf51ab57f5973d047d317c5ca72828d3b42de8447f020b584eac40090b43faad817db4aa2e32db025fb28c341521842f1bbeb98b15be04b8278d4f81b2bd8d4ac7e02f68.jpg)

**Comment by fpici** [comment]
Here is another one
![Images5.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58efcaa2b7100d001a59b5e8/125516c66e82c728ace21e0d46c1999b248790fccda5fd53b652fa912a5265296b51fb2f73ddb57fba157d050c0b49ac41590e10fbffdd23f0a42062c80d55b98e30063e937f03a6aa8318b500bf228c4985b2b58e4fc9ee3837aa.jpg)

**Comment by fpici** [comment]
Here is another one
![Images6.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58efcaa2b7100d001a59b5e8/125516c66e82c728ace21e0d46c1999b248790ffcda5fd53b652fa912a5265296b51fb2f73ddb57fba157d050c0b49ac41590e10fbffdd23f0a42062c80d55b98e30063e937f03a6aa8318b500bf228c4985b2b58c4ec3e13d37aa.jpg)

**Comment by mark-dce** [comment]
@rosy1280 Is this request still active?  If so, can Emory finalize a choice on an image and can Collin or Zo make a corresponding PR with the new image?

**Comment by rotated8** [comment]
@mark-dce It is active, I hope to have a PR ready next week.

**Comment by mark-dce** [comment]
@rotated8 poke - any updates?  Do we need to keep this ticket open?

**Comment by rotated8** [comment]
No, we can close it here and track it on the Emory side.
