### ISSUE TITLE
Add Google Analytics to the new ETD site

### ISSUE THREAD

**Issue by fpici** [curationexperts/laevigata#749]
From Emily Porter: Looks like we haven’t added Google Analytics to the new ETD application. Have we already talked about how to transition Google Analytics on ETDs? My suggestion is only related to the basic Google Analytics tracking code snippet (and existing Google Analytics account), and whether or not we want to relocate that HTML code snippet over to the new application from the old one?

From Rosalyn:
While Google Analytics information is useful to have, do we want to prioritize that work over the other items on this list?  Or do we want to add a ticket to the back log and lump it with everything else?

From Fran:

Perhaps Kristian Serrano would be available to help :-)

**Comment by mark-dce** [comment]
We've moved this to the backlog and would like to consider addressing this when we add google analytics to LUX
