### ISSUE TITLE
Please provide Admin Superuser Access access to all three ETD environments for new SCO Staff

### ISSUE THREAD

**Issue by fpici** [curationexperts/laevigata#750]
Anna Miles (NetID: AMILES4; Email: anna.miles@emory.edu)

Many thanks!

**Comment by acozine** [comment]
Done. Let me know if you see problems.

**Comment by fpici** [comment]
Thank you Alicia.
We will test Anna’s access tomorrow.

Much obliged in advance ☺



Frances Pici
Scholarly Repository Application Support Analyst
Scholarly Communications Office
Emory University Libraries and Information Technology
Robert W. Woodruff Library
540 Asbury Circle
Atlanta, GA 30322
404.727.7673
fpici@emory.edu<mailto:%7Cfpici@emory.edu>

Check out our new websites!
Scholarly Communications http://sco.library.emory.edu/index.html
Research Data http://researchdata.emory.edu/index.html

**Comment by fpici** [comment]
Good Morning Alicia.

Could you check Anna’s Super User access for ETD Production (https://etd.library.emory.edu/)  When she logs in, she does NOT see the User Notifications displaying 5 created records that I see.

Here view looks good in Staging and Q/A.

Many thanks in advance and oh yeah, HAPPY FRIDAY!.



Frances Pici
Scholarly Repository Application Support Analyst
Scholarly Communications Office
Emory University Libraries and Information Technology
Robert W. Woodruff Library
540 Asbury Circle
Atlanta, GA 30322
404.727.7673
fpici@emory.edu<mailto:%7Cfpici@emory.edu>

Check out our new websites!
Scholarly Communications http://sco.library.emory.edu/index.html
Research Data http://researchdata.emory.edu/index.html
