### ISSUE TITLE
What are the different embargo lengths, by school?

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#76]
Emory to provide a list of each school embargo lengths to DCE

**Comment by bnash108** [comment]
o   Honors Program: 6 months, 1 year, 2 years
o   Laney Graduate School: 6 months, 1 year, 2 years, 6 years
o   Rollins School of Public Health: 6 months, 1 year, 2 years (considering adding a 3-year option)
o   Candler School of Theology: 6 months, 1 year, 2 years
o   Nell Hodgson Woodruff School of Nursing (development work was completed to allow their students to submit; school has not rolled it out yet): 6 months, 1 year, 2 years

**Comment by bnash108** [comment]
Current embargo levels:

o   Files only
o   Files and table of contents
o   Files, table of contents, and abstract

**Comment by shanitajohn** [comment]
Thanks, this has been reflected in the updated wireframes. Creating a new ticket to develop embargo terms, closing this one.
