### ISSUE TITLE
Can school reviewers see the submitter's answers to the Copyright Questions? If so, where?

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#762]
Fran asked if school reviewers are able to see the answers the students submit in response to the Copyright questions. I know that those answers are visible on the "summary" screen before submission, but I don't see them when, as an admin, I look at a submitted ETD. This is functionality that exists in the old ETDs. 

Questions
1) Was it intentional that these answers are hidden? 
2) If not, how much work would it be to show the answers to these questions to administrators and school reviewers only? 

Depending on the answer, this ticket may be related to ticket: #716

- [ ] This information is being stored. Make it appear in the show view, but only for administrators.

**Comment by fpici** [comment]
Howdy friends. Let's hold off on this ticket for now. We are going to poll the School Approvers to see if the answers to these questions are something that they want to be able to see during their review of the student's submission. If the School Approvers don't really care, then I will cancel the ticket. The important thing is that  the students can see their answers -- which they can -- in their Preview before submission :-)

**Comment by fpici** [comment]
Hi there, me again. I polled the School Approvers and they all agreed that they do need to see the answers that the students provide for the two copyright and the one patent question.  In the past, in legacy ETDs, they use it to evaluate the student's submission and match it to the hard copy submission agreement that the student fills out. So we can take the "pause" off of the ticket and make it active again. Many thanks in advance! :-)

**Comment by shanitajohn** [comment]
Thanks for the heads up Fran, I'm making a note to factor this into the development prioritization.

**Comment by mark-dce** [comment]
FYI - it looks like we may not always have been capturing these values:

Compare https://qa-etd.library.emory.edu/concern/etds/0c483j36g.json - scroll to the bottom of the page
with 
https://qa-etd.library.emory.edu/concern/etds/ks65hc20t.json - see copyright_question_one etc. at the bottom.  

You'll probably need to log in as and admin to see those views.

**Comment by jenlindner** [comment]
It looks like the fix for this didn't get into the release, so I'm going to remove the "Release 1.1" label.
