### ISSUE TITLE
Change notification polling interval

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#777]
**ACCEPTANCE**
- [ ] client notification polling is increase to 5 minutes

**NOTE**
see https://github.com/curationexperts/epigaea/pull/523/files

**Comment by mark-dce** [comment]
...but we're running Hyrax 1.x for Emory which doesn't have this as a config setting :)
Probably time-bound this ticket to 60 minutes.  If we can find an easy override, this would have a major impact on the logs; otherwise, we can wait until we upgrade to 2.x

**Comment by bess** [comment]
Also, this setting is going away in Hyrax 2.0 -- see release notes here: https://github.com/samvera/hyrax/releases
Seems like it was causing problems? I know it's a pain, but I think we'd better leave this alone for now. It isn't a quick fix.
