### ISSUE TITLE
What view/edit permissions does the School Reviewer have?

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#78]
Confirm that is okay for school reviewers to be able to search, view, edit records from other schools (i.e. permissions will not be in place to prevent this, but records will be filtered by their assigned schools/programs)

**Comment by bnash108** [comment]
Yes, we discussed on our end and we are okay with trusting the reviewers not to review/approve records that are not within their assigned school/program, but not having permissions in the application that prevent them from doing so.

**Comment by tmiles2** [comment]
@shanitajohn  I think we are good on this question correct?

**Comment by shanitajohn** [comment]
Yes, I think we can close this -- I want to make sure that @bess @jenlindner @rotated8 @alexBLR and @mark-dce see the response. I don't believe there is a new ticket to come out of this.
