### ISSUE TITLE
Upgrade background jobs from Resque --> Sidekiq

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#786]
Community practice has been shifting from Resque to Sidkiq as our background manager.  At this point we have better automation and configuration for Sidekiq and the change will help make laevigata easier and more reliable to manage.

**ACCEPTANCE**
- [ ] The application is configured to use Sidekiq as it's background job manager
- [ ] Configuration specific to Resque is removed from the codebase
- [ ] Ensure sidekiq runs without rubyracer gem
- [ ] Remove resque monitoring from nagios
- [ ] Add monitoring for sidekiq

**Comment by bess** [comment]
Looks like we might need to install NodeJS at the system level in order for this to be a good idea, and I don't want to do that until we have an ansible build that could do that for us.
