### ISSUE TITLE
If you submit the same file as your primary pdf and as a supplemental file, it will be displayed twice in primary pdf part of show page

### ISSUE THREAD

**Issue by jenlindner** [curationexperts/laevigata#825]
It's unlikely someone would do this, but interesting that nothing prevents this display bug, either. I found it in the 1.0.5 branch, but hadn't tried this test in any previous branches.

https://qa-etd.library.emory.edu/concern/etds/3x816m604?locale=en

**Comment by mark-dce** [comment]
Need to do a quick assessment of how likely this is to occur in production and prioritize with that in mind.

**Comment by mark-dce** [comment]
Can this ticket be addressed as part of #974 ?

**Comment by mark-dce** [comment]
Fixed in Version v2.0.0 updated 28 August 2018

<img width="1089" alt="825 - fixed" src="https://user-images.githubusercontent.com/3064318/44699448-df455e80-aa49-11e8-8d69-88decc6fe347.png">
