### ISSUE TITLE
Updating Admins in Staging, QA and Prod

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#843]
**ACCEPTANCE CRITERIA**
- [x] Remove Bethany Nash as an Admin from Staging, QA and Production. 
- [x] Add Emily Porter (eporter@emory.edu) as an Admin Superuser (like Fran) in QA only

**Comment by bess** [comment]
Done!
Bethany had already been removed from prod, so no restart required for this to be in effect in production.

**Comment by fpici** [comment]
Thank you Bess!! I will ask Emily to check her access in Q/A :-)
