### ISSUE TITLE
Add sample config files

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#85]
- [ ] Add sample config files for database.yml, solr.yml, blacklight.yml, fedora.yml, etc.
- [ ] Add developer instructions OR update bin/setup script

**Comment by acozine** [comment]
Here's what we did on ADRL to make Travis work with sample files:
https://github.com/curationexperts/alexandria/blob/master/.travis.yml

**Comment by acozine** [comment]
And here's how the Goldenseal `bin/setup` script handled sample files: 
https://github.com/curationexperts/goldenseal/blob/master/bin/setup

**Comment by mark-dce** [comment]
Yup - that's effectively what I was trying to do here
https://github.com/curationexperts/laevigata/blob/config-files/bin/setup#L21-L34

The problem is having to keep the list in `bin/setup` synchronized with the list in travis - I was hoping we could just have travis run `bin/setup` but it clobbers other settings that are specific to the CI environment
https://github.com/curationexperts/laevigata/blob/config-files/.travis.yml#L11-L12

I just haven't had free time to get back to it since trying that and it failing.  The ugly fallback is to duplicate the complete file list in both `bin\setup` and `.travis.yml`

**Comment by acozine** [comment]
Ah, interesting! Could we break the config step into its own script, then have the setup script call the config script at the proper moment, and have `travis.yml` call the config script without calling the rest of `bin/setup`?
