### ISSUE TITLE
Hidden works should not submit to ProQuest

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#879]
- [x] If a work has a "hidden" status, it should not submit to ProQuest

**Comment by fpici** [comment]
@bess We just met with Rosalyn and Emily and they suggested we hold off on this request. We are discussing with Lisa and I will let you know as soon as possible if we want to proceed or not. :-)

**Comment by bess** [comment]
@fpici I already did the work. Do you want me to remove it?

**Comment by fpici** [comment]
Wow! Well, I just checked with Rosalyn and she says keep the work. And THANK YOU!!

Y’all are so darn good




Frances Pici
Scholarly Repository Application Support Analyst
Scholarly Communications Office
Emory University Libraries and Information Technology
Robert W. Woodruff Library
540 Asbury Circle
Atlanta, GA 30322
404.727.7673
fpici@emory.edu<mailto:%7Cfpici@emory.edu>

Check out our new websites!
Scholarly Communications http://sco.library.emory.edu/index.html
Research Data http://researchdata.emory.edu/index.html

**Comment by fpici** [comment]
@bess @rotated8 Hi Bess, Collin. I think this may be the ticket I just asked you about. It is in reference to my Slack message about a sensitive Dissertation that we had set as “Hidden” so it would not publish nor go to Proquest. I would like to  add: "Hidden Works should also NOT Publish."  Let me know if this needs to be a Waffle ETD or something that is a continuation of this ticket. Thank you for making it Private: https://etd.library.emory.edu/concern/etds/ks65hc22c?locale=en
