### ISSUE TITLE
Add ProQuest information to Review Page

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#881]
**ACCEPTANCE CRITERIA** 

- [x] On the review page, I should see general information about ProQuest submissions 
- [x] Copy should read: "If you are a doctoral student in the Laney Graduate School, your dissertation will be sent to ProQuest."
- [x] There should be no action associated with the copy.

**Comment by bess** [comment]
![screenshot-qa-etd.library.emory.edu-2018.02.13-19-18-13.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5515e9ab52d65b2000638516/125516c66e82c728ace21e0d46fb978826878dba87e6ab0eb55cbd913d42697f2006b12a629cad2db24d6918410a1ae95c5a5f45f4e78929b8b73f6d8b5516ecd9705e77d42103ecfadd45ea52fe32815d80bee8d944c6ef6822b1dfdc1b391e0519d8ab5a33f4911dda44e409b01301fb4e6f29b33424765595167f2d6e662eaef8d651818568a2b90262.png)
