### ISSUE TITLE
Add SSL for servers

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#89]
- [x] I can connect via https to emory.curationexperts.com - i.e. https://emory.curationexperts.com

**Comment by acozine** [comment]
AWS Certificate Manager only works with some kind of AWS load balancing - Elastic Load Balancers, CloudFront, or Elastic Beanstalk. I like the convenience and simplicity of getting certs from AWS and having them manage renewals. Moving to Elastic Beanstalk is a great idea for the ultimate hosted production environment, but it will involve a learning curve and load balancing isn't vital for sandbox machines. I'm going to split that work into two streams, and investigate getting a cert elsewhere for our sandbox machines as I learn more about load-balancing and traffic-management techniques on AWS.

**Comment by acozine** [comment]
Also, I cannot connect to http://emory.curationexperts.com - if i try, I get redirected to https:
