### ISSUE TITLE
Creating an AdminSet through the UI breaks our deploy

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#892]
If you create an admin set through the administrator dashboard, it isn't set up as expected for our workflows (maybe because we don't have a default admin set?) and it breaks our deploy process, specifically the `db:seed` task.

**Comment by mark-dce** [comment]
We haven't experienced this being an issue in production.  While it is theoretically possible that this is still an issue, it doesn't seem worth the time investment to address at this point.
