### ISSUE TITLE
Ensure all admin sets have permission templates

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#908]
Write a rake task to ensure that every admin set has a permission template.  Sometimes these get into a weird state (especially if someone has created an AdminSet through the UI -- see #892) and I run this by hand to fix it. We should have a rake task that does this, or else build it into the deploy.
```
AdminSet.all.each do |a|
  
Hyrax::PermissionTemplate.find_by(admin_set_id: a.id) || Hyrax::PermissionTemplate.create!(admin_set_id: a.id)
end
```

**Comment by mark-dce** [comment]
@bess do we still need to address this or has it been addressed during any of our recent work?

**Comment by bess** [comment]
This doesn't seem to be a problem anymore.
