### ISSUE TITLE
Set up DCE Shibboleth Test System

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#92]
- [x] Find out if Emory has a test shibboleth system and if so how to connect (Zo)
- [x] Set up test system
- [x] Integrate application authentication with the test shibboleth

**Comment by shanitajohn** [comment]
Emory has Shibboleth up and running currently. Have not yet integrated any apps. 
Zo will check to see if there is a test system.

**Comment by acozine** [comment]
Looks like Zo and I are at about the same point - I have Shibboleth up and running, but without any data in it and not connecting to any apps. @alexBLR would you be open to pairing up on the next steps?

**Comment by mark-dce** [comment]
Pasting a like to TestShib here in case it's useful: https://www.testshib.org

**Comment by shanitajohn** [comment]
Split this out into two tickets.

**Comment by acozine** [comment]
@zo and I discussed this - there is an Emory test shibboleth server, but we cannot use it until our request for specific data fields has been approved. In the meantime, we will pursue a DCE test server, connected to the DCE LDAP server, so we can confirm the generic Shibboleth connection.

**Comment by acozine** [comment]
See #324 for details. This only works right now on emory-stress-test.curationexperts.com. See #210 for next steps.
