### ISSUE TITLE
On staging - Submitting to any Rollins Environmental Health subfield causes an error

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#924]
**ISSUE** 
Currently, on staging-etd, attempting to submit an ETD from any of the Rollins, Environmental Health subfield results in the error message, "The page you were looking for doesn’t exist. You may have mistyped the address or the page may have moved." 

**ACCEPTANCE CRITERIA** 
- [ ] I should be able to submit an ETD via the Rollins School of Public Health, Environment Health Department, using subfield - Environmental Health - MPH 
- [ ]  I should be able to submit an ETD via the Rollins School of Public Health, Environment Health Department, using subfield - Environmental Health Epidemiology - MPH & MSPH
- [ ] I should be able to submit an ETD via the Rollins School of Public Health, Environment Health Department, using subfield - Global Environmental Health  - MPH

**Comment by RachelDCE** [comment]
This is still broken in v1.5.1

**Comment by RachelDCE** [comment]
I was able to submit successfully with all three subfields.
