### ISSUE TITLE
Make wireframe for search and discovery

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#95]

**Comment by shanitajohn** [comment]
**WIREFRAMES:** 
Search Results: https://emory.box.com/s/sl6vmzan5dhl2qmo3hwdsz3mrqs48ttl
Open Access:  https://emory.box.com/s/fe5n8xxrrr1e958zs8kf1etzay017gj4
Embargoed: https://emory.box.com/s/mf8fy3ivvdbqmmcj43wbk6v290171qqa
