### ISSUE TITLE
Upload Final PDF

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#96]
As Joey, an undergraduate Art Major, I want to be able to easily upload the final PDF of my thesis--so that I can complete the submission process--so that I can graduate.

**ACCEPTANCE CRITERIA**
- [x] I can designate this as my Final PDF
- [ ] I can choose a file from my local hard drive 
- [ ] The system warns me if it can't tell that its in PDF format
- [ ] I can tell if the file is uploading 
- [ ] I know when the file has been successfully uploaded 
- [ ] The system displays the file as the Primary PDF

**Comment by mark-dce** [comment]
Collin to determine if the Hydra File Sets working group has recommendations that can be used to help distinguish between final file and supplemental files.

**Comment by rotated8** [comment]
- File use vocabulary: https://wiki.duraspace.org/display/hydra/File+Use+Vocabulary
- Proposed implementation diagram (circa May 2015): https://docs.google.com/drawings/d/1ihQzx9BJq0r3bJ5fuY1ZEQwo6NVBIQvG6mz8w-BtB38/edit
- Open ticket for actual implementation: https://github.com/projecthydra-labs/hydra_file_sets_wg/issues/1

**Comment by rotated8** [comment]
A file is a Non-RDF resource in fedora, and is modeled by [Hydra::PCDM:File](https://github.com/projecthydra/hydra-pcdm/blob/master/lib/hydra/pcdm/models/file.rb)
A FileSet is an RDF resource, and is modeled [in Laevigata](https://github.com/curationexperts/laevigata/blob/master/app/models/file_set.rb)
A FileSet is created for each file uploaded to an ETD.
