### ISSUE TITLE
Re-submit this ETD to ProQuest

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#984]
Once this object has a PDFs, resubmit it to ProQuest:

- [ ] 6h440s459

**Comment by fpici** [comment]
Good Morning Bess.
Hi Bess.
 
Well the student/alum never responded BUT the Laney Admin sent me her pdf.
When I tried to add it to her record by replacing the version it failed? See below screenshot:
 
So, I am attaching her pdf to this ticket
![image001](https://user-images.githubusercontent.com/7809072/38808985-fe923e92-414f-11e8-9721-3961a615f8c6.png)
[RELIGION_COLEMAN-TOBIAS_MEREDITH_0836461.pdf](https://github.com/curationexperts/laevigata/files/1915213/RELIGION_COLEMAN-TOBIAS_MEREDITH_0836461.pdf)

 to see if you can work your magic and upload her pdf to her published record.
Let me know if you get it to work and complete with a successful “send to Proquest.”
 
Many thanks!

**Comment by fpici** [comment]
Good Morning Bess.

Well the student/alum never responded BUT the Laney Admin sent me her pdf.
When I tried to add it to her record by replacing the version it failed? See below screenshot:
 
So, I am attaching her pdf to this ticket to see if you can work your magic and upload her pdf to her published record. Let me know if you get it to work and complete with a successful “send to Proquest.” Many thanks!
[RELIGION_COLEMAN-TOBIAS_MEREDITH_0836461.pdf](https://github.com/curationexperts/laevigata/files/1915229/RELIGION_COLEMAN-TOBIAS_MEREDITH_0836461.pdf)
![image001](https://user-images.githubusercontent.com/7809072/38809055-40611e7e-4150-11e8-9365-5684f3721ff4.png)

**Comment by bess** [comment]
Thanks, @fpici ! I have re-submitted this one.

**Comment by fpici** [comment]
Bess, Yippee!! And thank you :-)
