### ISSUE TITLE
Emory email service is on probation

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#995]
Emory just got a notification that their email service with Amazon is on probation because we are sending too many messages that are bouncing (but no complaints, thankfully). 

- [x] Set up a notification so we know when an email has bounced
- [x] Set up a system so invalid emails won't be sent

**Comment by bess** [comment]
<img width="904" alt="ses_management_console" src="https://user-images.githubusercontent.com/65608/39310525-92631f7a-4938-11e8-85a3-1ae4a0f4c3aa.png">

**Comment by bess** [comment]
As of 26 April, after release 1.6.1 and processing April registrar data, our email reputation is trending in the right direction, and we now have a status of "almost healed" instead of "probation".

**Comment by mark-dce** [comment]
Continued improvement through June.  Trending to "healthy" by July.
