### ISSUE TITLE
Is our embargo notification job running?

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#997]
Emory reports that people are not getting notifications about their embargoes expiring -- look into whether we are running these jobs.

**Comment by no-reply** [comment]
I believe the embargo job as written does not actually update the work permissions. It seems to call this method, which explicitly does not lift the embargo, and leaves permissions as-is.

https://github.com/samvera/hydra-head/blob/b9f3f177d057e5611c6661a1d43b7707057ac6b3/hydra-access-controls/app/models/hydra/access_controls/embargo.rb#L17-L26

**Comment by no-reply** [comment]
See also: https://github.com/samvera/hyrax/issues/2657#issuecomment-399169889

**Comment by mark-dce** [comment]
frances pici [7:44 AM]
@bess BTW, the embargo summary of embargoes expiring in 7 days came through with the names, title, and pid of the expiring record. YIPPEE.
